{
  "name": "Рабочий отчет 1_0 — отчет по эффективности",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "ru-RU",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "ru-RU",
    "tables": [
      {
        "name": "AtomsWithExtensions",
        "lineageTag": "7df66113-8c42-4d4b-b06e-9dd97d7c104d",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "7fbaeccd-d143-4ce9-84c3-1e71b6e98989",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Version",
            "dataType": "int64",
            "sourceColumn": "Version",
            "lineageTag": "ab282fb1-509c-4a7e-952e-da59c48e4259",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Город",
            "dataType": "string",
            "sourceColumn": "Город",
            "lineageTag": "743f1756-f4a3-415d-98c1-ae73bf93a8aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Бренд авто",
            "dataType": "string",
            "sourceColumn": "Бренд авто",
            "lineageTag": "08f8cadf-5c03-467a-a2ed-d9ee2d7f8802",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Подрядчик",
            "dataType": "string",
            "sourceColumn": "Подрядчик",
            "lineageTag": "c0b188f4-52dc-413f-8377-c6956f6f2cf0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Платный",
            "dataType": "string",
            "sourceColumn": "Платный",
            "lineageTag": "021ccf0f-ec21-4269-a90f-2da54d5bd278",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Площадка рекламы",
            "dataType": "string",
            "sourceColumn": "Площадка рекламы",
            "lineageTag": "21a60ed7-9652-4933-8335-a676ac46ca1e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Кампания",
            "dataType": "string",
            "sourceColumn": "Кампания",
            "lineageTag": "8cf4406f-0fcc-4283-b8cb-b3959a30be05",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Источник",
            "dataType": "string",
            "sourceColumn": "Источник",
            "lineageTag": "37f4cc68-a28e-462e-9553-fcd97dad0744",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Канал",
            "dataType": "string",
            "sourceColumn": "Канал",
            "lineageTag": "b65604fe-58e1-477a-8e2f-1c5c4099be2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Виды РК",
            "dataType": "string",
            "sourceColumn": "Виды РК",
            "lineageTag": "f65a2aca-a6b8-4edb-aec7-e1ddabfd7268",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Группа источников",
            "dataType": "string",
            "sourceColumn": "Группа источников",
            "lineageTag": "a5cbc11d-2455-4ddc-bf99-10d22f03b25a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Бренд?",
            "dataType": "string",
            "sourceColumn": "Бренд?",
            "lineageTag": "bdb2de0c-7f22-4870-b9bb-eaf49681486b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ремаркетинг?",
            "dataType": "string",
            "sourceColumn": "Ремаркетинг?",
            "lineageTag": "d5dce16e-d558-4c29-b924-0bb34c166de6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Источник2",
            "dataType": "string",
            "sourceColumn": "Источник2",
            "lineageTag": "8c6ad309-86a0-4d96-80fc-d33a97863988",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Кампания2",
            "dataType": "string",
            "sourceColumn": "Кампания2",
            "lineageTag": "442879aa-5f6b-461a-a3ee-739422528a01",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "carBrand",
            "dataType": "string",
            "sourceColumn": "carBrand",
            "lineageTag": "29dc9000-7263-4a8a-987c-45a67b0e2064",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GA профиль",
            "dataType": "string",
            "sourceColumn": "GA профиль",
            "lineageTag": "4b2e6b8b-8588-43ff-a7e7-c6f8bbfaab73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Площадка рекламы2",
            "dataType": "string",
            "sourceColumn": "Площадка рекламы2",
            "lineageTag": "c61f7dd0-d4e3-43dc-9d6c-f34cf18cc009",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AtomsWithExtensions",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT *,#(lf)#(tab) CASE#(lf)#(tab) #(tab)WHEN [Кампания] LIKE 'Comagic ||| [[]%' OR [Кампания] LIKE 'Comagic |||%/%' THEN [Источник]#(tab)#(lf)#(tab) #(tab)WHEN [Кампания] LIKE 'Comagic |||%' AND [Бренд авто] IN (N'Mercedes-Benz',N'Audi') THEN N'Старые кампании CoMagic'#(lf)#(tab) #(tab)ELSE [Источник] END [Источник2],#(lf)#(tab)CASE WHEN [Кампания] LIKE 'Comagic ||| [[]%' OR [Кампания] LIKE 'Comagic |||%/%' THEN [Кампания]#(lf)#(tab)#(tab) WHEN [Кампания] LIKE 'Comagic |||%' AND [Бренд авто] IN (N'Mercedes-Benz',N'Audi') THEN N'Старые кампании CoMagic'#(lf)#(tab)#(tab)ELSE [Кампания] END [Кампания2]#(tab)FROM [pivotparts].[AtomsWithExtensions]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Дублированный столбец\" = Table.DuplicateColumn(Source, \"Бренд авто\", \"carBrand\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Дублированный столбец\", \"Custom\", each if [Бренд авто] = \"Audi\" and Text.Contains([GA профиль], \"volkswagen\") then \"Не задан Домен\" else [GA профиль]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"GA профиль\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"GA профиль\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of AtomId",
            "expression": "SUM('AtomsWithExtensions'[AtomId])",
            "lineageTag": "5ce755fc-623d-45f0-8b65-993c59f0b03f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Count of AtomId",
            "expression": "COUNTA('AtomsWithExtensions'[AtomId])",
            "lineageTag": "001ec2e8-486d-40be-ba51-24fa1c73d51b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Источник Иерархия",
            "lineageTag": "d41cef5e-1a47-41f0-a46d-c2edb0d773ce",
            "levels": [
              {
                "name": "Источник",
                "ordinal": 0,
                "column": "Источник",
                "lineageTag": "b422fa0e-868e-41c2-a975-da6ff25615a6"
              },
              {
                "name": "Виды РК",
                "ordinal": 1,
                "column": "Виды РК",
                "lineageTag": "86cc495b-f37b-4f92-8cd1-15ad605800c2"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "33c6c918-9334-4c32-8948-82444ce00497"
          },
          {
            "name": "LinkedQueryName",
            "value": "AtomsWithExtensions"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":17,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/AtomsWithExtensions/Source.{AtomId,0}\",\"Section1/AtomsWithExtensions/Source.{Version,1}\",\"Section1/AtomsWithExtensions/Source.{Кампания,2}\",\"Section1/AtomsWithExtensions/Source.{Источник,3}\",\"Section1/AtomsWithExtensions/Source.{Группа источников,4}\",\"Section1/AtomsWithExtensions/Source.{Канал,5}\",\"Section1/AtomsWithExtensions/Source.{Город,6}\",\"Section1/AtomsWithExtensions/Source.{Бренд?,7}\",\"Section1/AtomsWithExtensions/Source.{Ремаркетинг?,8}\",\"Section1/AtomsWithExtensions/Source.{GA профиль,9}\",\"Section1/AtomsWithExtensions/Source.{Бренд авто,10}\",\"Section1/AtomsWithExtensions/Source.{Виды РК,11}\",\"Section1/AtomsWithExtensions/Source.{Подрядчик,12}\",\"Section1/AtomsWithExtensions/Source.{Платный,13}\",\"Section1/AtomsWithExtensions/Source.{Площадка рекламы,14}\",\"Section1/AtomsWithExtensions/Source.{Источник2,15}\",\"Section1/AtomsWithExtensions/Source.{Кампания2,16}\"],\"ColumnCount\":17,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/AtomsWithExtensions/Source.{AtomId,0}\",\"Section1/AtomsWithExtensions/Source.{Version,1}\",\"Section1/AtomsWithExtensions/Source.{Кампания,2}\",\"Section1/AtomsWithExtensions/Source.{Источник,3}\",\"Section1/AtomsWithExtensions/Source.{Группа источников,4}\",\"Section1/AtomsWithExtensions/Source.{Канал,5}\",\"Section1/AtomsWithExtensions/Source.{Город,6}\",\"Section1/AtomsWithExtensions/Source.{Бренд?,7}\",\"Section1/AtomsWithExtensions/Source.{Ремаркетинг?,8}\",\"Section1/AtomsWithExtensions/Source.{GA профиль,9}\",\"Section1/AtomsWithExtensions/Source.{Бренд авто,10}\",\"Section1/AtomsWithExtensions/Source.{Виды РК,11}\",\"Section1/AtomsWithExtensions/Source.{Подрядчик,12}\",\"Section1/AtomsWithExtensions/Source.{Платный,13}\",\"Section1/AtomsWithExtensions/Source.{Площадка рекламы,14}\",\"Section1/AtomsWithExtensions/Source.{Источник2,15}\",\"Section1/AtomsWithExtensions/Source.{Кампания2,16}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "DeviceTypes",
        "lineageTag": "459a5f38-aa7d-4a6f-bfe4-998cfeac03ca",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "lineageTag": "928ed98d-a882-444d-a6d4-bfcfb25c074d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "f8cc99ab-782a-4d38-9de2-c6db6c568fd6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DeviceTypes",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT [pivotparts].[DeviceTypes].* FROM [pivotparts].[DeviceTypes]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Id\", \"Id\"}, {\"Name\", \"Name\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Id\", Int64.Type}, {\"Name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "42e9fcf5-b13c-455c-b7df-1a6b2757458c"
          },
          {
            "name": "LinkedQueryName",
            "value": "DeviceTypes"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/DeviceTypes/Changed Type.{Id,0}\",\"Section1/DeviceTypes/Changed Type.{Name,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/DeviceTypes/Changed Type.{Id,0}\",\"Section1/DeviceTypes/Changed Type.{Name,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "Pivot",
        "lineageTag": "df3ac46f-e561-48e9-abe9-83746511379b",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "c4104a1e-ab3c-45dd-aeee-b2cdc7f644ca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "lineageTag": "d7122f2f-5ac2-4b93-b31d-969eddeadd68",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Version",
            "dataType": "int64",
            "sourceColumn": "Version",
            "lineageTag": "7265f940-f2a4-4443-9d17-5f763652472e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DeviceTypeId",
            "dataType": "int64",
            "sourceColumn": "DeviceTypeId",
            "lineageTag": "a90a01cf-9f1c-441b-bb83-2f08bccf00b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Shows",
            "dataType": "int64",
            "sourceColumn": "Shows",
            "lineageTag": "a4d0483d-1458-4015-a7c0-04964a44bc0f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Spent",
            "dataType": "double",
            "sourceColumn": "Spent",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "c9a8d2f1-e8ca-4af6-add5-811a9a24be00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Clicks",
            "dataType": "int64",
            "sourceColumn": "Clicks",
            "lineageTag": "791ad62b-ded2-40b8-bd81-98a542d03980",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Sessions",
            "dataType": "int64",
            "sourceColumn": "Sessions",
            "lineageTag": "72ac7e00-6cc3-47dc-9d73-bdd197a51597",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Transactions",
            "dataType": "int64",
            "sourceColumn": "Transactions",
            "lineageTag": "f1453d09-94fb-4044-8a6c-a3f0666e97e5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "revenue",
            "dataType": "double",
            "sourceColumn": "revenue",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "6ebf3875-98ab-426d-9f21-42e7269069c4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Цель1",
            "dataType": "int64",
            "sourceColumn": "Цель1",
            "lineageTag": "8a4f0ff0-d2fc-4de5-8899-510324e3e5fd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель2",
            "dataType": "int64",
            "sourceColumn": "Цель2",
            "lineageTag": "10d3a819-2831-406c-b7b6-ffba466370ae",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель3",
            "dataType": "int64",
            "sourceColumn": "Цель3",
            "lineageTag": "52d481bd-3480-45cb-a3a9-187de66be0f0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель4",
            "dataType": "int64",
            "sourceColumn": "Цель4",
            "lineageTag": "aff3d9ee-ff7b-4e03-8abf-a364b9545d1b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель5",
            "dataType": "int64",
            "sourceColumn": "Цель5",
            "lineageTag": "24e3a361-16b7-41b6-abc4-1cd59754eed3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель6",
            "dataType": "int64",
            "sourceColumn": "Цель6",
            "lineageTag": "3eaef2c3-97aa-43cc-bcce-5520ef5b8f94",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель7",
            "dataType": "int64",
            "sourceColumn": "Цель7",
            "lineageTag": "aa905add-ceb3-46bd-ab27-9c89076bba15",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель8",
            "dataType": "int64",
            "sourceColumn": "Цель8",
            "lineageTag": "f631570c-ba31-48c9-bfa6-9f6c0eaafd53",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель9",
            "dataType": "int64",
            "sourceColumn": "Цель9",
            "lineageTag": "f29f1f7b-2e2b-4896-a906-5f7044c1203c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель10",
            "dataType": "int64",
            "sourceColumn": "Цель10",
            "lineageTag": "47623c11-2260-4d2f-9789-c78dc3b17b20",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель11",
            "dataType": "int64",
            "sourceColumn": "Цель11",
            "lineageTag": "b3369b1d-ae29-447b-acdb-85af2bc68f1f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель12",
            "dataType": "int64",
            "sourceColumn": "Цель12",
            "lineageTag": "1b7bc8d1-61b4-4ea0-b76e-7ab10029dcce",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель13",
            "dataType": "int64",
            "sourceColumn": "Цель13",
            "lineageTag": "f63f59a5-f270-496e-b134-d4c2091ed54c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель14",
            "dataType": "int64",
            "sourceColumn": "Цель14",
            "lineageTag": "c263c66a-161a-48ad-9b51-02f9d2645d99",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель15",
            "dataType": "int64",
            "sourceColumn": "Цель15",
            "lineageTag": "4c640876-9cd1-4402-94f6-238b253dcda4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель16",
            "dataType": "int64",
            "sourceColumn": "Цель16",
            "lineageTag": "e9297854-ecbf-4f61-92ca-bd4d54199232",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель17",
            "dataType": "int64",
            "sourceColumn": "Цель17",
            "lineageTag": "5d731418-da17-4fa7-b856-441ccbabf7d5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель18",
            "dataType": "int64",
            "sourceColumn": "Цель18",
            "lineageTag": "5610eaec-bda4-4d32-bf49-0df9a242d4f2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель19",
            "dataType": "int64",
            "sourceColumn": "Цель19",
            "lineageTag": "06f0309a-f8ae-498a-af43-f01bb4bc6f3a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Цель20",
            "dataType": "int64",
            "sourceColumn": "Цель20",
            "lineageTag": "c92da93a-3988-4666-a902-73e1360f5837",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Директ Расчет ср. позиции показа",
            "dataType": "double",
            "sourceColumn": "Директ Расчет ср. позиции показа",
            "lineageTag": "1ab71179-0bcf-46aa-aca6-0270a4593c15",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Директ Показы для расчёта ср. позиции",
            "dataType": "int64",
            "sourceColumn": "Директ Показы для расчёта ср. позиции",
            "lineageTag": "71512492-d7ca-4dd8-a1c8-446c998f6ef6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Директ Директ Расчет ср. позиции клика",
            "dataType": "double",
            "sourceColumn": "Директ Директ Расчет ср. позиции клика",
            "lineageTag": "33488bb0-5517-462e-b16a-060fb02cf2c6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Клики для расчёта ср. позиции",
            "dataType": "int64",
            "sourceColumn": "Клики для расчёта ср. позиции",
            "lineageTag": "d9514457-5486-4d64-9af1-23077791c719",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Директ Расчет ср. объема трафика",
            "dataType": "double",
            "sourceColumn": "Директ Расчет ср. объема трафика",
            "lineageTag": "38e7c983-6048-46c4-be29-547e83dffe13",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Расчёт средней позиции клика",
            "dataType": "double",
            "sourceColumn": "AdWords Расчёт средней позиции клика",
            "lineageTag": "f6f20aef-47c1-4756-be73-d4981ad7eef6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Клики для расчёта ср. позиции",
            "dataType": "int64",
            "sourceColumn": "AdWords Клики для расчёта ср. позиции",
            "lineageTag": "9eb177b2-ddce-4316-a555-d21dd49a0397",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Расчёт показателя качества (по показам)",
            "dataType": "double",
            "sourceColumn": "AdWords Расчёт показателя качества (по показам)",
            "lineageTag": "c720a4ea-7108-458f-baa2-a7229d4b69bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Показы для расчёта показателя качества",
            "dataType": "int64",
            "sourceColumn": "AdWords Показы для расчёта показателя качества",
            "lineageTag": "8c3ff221-f7e1-4ee2-8dca-c392c43e4ae4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Расчёт показателя качества (по кликам)",
            "dataType": "double",
            "sourceColumn": "AdWords Расчёт показателя качества (по кликам)",
            "lineageTag": "291a2d58-59ff-4f9b-b85a-684b3c853f22",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Клики для расчёта показателя качества",
            "dataType": "int64",
            "sourceColumn": "AdWords Клики для расчёта показателя качества",
            "lineageTag": "22366ec1-83df-42a7-98c7-cd4f76d5196c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Клики или сессии",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH (",
              "    RELATED ( AtomsWithExtensions[Канал] ),",
              "    \"Контекстная реклама\", \"Clicks\",",
              "    \"Таргетированная реклама\", \"Clicks\",",
              "    \"Sessions\"",
              ")",
              ""
            ],
            "lineageTag": "f52a7532-e6d4-4b48-a524-5834cc7d101c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AdWords Расчёт показателя AbsoluteTopImpressionPercentage (по показам)",
            "dataType": "double",
            "sourceColumn": "AdWords Расчёт показателя AbsoluteTopImpressionPercentage (по показам)",
            "lineageTag": "4fb46303-70bc-4120-9db0-9ad8b6e8aea3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Показы для расчёта показателя AbsoluteTopImpressionPercentage",
            "dataType": "int64",
            "sourceColumn": "AdWords Показы для расчёта показателя AbsoluteTopImpressionPercentage",
            "formatString": "0",
            "lineageTag": "47e6fe1a-baf9-4bff-8b2d-d272915d11d4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AdWords Расчёт показателя TopImpressionPercentage (по показам)",
            "dataType": "double",
            "sourceColumn": "AdWords Расчёт показателя TopImpressionPercentage (по показам)",
            "lineageTag": "38518f8e-6463-4b9b-abe9-3d1d3244c7a7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AdWords Показы для расчёта показателя TopImpressionPercentage",
            "dataType": "int64",
            "sourceColumn": "AdWords Показы для расчёта показателя TopImpressionPercentage",
            "formatString": "0",
            "lineageTag": "0fc04a82-62e1-467d-a27d-6f2427cabd8a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Facebook Лиды",
            "dataType": "int64",
            "sourceColumn": "Facebook Лиды",
            "formatString": "0",
            "lineageTag": "6589a58a-8759-4158-8d13-ab2e73a0f519",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Pivot",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT   * FROM [pivotparts].[Pivot]#(lf)where [Date] >='2019-06-01'\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Date\", \"Date\"}, {\"AtomId\", \"AtomId\"}, {\"Version\", \"Version\"}, {\"DeviceTypeId\", \"DeviceTypeId\"}, {\"Shows\", \"Shows\"}, {\"Spent\", \"Spent\"}, {\"Clicks\", \"Clicks\"}, {\"Sessions\", \"Sessions\"}, {\"Transactions\", \"Transactions\"}, {\"revenue\", \"revenue\"}, {\"Цель1\", \"Цель1\"}, {\"Цель2\", \"Цель2\"}, {\"Цель3\", \"Цель3\"}, {\"Цель4\", \"Цель4\"}, {\"Цель5\", \"Цель5\"}, {\"Цель6\", \"Цель6\"}, {\"Цель7\", \"Цель7\"}, {\"Цель8\", \"Цель8\"}, {\"Цель9\", \"Цель9\"}, {\"Цель10\", \"Цель10\"}, {\"Цель11\", \"Цель11\"}, {\"Цель12\", \"Цель12\"}, {\"Цель13\", \"Цель13\"}, {\"Цель14\", \"Цель14\"}, {\"Цель15\", \"Цель15\"}, {\"Цель16\", \"Цель16\"}, {\"Цель17\", \"Цель17\"}, {\"Цель18\", \"Цель18\"}, {\"Цель19\", \"Цель19\"}, {\"Цель20\", \"Цель20\"}, {\"Директ Расчет ср. позиции показа\", \"Директ Расчет ср. позиции показа\"}, {\"Директ Показы для расчёта ср. позиции\", \"Директ Показы для расчёта ср. позиции\"}, {\"Директ Директ Расчет ср. позиции клика\", \"Директ Директ Расчет ср. позиции клика\"}, {\"Клики для расчёта ср. позиции\", \"Клики для расчёта ср. позиции\"}, {\"Директ Расчет ср. объема трафика\", \"Директ Расчет ср. объема трафика\"}, {\"AdWords Расчёт средней позиции клика\", \"AdWords Расчёт средней позиции клика\"}, {\"AdWords Клики для расчёта ср. позиции\", \"AdWords Клики для расчёта ср. позиции\"}, {\"AdWords Расчёт показателя качества (по показам)\", \"AdWords Расчёт показателя качества (по показам)\"}, {\"AdWords Показы для расчёта показателя качества\", \"AdWords Показы для расчёта показателя качества\"}, {\"AdWords Расчёт показателя качества (по кликам)\", \"AdWords Расчёт показателя качества (по кликам)\"}, {\"AdWords Клики для расчёта показателя качества\", \"AdWords Клики для расчёта показателя качества\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}, {\"AtomId\", Int64.Type}, {\"Version\", Int64.Type}, {\"DeviceTypeId\", Int64.Type}, {\"Shows\", Int64.Type}, {\"Spent\", type number}, {\"Clicks\", Int64.Type}, {\"Sessions\", Int64.Type}, {\"Transactions\", Int64.Type}, {\"revenue\", type number}, {\"Цель1\", Int64.Type}, {\"Цель2\", Int64.Type}, {\"Цель3\", Int64.Type}, {\"Цель4\", Int64.Type}, {\"Цель5\", Int64.Type}, {\"Цель6\", Int64.Type}, {\"Цель7\", Int64.Type}, {\"Цель8\", Int64.Type}, {\"Цель9\", Int64.Type}, {\"Цель10\", Int64.Type}, {\"Цель11\", Int64.Type}, {\"Цель12\", Int64.Type}, {\"Цель13\", Int64.Type}, {\"Цель14\", Int64.Type}, {\"Цель15\", Int64.Type}, {\"Цель16\", Int64.Type}, {\"Цель17\", Int64.Type}, {\"Цель18\", Int64.Type}, {\"Цель19\", Int64.Type}, {\"Цель20\", Int64.Type}, {\"Директ Расчет ср. позиции показа\", type number}, {\"Директ Показы для расчёта ср. позиции\", Int64.Type}, {\"Директ Директ Расчет ср. позиции клика\", type number}, {\"Клики для расчёта ср. позиции\", Int64.Type}, {\"Директ Расчет ср. объема трафика\", type number}, {\"AdWords Расчёт средней позиции клика\", type number}, {\"AdWords Клики для расчёта ср. позиции\", Int64.Type}, {\"AdWords Расчёт показателя качества (по показам)\", type number}, {\"AdWords Показы для расчёта показателя качества\", Int64.Type}, {\"AdWords Расчёт показателя качества (по кликам)\", type number}, {\"AdWords Клики для расчёта показателя качества\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Показы",
            "expression": "SUM([Shows])",
            "formatString": "#,0",
            "lineageTag": "88ab781a-93e7-4fa2-8197-0a14013933ac"
          },
          {
            "name": "Расход без НДС",
            "expression": "SUM([Spent])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "1ef46578-493c-44dc-9ca0-4f7a86534b41",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Клики",
            "description": [
              "Для Контекста и соц сетей считаем клики, для бесплатного трафика и того, у чего нет кликов считаем сессии",
              ""
            ],
            "expression": "SUMX(Pivot,if([Клики или сессии]=\"Clicks\",Pivot[Clicks],Pivot[Sessions]))",
            "formatString": "#,0",
            "lineageTag": "eb5b21e5-ffb4-4084-a57c-030810dc39ee",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Сессии GA",
            "expression": "SUM(Pivot[Sessions])",
            "formatString": "#,0",
            "lineageTag": "36008ff1-293e-470c-8e65-77c2b96861f5"
          },
          {
            "name": "GA-goal —1",
            "expression": "SUM([Цель1])",
            "formatString": "#,0",
            "lineageTag": "98ee07d8-0c3b-4291-8ca0-2dc075b0f88d"
          },
          {
            "name": "GA-goal — Кнопка перехода в корзину после кнопки Заказать",
            "expression": "SUM([Цель2])",
            "formatString": "#,0",
            "lineageTag": "d09ccbca-0827-446b-9d7d-7cfe555a9906"
          },
          {
            "name": "GA-goal — Кнопка завершения оформления заказа в корзине",
            "expression": "SUM([Цель3])",
            "formatString": "#,0",
            "lineageTag": "2eb7c8df-90b0-4494-bde7-d1a24e0f61c0"
          },
          {
            "name": "GA-goal — Успешная оплата заказа",
            "expression": "SUM([Цель4])",
            "formatString": "#,0",
            "lineageTag": "283f57b5-fd37-4c4a-b624-c29cc3f16f20"
          },
          {
            "name": "GA-goal — Финал заказ подтвержден",
            "expression": "SUM([Цель5])",
            "formatString": "#,0",
            "lineageTag": "a10fb39d-6487-4d56-a48f-5edd5b13fb69"
          },
          {
            "name": "GA-goal — Переход на карточку товара",
            "expression": "SUM([Цель6])",
            "formatString": "#,0",
            "lineageTag": "1dee2cf7-1575-44e2-8452-ee8be9a606a4"
          },
          {
            "name": "Sum of Цель7",
            "expression": "SUM([Цель7])",
            "formatString": "#,0",
            "lineageTag": "5a4a08db-1351-4e14-8b83-d8262b58e17d"
          },
          {
            "name": "GA-goal — Оформил заказ все варианты",
            "expression": "SUM([Цель8])",
            "formatString": "#,0",
            "lineageTag": "f0a790ed-99a0-4f53-9bb3-6859d8efdbfb"
          },
          {
            "name": "Sum of Цель9",
            "expression": "SUM([Цель9])",
            "formatString": "#,0",
            "lineageTag": "fd65373d-ef59-40db-a568-f9016767bb79"
          },
          {
            "name": "Sum of Цель10",
            "expression": "SUM([Цель10])",
            "formatString": "#,0",
            "lineageTag": "d9ac22c6-7c30-4a1b-ba9d-222b2e59eca8"
          },
          {
            "name": "Sum of Цель11",
            "expression": "SUM([Цель11])",
            "formatString": "#,0",
            "lineageTag": "b0b0b633-0175-4f5d-9e60-7f735319390c"
          },
          {
            "name": "Sum of Цель12",
            "expression": "SUM([Цель12])",
            "formatString": "#,0",
            "lineageTag": "689c62e3-2568-433f-916c-dbce28a7cc19"
          },
          {
            "name": "Sum of Цель13",
            "expression": "SUM([Цель13])",
            "formatString": "#,0",
            "lineageTag": "7d2db07a-a791-4771-99ce-a86695b1b0e9"
          },
          {
            "name": "Sum of Цель14",
            "expression": "SUM([Цель14])",
            "formatString": "#,0",
            "lineageTag": "b49f44fe-006c-4042-958b-77deecb04e92"
          },
          {
            "name": "Sum of Цель15",
            "expression": "SUM([Цель15])",
            "formatString": "#,0",
            "lineageTag": "93e03bb6-0022-4d62-b6ec-b9cffb6b70b6"
          },
          {
            "name": "Sum of Цель16",
            "expression": "SUM([Цель16])",
            "formatString": "#,0",
            "lineageTag": "9a670afc-7bf4-4644-8d72-bcd34932ab24"
          },
          {
            "name": "Sum of Цель17",
            "expression": "SUM([Цель17])",
            "formatString": "#,0",
            "lineageTag": "a102805c-7a90-422a-9626-0a61265078b8"
          },
          {
            "name": "Sum of Цель18",
            "expression": "SUM([Цель18])",
            "formatString": "#,0",
            "lineageTag": "0c5f6d8e-1f40-4497-a443-b60ddd029ef1"
          },
          {
            "name": "Sum of Цель19",
            "expression": "SUM([Цель19])",
            "formatString": "#,0",
            "lineageTag": "e0080265-666d-49db-bfdb-cd0438c2e792"
          },
          {
            "name": "Sum of Цель20",
            "expression": "SUM([Цель20])",
            "formatString": "#,0",
            "lineageTag": "78f4e162-a4c5-4dee-861e-cdef20669b5c"
          },
          {
            "name": "cpm",
            "expression": "DIVIDE([Расход без НДС],[Показы]/1000)",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "6c117f5a-a00d-4da0-baaa-60cf3ab9b22f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "CPC",
            "expression": "DIVIDE([Расход без НДС],[Клики])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7c28e499-af29-4384-aa28-65db5771da0c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сессии цена",
            "expression": "DIVIDE([Расход без НДС],[Сессии GA])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7b3d5d8a-2167-40c1-9d98-be0a95b4046c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "CTR",
            "expression": "DIVIDE([Клики из кабинетов],[Показы])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "27cf40a3-a93f-4ba9-956c-2ce4d86b3b50"
          },
          {
            "name": "Adwords Ср.позиция",
            "expression": "DIVIDE(sum([AdWords Расчёт средней позиции клика]),sum([AdWords Клики для расчёта ср. позиции]))",
            "formatString": "#,0.0",
            "lineageTag": "3a5c8b7a-9fe1-4c5a-98f1-4c7278ee343a"
          },
          {
            "name": "YD Ср.позиция клика",
            "expression": "DIVIDE(sum([Директ Директ Расчет ср. позиции клика]),sum([Клики для расчёта ср. позиции]))",
            "formatString": "0.0",
            "lineageTag": "b5aa1c4a-5e89-4629-894f-00546f71639e"
          },
          {
            "name": "YD Ср.позиция показа",
            "expression": "DIVIDE(sum([Директ Расчет ср. позиции показа]),sum([Директ Показы для расчёта ср. позиции]))",
            "formatString": "0.0",
            "lineageTag": "f68ab429-0810-481a-a4bd-591ddbc1c21f"
          },
          {
            "name": "YD объем трафика",
            "expression": "DIVIDE(sum([Директ Расчет ср. объема трафика]),[Показы])",
            "formatString": "0.0",
            "lineageTag": "2f687ea4-797d-48fb-afa6-c822ee9982bc"
          },
          {
            "name": "Adwords Показатель качества, клики",
            "expression": "DIVIDE(sum([AdWords Расчёт показателя качества (по кликам)]),sum([AdWords Клики для расчёта показателя качества]))",
            "formatString": "#,0.0",
            "lineageTag": "c5d3b8d0-250f-4050-9d9e-91c36ec531ee"
          },
          {
            "name": "Adwords Показатель качества, показы",
            "expression": "DIVIDE(sum([AdWords Расчёт показателя качества (по показам)]),sum([AdWords Показы для расчёта показателя качества]))",
            "formatString": "#,0.0",
            "lineageTag": "8c5a948a-e51b-4a50-950f-51bf9d1c9366"
          },
          {
            "name": "Расход/Выручка",
            "expression": "DIVIDE([Расход без НДС],[Выручка когортная])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "25225ac1-f3b3-4651-be6a-887eaef469ff"
          },
          {
            "name": "Ср. Позиция клика",
            "expression": "DIVIDE(sum([AdWords Расчёт средней позиции клика])+sum([Директ Директ Расчет ср. позиции клика]),sum([AdWords Клики для расчёта ср. позиции])+sum([Клики для расчёта ср. позиции]))",
            "lineageTag": "aaa8cf8a-259e-4bef-a6fb-e301995ffab2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Клики → Трафик новый авто",
            "expression": "DIVIDE([Трафик новый авто],[Клики],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "205a57df-44fd-436d-ab28-e173d7b500a7"
          },
          {
            "name": "Сессии GA → Трафик новый авто",
            "expression": "DIVIDE([Трафик новый авто],[Сессии GA],BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "16f76515-af5a-4819-acf7-632e0ed691a2"
          },
          {
            "name": "Клики из кабинетов",
            "expression": "SUM(Pivot[Clicks])",
            "formatString": "0",
            "lineageTag": "8db0667f-2329-4c70-b96a-f3f4fd400591"
          },
          {
            "name": "Изменение расхода с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Расход без НДС | Прошедшая неделя] - [Расход ПП],",
              "        [Расход ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [Расход без НДС] - [Расход ПП], [Расход ПП], BLANK () )",
              ")"
            ],
            "lineageTag": "97b528a3-8813-4850-a657-f111569e25c8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение расхода с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение расхода с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение расхода с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение расхода с пп], \"#.##%\" )",
              ")"
            ],
            "lineageTag": "4ac570b6-474c-460e-a1e5-e3b2c2b70708"
          },
          {
            "name": "Расход ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    3,",
              "        CALCULATE (",
              "            [Расход без НДС],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    1,",
              "        CALCULATE (",
              "            [Расход без НДС],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    2, CALCULATE ( [Расход без НДС], FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 ) ),",
              "    BLANK ()",
              ")"
            ],
            "lineageTag": "76a79a18-dd8d-4665-8669-9f30505ac019",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Расход без НДС | Прошедшая неделя",
            "expression": [
              "CALCULATE ( [Расход без НДС], FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 ) )",
              ""
            ],
            "lineageTag": "c4949036-3f6c-45a8-84b3-a677afb1f43a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Клики ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Клики],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Клики],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Клики],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Клики",
            "lineageTag": "46d4b236-dcee-4201-8e49-a36fe4d51c88"
          },
          {
            "name": "Клики | Прошедшая неделя",
            "expression": "CALCULATE ([Клики] , FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 ) )",
            "displayFolder": "Клики",
            "lineageTag": "fa53e29b-6713-43c6-867d-a183c23bdff3"
          },
          {
            "name": "CPC ПП",
            "expression": [
              "DIVIDE([Расход ПП],[Клики ПП])",
              ""
            ],
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7247f9e9-fedf-4e60-8b95-1b017f265411"
          },
          {
            "name": "CPC | Прошедшая неделя",
            "expression": "DIVIDE ([Расход без НДС | Прошедшая неделя],[Клики | Прошедшая неделя])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "dd4b9faa-df0b-43ca-96b8-d0b79191a42b"
          },
          {
            "name": "Изменение CPC с прошедшего периода",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [CPC | Прошедшая неделя] - [CPC ПП],",
              "        [CPC ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [CPC] - [CPC ПП], [CPC ПП], BLANK () )",
              ")"
            ],
            "lineageTag": "77d2aac2-4dda-4710-9d8f-60ed72a1b4e9"
          },
          {
            "name": "Изменение CPC с прошедшего периода (текст)",
            "expression": [
              "IF (",
              "    [Изменение CPC с прошедшего периода] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение CPC с прошедшего периода], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение CPC с прошедшего периода], \"#.##%\" )",
              ")"
            ],
            "lineageTag": "13e607ad-1ef7-4c3d-bf29-537efbfb8dcf"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5da81b0e-07c8-4cfa-9815-a1cbb2445b1e"
          },
          {
            "name": "LinkedQueryName",
            "value": "Pivot"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":46,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Pivot/Changed Type.{Date,0}\",\"Section1/Pivot/Changed Type.{AtomId,1}\",\"Section1/Pivot/Changed Type.{Version,2}\",\"Section1/Pivot/Changed Type.{DeviceTypeId,3}\",\"Section1/Pivot/Changed Type.{Shows,4}\",\"Section1/Pivot/Changed Type.{Spent,5}\",\"Section1/Pivot/Changed Type.{Clicks,6}\",\"Section1/Pivot/Changed Type.{Sessions,7}\",\"Section1/Pivot/Changed Type.{Transactions,8}\",\"Section1/Pivot/Changed Type.{revenue,9}\",\"Section1/Pivot/Changed Type.{Цель1,10}\",\"Section1/Pivot/Changed Type.{Цель2,11}\",\"Section1/Pivot/Changed Type.{Цель3,12}\",\"Section1/Pivot/Changed Type.{Цель4,13}\",\"Section1/Pivot/Changed Type.{Цель5,14}\",\"Section1/Pivot/Changed Type.{Цель6,15}\",\"Section1/Pivot/Changed Type.{Цель7,16}\",\"Section1/Pivot/Changed Type.{Цель8,17}\",\"Section1/Pivot/Changed Type.{Цель9,18}\",\"Section1/Pivot/Changed Type.{Цель10,19}\",\"Section1/Pivot/Changed Type.{Цель11,20}\",\"Section1/Pivot/Changed Type.{Цель12,21}\",\"Section1/Pivot/Changed Type.{Цель13,22}\",\"Section1/Pivot/Changed Type.{Цель14,23}\",\"Section1/Pivot/Changed Type.{Цель15,24}\",\"Section1/Pivot/Changed Type.{Цель16,25}\",\"Section1/Pivot/Changed Type.{Цель17,26}\",\"Section1/Pivot/Changed Type.{Цель18,27}\",\"Section1/Pivot/Changed Type.{Цель19,28}\",\"Section1/Pivot/Changed Type.{Цель20,29}\",\"Section1/Pivot/Changed Type.{Директ Расчет ср. позиции показа,30}\",\"Section1/Pivot/Changed Type.{Директ Показы для расчёта ср. позиции,31}\",\"Section1/Pivot/Changed Type.{Директ Директ Расчет ср. позиции клика,32}\",\"Section1/Pivot/Changed Type.{Клики для расчёта ср. позиции,33}\",\"Section1/Pivot/Changed Type.{Директ Расчет ср. объема трафика,34}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт средней позиции клика,35}\",\"Section1/Pivot/Changed Type.{AdWords Клики для расчёта ср. позиции,36}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт показателя качества (по показам),37}\",\"Section1/Pivot/Changed Type.{AdWords Показы для расчёта показателя качества,38}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт показателя качества (по кликам),39}\",\"Section1/Pivot/Changed Type.{AdWords Клики для расчёта показателя качества,40}\",\"Section1/Pivot/Source.{AdWords Расчёт показателя AbsoluteTopImpressionPercentage (по показам),41}\",\"Section1/Pivot/Source.{AdWords Показы для расчёта показателя AbsoluteTopImpressionPercentage,42}\",\"Section1/Pivot/Source.{AdWords Расчёт показателя TopImpressionPercentage (по показам),43}\",\"Section1/Pivot/Source.{AdWords Показы для расчёта показателя TopImpressionPercentage,44}\",\"Section1/Pivot/Source.{Facebook Лиды,45}\"],\"ColumnCount\":46,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Pivot/Changed Type.{Date,0}\",\"Section1/Pivot/Changed Type.{AtomId,1}\",\"Section1/Pivot/Changed Type.{Version,2}\",\"Section1/Pivot/Changed Type.{DeviceTypeId,3}\",\"Section1/Pivot/Changed Type.{Shows,4}\",\"Section1/Pivot/Changed Type.{Spent,5}\",\"Section1/Pivot/Changed Type.{Clicks,6}\",\"Section1/Pivot/Changed Type.{Sessions,7}\",\"Section1/Pivot/Changed Type.{Transactions,8}\",\"Section1/Pivot/Changed Type.{revenue,9}\",\"Section1/Pivot/Changed Type.{Цель1,10}\",\"Section1/Pivot/Changed Type.{Цель2,11}\",\"Section1/Pivot/Changed Type.{Цель3,12}\",\"Section1/Pivot/Changed Type.{Цель4,13}\",\"Section1/Pivot/Changed Type.{Цель5,14}\",\"Section1/Pivot/Changed Type.{Цель6,15}\",\"Section1/Pivot/Changed Type.{Цель7,16}\",\"Section1/Pivot/Changed Type.{Цель8,17}\",\"Section1/Pivot/Changed Type.{Цель9,18}\",\"Section1/Pivot/Changed Type.{Цель10,19}\",\"Section1/Pivot/Changed Type.{Цель11,20}\",\"Section1/Pivot/Changed Type.{Цель12,21}\",\"Section1/Pivot/Changed Type.{Цель13,22}\",\"Section1/Pivot/Changed Type.{Цель14,23}\",\"Section1/Pivot/Changed Type.{Цель15,24}\",\"Section1/Pivot/Changed Type.{Цель16,25}\",\"Section1/Pivot/Changed Type.{Цель17,26}\",\"Section1/Pivot/Changed Type.{Цель18,27}\",\"Section1/Pivot/Changed Type.{Цель19,28}\",\"Section1/Pivot/Changed Type.{Цель20,29}\",\"Section1/Pivot/Changed Type.{Директ Расчет ср. позиции показа,30}\",\"Section1/Pivot/Changed Type.{Директ Показы для расчёта ср. позиции,31}\",\"Section1/Pivot/Changed Type.{Директ Директ Расчет ср. позиции клика,32}\",\"Section1/Pivot/Changed Type.{Клики для расчёта ср. позиции,33}\",\"Section1/Pivot/Changed Type.{Директ Расчет ср. объема трафика,34}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт средней позиции клика,35}\",\"Section1/Pivot/Changed Type.{AdWords Клики для расчёта ср. позиции,36}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт показателя качества (по показам),37}\",\"Section1/Pivot/Changed Type.{AdWords Показы для расчёта показателя качества,38}\",\"Section1/Pivot/Changed Type.{AdWords Расчёт показателя качества (по кликам),39}\",\"Section1/Pivot/Changed Type.{AdWords Клики для расчёта показателя качества,40}\",\"Section1/Pivot/Source.{AdWords Расчёт показателя AbsoluteTopImpressionPercentage (по показам),41}\",\"Section1/Pivot/Source.{AdWords Показы для расчёта показателя AbsoluteTopImpressionPercentage,42}\",\"Section1/Pivot/Source.{AdWords Расчёт показателя TopImpressionPercentage (по показам),43}\",\"Section1/Pivot/Source.{AdWords Показы для расчёта показателя TopImpressionPercentage,44}\",\"Section1/Pivot/Source.{Facebook Лиды,45}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Calendar",
        "lineageTag": "34648981-dc40-4dcd-9962-47cba5465786",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "985a249c-c61b-45f2-bbe0-a26e59340840",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "YEAR([Date])",
            "lineageTag": "77aa75d4-e851-4b6a-b3ec-36b06b55bcdb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month Number",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "30718dc0-1d92-488d-b0f5-89d6f4039295",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT([Date],\"MMM\")",
            "sortByColumn": "Month Number",
            "lineageTag": "8f9183f7-3689-403a-8a28-0765f9a3f4e7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "YYYY-MM",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if('Calendar'[Date]<DATE(2018,1,1),\"0 Раньше 2018 года\",FORMAT([Date],\"YYYY-MM\"))",
            "lineageTag": "339830b4-0ea0-4ec1-a18e-52dee0386159",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day Of Week Number",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "WEEKDAY([Date],2)",
            "lineageTag": "e46e8897-cdce-4647-856b-cac67fb98503",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day Of Week",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT([Date],\"DDD\")",
            "sortByColumn": "Day Of Week Number",
            "lineageTag": "0cdd55a6-0d73-4348-a350-08e1489a00ed",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week Number",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "WEEKNUM ( 'Calendar'[Date],2)",
            "lineageTag": "71508a69-6bb9-4d4d-b3ca-7f006204a5c0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "month diff",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IFERROR ( DATEDIFF ( [Date], TODAY (), MONTH ), -1 )",
            "lineageTag": "2f34c0f4-c580-402e-bcc9-e6cd368b2ac0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "weekdiff",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "IFERROR (",
              "    IF (",
              "        'Calendar'[Day Of Week Number] = 7,",
              "        DATEDIFF ( 'Calendar'[Date], TODAY (), WEEK ) + 1,",
              "        DATEDIFF ( 'Calendar'[Date], TODAY (), WEEK )",
              "    ),",
              "    -1",
              ")"
            ],
            "lineageTag": "e3991058-89ff-401c-8e85-2f098962a106",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Недели",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "if('Calendar'[Date]<DATE(2018,1,1),\"0 Раньше 2018 года\",FORMAT (",
              "    CALCULATE (",
              "        FIRSTNONBLANK ( 'Calendar'[Date], 1 ),",
              "        ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "    ),",
              "    \"YYYY-MM-DD\"",
              ")",
              "    & \"- \"",
              "    & FORMAT (",
              "        CALCULATE (",
              "            LASTNONBLANK ( 'Calendar'[Date], 1 ),",
              "            ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "        ),",
              "        \"YYYY-MM-DD\"",
              "  ))"
            ],
            "lineageTag": "d96d984d-189f-4737-befc-57ebf053d5f6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Недели_",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "if('Calendar'[Date]<DATE(2018,1,1),\"0 Раньше 2018 года\",FORMAT (",
              "    CALCULATE (",
              "        FIRSTNONBLANK ( 'Calendar'[Date], 1 ),",
              "        ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "    ),",
              "    \"DD.MM\"",
              ")",
              "    & \"- \"",
              "    & FORMAT (",
              "        CALCULATE (",
              "            LASTNONBLANK ( 'Calendar'[Date], 1 ),",
              "            ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "        ),",
              "        \"DD.MM\"",
              "  ))"
            ],
            "sortByColumn": "Недели",
            "lineageTag": "04075393-a064-4e36-bf22-6114052264e6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Недели_колон",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "if('Calendar'[Date]<DATE(2018,1,1),\"0 Раньше 2018 года\",FORMAT (",
              "    CALCULATE (",
              "        FIRSTNONBLANK ( 'Calendar'[Date], 1 ),",
              "        ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "    ),",
              "    \"DD.MM\"",
              ")",
              "    & \"-\" & UNICHAR(10) ",
              "    & FORMAT (",
              "        CALCULATE (",
              "            LASTNONBLANK ( 'Calendar'[Date], 1 ),",
              "            ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "        ),",
              "        \"DD.MM\"",
              "  ))"
            ],
            "lineageTag": "fcddefe0-135f-4904-9976-ae8e37ce31b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Квартал",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "QUARTER('Calendar'[Date])",
            "formatString": "0",
            "lineageTag": "d1bd8c72-36db-4a13-9313-08dab321238b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Week",
            "dataType": "string",
            "sourceColumn": "Week",
            "lineageTag": "c5946cfc-1f2d-4e68-9799-49121684ab5a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Неделя начинается с",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "CALCULATE (",
              "        FIRSTNONBLANK ( 'Calendar'[Date], 1 ),",
              "        ALLEXCEPT ( 'Calendar', 'Calendar'[weekdiff] )",
              "    )"
            ],
            "formatString": "Short Date",
            "lineageTag": "a6d7f6c9-f3e5-4526-a5a7-8747f9501b63",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Query1 = List.Generate(",
                "    ()=>#date(2019,7,1),",
                "    (x)=>x<=#date(2023,12,31),",
                "    (x)=>Date.AddDays(x,1)",
                "),",
                "    #\"Converted to Table\" = Table.FromList(Query1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}}),",
                "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Changed Type\", \"Week\", each Date.ToText(Date.StartOfWeek([Date]),\"yyyy-MM-dd\") &\" - \" & Date.ToText(Date.EndOfWeek([Date]),\"yyyy-MM-dd\")),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Добавлен пользовательский объект\",{{\"Week\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Today",
            "expression": "TODAY()",
            "formatString": "General Date",
            "lineageTag": "7c359a3f-effc-4c15-ab50-669ff5f394d4"
          },
          {
            "name": "Выбрано дней",
            "expression": "COUNT('Calendar'[Date])",
            "formatString": "0",
            "lineageTag": "1829f49c-6035-40b7-b330-f70e247e359c"
          },
          {
            "name": "Предыдущий период",
            "expression": [
              "",
              "VAR minDate =",
              "SWITCH([SelectedCamparePeriodType],",
              "1, [MidDate],",
              "2,CALCULATE(min('Calendar'[Date]),DATEADD('Calendar'[Date],-1 * [Выбрано дней],DAY)),BLANK())",
              "VAR maxDate = ",
              "SWITCH([SelectedCamparePeriodType],",
              "1,[MaxDate],",
              "2,CALCULATE(max('Calendar'[Date]),DATEADD('Calendar'[Date],-1 * [Выбрано дней],DAY)),BLANK())",
              "ReTURN FORMAT(minDate,\"dd.MM.YYYY\") &\"-\" & FORMAT(maxDate,\"dd.MM.YYYY\")"
            ],
            "lineageTag": "85496b6d-3443-424e-a85f-efaf4ac3154d"
          },
          {
            "name": "Текст для сравнения",
            "expression": [
              "VAR minDatePrev =",
              "    SWITCH (",
              "        [SelectedCamparePeriodType],",
              "        1, [MidDate],",
              "        3,",
              "            CALCULATE (",
              "                MIN ( 'Calendar'[Date] ),",
              "                DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "            ),",
              "        2,",
              "            CALCULATE (",
              "                MIN ( 'Calendar'[Date] ),",
              "                FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "            ),",
              "        BLANK ()",
              "    )",
              "VAR maxDatePrev =",
              "    SWITCH (",
              "        [SelectedCamparePeriodType],",
              "        1, [MaxDate],",
              "        3,",
              "            CALCULATE (",
              "                MAX ( 'Calendar'[Date] ),",
              "                DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "            ),",
              "        2,",
              "            CALCULATE (",
              "                MAX ( 'Calendar'[Date] ),",
              "                FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "            ),",
              "        BLANK ()",
              "    )",
              "VAR Prev =",
              "    \" с \" & FORMAT ( minDatePrev, \"dd.MM.YYYY\" ) & \" по \"",
              "        & FORMAT ( maxDatePrev, \"dd.MM.YYYY\" )",
              "VAR minDate =",
              "    SWITCH (",
              "        [SelectedCamparePeriodType],",
              "        2,",
              "            CALCULATE (",
              "                MIN ( 'Calendar'[Date] ),",
              "                FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              "            ),",
              "        MIN ( 'Calendar'[Date] )",
              "    )",
              "VAR maxDate =",
              "    SWITCH (",
              "        [SelectedCamparePeriodType],",
              "        2,",
              "            CALCULATE (",
              "                MAX ( 'Calendar'[Date] ),",
              "                FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              "            ),",
              "        MAX ( 'Calendar'[Date] )",
              "    )",
              "VAR curr =",
              "    \" с \" & FORMAT ( minDate, \"dd.MM.YYYY\" ) & \" по \"",
              "        & FORMAT ( maxDate, \"dd.MM.YYYY\" )",
              "RETURN",
              "    \"Сравниваем период\" & curr & \" с периодом\" & Prev"
            ],
            "lineageTag": "c58c7b9a-3020-471f-bf67-8433a008bebc"
          },
          {
            "name": "_MaxDate",
            "expression": "MAX('Calendar'[Date]) ",
            "formatString": "General Date",
            "lineageTag": "708eff48-8e9d-40c6-a033-c6f50d1c43d3"
          },
          {
            "name": "MinDate",
            "expression": "MIN('Calendar'[Date]) ",
            "formatString": "General Date",
            "lineageTag": "66b64c34-e574-4f34-bd60-701d63c16924"
          },
          {
            "name": "Текст выбранный период за 2 недели",
            "expression": "\"с \" & FORMAT([MinDate],\"dd.MM.YYYY\") & \" по \" & FORMAT([_MaxDate],\"dd.MM.YYYY\")",
            "lineageTag": "442a3727-7c59-4440-9576-8fb7afbeea5e"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "2a3856f2-67fc-4688-a278-67f5bb1c4823",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "592cec3c-5d82-4351-92d8-f13fab34ca4f"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month",
                "lineageTag": "88500e29-6b7a-4f11-9750-3530df708d82"
              },
              {
                "name": "DateColumn",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "4cf72752-3d9f-40f7-8152-e9acdf5aea3a"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "07073761-aeb8-4f7b-b9ee-446fb5c5d099"
          },
          {
            "name": "LinkedQueryName",
            "value": "Calendar (2)"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Calendar (2)/Changed Type.{Date,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Calendar (2)/Changed Type.{Date,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "ComagicCalls",
        "lineageTag": "58d4a210-fdcf-4a67-8fba-8c9ee71534ea",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "lineageTag": "9389d3b6-7998-4e33-9b83-373f34e4a20e",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "e4c05a2b-6a90-4959-900a-7ba1022a1a71",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "ComagicCalls",
            "dataType": "int64",
            "sourceColumn": "ComagicCalls",
            "lineageTag": "59bab7f0-1710-42c4-ba14-154f1c05f2fd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ComagicCallsIsLost",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsIsLost",
            "lineageTag": "a563e1d1-20da-4c29-b85b-21da7bfa3828",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ComagicCallsHasCid",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsHasCid",
            "lineageTag": "9dacbdfb-90e9-4f91-b985-e4644bd65d2a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ComagicCallsTag-Сервис",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsTag-Сервис",
            "lineageTag": "28427900-23de-45e7-99e2-a6b0cd0dcc6b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ComagicCallsTag-ОП",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsTag-ОП",
            "formatString": "0",
            "lineageTag": "074e2933-560a-4b20-8df5-3f414a817c67",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ComagicCallsTag-ОП-Автоматический",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsTag-ОП-Автоматический",
            "formatString": "0",
            "lineageTag": "4cf80dd7-672a-4b1d-8237-e6423e8f055f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateEvent",
            "dataType": "dateTime",
            "sourceColumn": "DateEvent",
            "formatString": "Long Date",
            "lineageTag": "a16f1401-dd10-43ba-8990-1a3f928d667c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "1a1b180c-5bd7-4113-a621-bfe8a4ad9c36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ComagicCallsTag-ОП-Только автоматический, без ручного",
            "dataType": "int64",
            "sourceColumn": "ComagicCallsTag-ОП-Только автоматический, без ручного",
            "formatString": "0",
            "lineageTag": "39e05ba4-c933-4e90-b865-9bd5307495a8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ComagicCalls",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[ComagicCallsNew]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"date\", type date}, {\"DateEvent\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Comagic звонки все",
            "expression": "SUM([ComagicCalls])",
            "formatString": "#,0",
            "lineageTag": "a44c1eb9-b443-4144-831b-72a6a8e49888"
          },
          {
            "name": "Comagic Потеряны",
            "expression": "SUM([ComagicCallsIsLost])",
            "formatString": "#,0",
            "lineageTag": "ed2f0eec-c2a2-465f-a958-c6158332af0e"
          },
          {
            "name": "Sum of ComagicCallsHasCid",
            "expression": "SUM([ComagicCallsHasCid])",
            "formatString": "#,0",
            "lineageTag": "173a2ab8-8e68-4977-9f5a-03864a3aa88a"
          },
          {
            "name": "Comagic Тэг «ОП»",
            "expression": [
              "IF(",
              "HASONEVALUE(TagOpTypes[Name]),",
              "    SWITCH(VALUES(TagOpTypes[Name]),",
              "        \"ОП\",[ОП, есть ручной тег],",
              "        \"ОП Только автоматические\",[ОП, только автоматически, без ручного]",
              "    ),",
              "    [ОП, есть ручной тег] + [ОП, только автоматически, без ручного]    ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d4363664-ef74-44d2-b772-f2d33004aa8a"
          },
          {
            "name": "Comagic Тэг «Сервис»",
            "expression": "SUM([ComagicCallsTag-Сервис])",
            "formatString": "#,0",
            "lineageTag": "e9d0a407-171a-4f97-ad89-dc48d53876fd"
          },
          {
            "name": "клик → Comagic",
            "expression": "DIVIDE([Comagic звонки все],[Клики])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7e2d6408-5da7-42f1-82f4-bd6753be8980"
          },
          {
            "name": "Comagic цена",
            "expression": "DIVIDE([Расход без НДС],[Comagic звонки все])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "23dfd2fe-16c3-4f7f-acda-f34110e6db48",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "% потерянных",
            "expression": "DIVIDE([Comagic Потеряны],[Comagic звонки все])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "51a1e2ec-2f72-4120-9245-a3cbb6cb1738"
          },
          {
            "name": "Comagic → Сервис",
            "expression": "DIVIDE([Comagic Тэг «Сервис»],[Comagic звонки все])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "46da6457-b489-43e8-91b2-fc74c9bba6b5"
          },
          {
            "name": "Comagic Тэг «Сервис», цена",
            "expression": "DIVIDE([Расход без НДС],[Comagic Тэг «Сервис»])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "1e174a2f-218e-4095-b120-ecf0b0cb8522",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "клик → Тег ОП",
            "expression": "DIVIDE([Comagic Тэг «ОП»],[Клики])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7cca1c20-8d15-4f1f-bc41-5aa01b1bb362"
          },
          {
            "name": "Тег ОП цена",
            "expression": "DIVIDE([Расход без НДС],[Comagic Тэг «ОП»])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "4b3893a8-9473-44d7-9dbd-0fd031cb4ed3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "План Тег ОП цена",
            "expression": "DIVIDE([Бюджет план без НДС],[План - тег продажа])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "6e7c1eac-c2ca-405c-8ebe-884726da4773",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "клик → тег Сервис",
            "expression": "DIVIDE([Comagic Тэг «Сервис»],[Клики])",
            "lineageTag": "704c403e-f8f2-4c85-927f-bb973555fa83",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ОП, есть ручной тег",
            "expression": "SUM(ComagicCalls[ComagicCallsTag-ОП])",
            "formatString": "#,0",
            "lineageTag": "9c92ed0b-a90c-45e6-ac6c-e644e61b712b"
          },
          {
            "name": "ОП, только автоматически, без ручного",
            "expression": "SUM(ComagicCalls[ComagicCallsTag-ОП-Только автоматический, без ручного])",
            "formatString": "#,0",
            "lineageTag": "2c4bc743-fb0a-4e7f-a9cc-16b432527947"
          },
          {
            "name": "ОП участвует",
            "expression": "CALCULATE([Comagic Тэг «ОП»],ComagicCalls[AttributionId]=3)",
            "formatString": "0",
            "displayFolder": "Аттрибуции",
            "lineageTag": "6665db07-ddfa-4d3e-a961-e57cceed9bc4"
          },
          {
            "name": "ОП первый",
            "expression": "CALCULATE([Comagic Тэг «ОП»],ComagicCalls[AttributionId]=2)",
            "formatString": "0",
            "displayFolder": "Аттрибуции",
            "lineageTag": "57604a16-01f0-439d-8461-12478f9608ea"
          },
          {
            "name": "ОП последний",
            "expression": "CALCULATE([Comagic Тэг «ОП»],ComagicCalls[AttributionId]=1)",
            "formatString": "0",
            "displayFolder": "Аттрибуции",
            "lineageTag": "d305c5d4-9fa6-4be0-87fe-e223c000fa00"
          },
          {
            "name": "Изменение звонков с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Comagic звонки все | Прошедшая неделя] - [Звонки ПП],",
              "        [Звонки ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [Comagic звонки все] - [Звонки ПП], [Звонки ПП], BLANK () )",
              ")"
            ],
            "lineageTag": "546e07ac-2c91-4686-8819-19e30ea3c8b7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение звонков с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение звонков с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение звонков с пп], \"0.0#%\" ),",
              "    IF (",
              "        OR ( ISBLANK ( [Изменение звонков с пп] ), [Изменение звонков с пп] = 0 ),",
              "        \"-\",",
              "        \"▼ \" & FORMAT ( [Изменение звонков с пп], \"0.0#%\" )",
              "    )",
              ")"
            ],
            "lineageTag": "0f815271-d450-44e0-b62d-7f0742910c46"
          },
          {
            "name": "Изменение ОП с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Comagic Тэг «ОП» | Прошедшая неделя] - [Звонки С ОП ПП],",
              "        [Звонки С ОП ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [Comagic Тэг «ОП»] - [Звонки С ОП ПП], [Звонки С ОП ПП], BLANK () )",
              ")"
            ],
            "lineageTag": "cb4e383a-7da5-497d-aedf-d5ea60e8bd57",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение ОП с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение ОП с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение ОП с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение ОП с пп], \"#.##%\" )",
              ")"
            ],
            "lineageTag": "08761a3d-338a-410a-969f-2101f4376bbb"
          },
          {
            "name": "Звонки ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Comagic звонки все],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Comagic звонки все],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Comagic звонки все],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4c6cefd4-0fdc-49ae-95f8-8149cffa49d7"
          },
          {
            "name": "Звонки С ОП ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Comagic Тэг «ОП»],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Comagic Тэг «ОП»],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Comagic Тэг «ОП»],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1b8b3e72-859f-45b7-8dca-467e9ef7a378"
          },
          {
            "name": "Comagic Тэг «ОП» | Прошедшая неделя",
            "expression": "CALCULATE ( [Comagic Тэг «ОП»], FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 ) )",
            "formatString": "0",
            "lineageTag": "bf93ddc6-53d5-44ed-9a88-f4f94a052dc2"
          },
          {
            "name": "Comagic звонки все | Прошедшая неделя",
            "expression": "CALCULATE ( [Comagic звонки все], FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 ) )",
            "formatString": "0",
            "lineageTag": "c99781ea-3594-4f85-9eb3-a5bf8eae14bc"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "06021d6f-c976-4453-a9bc-318cc7559f50"
          },
          {
            "name": "LinkedQueryName",
            "value": "ComagicCalls"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":6,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/ComagicCalls/Source.{AtomId,0}\",\"Section1/ComagicCalls/Changed Type.{date,1}\",\"Section1/ComagicCalls/Source.{ComagicCalls,2}\",\"Section1/ComagicCalls/Source.{ComagicCallsIsLost,3}\",\"Section1/ComagicCalls/Source.{ComagicCallsHasCid,4}\",\"Section1/ComagicCalls/Source.{ComagicCallsTag-Сервис,5}\"],\"ColumnCount\":6,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/ComagicCalls/Source.{AtomId,0}\",\"Section1/ComagicCalls/Changed Type.{date,1}\",\"Section1/ComagicCalls/Source.{ComagicCalls,2}\",\"Section1/ComagicCalls/Source.{ComagicCallsIsLost,3}\",\"Section1/ComagicCalls/Source.{ComagicCallsHasCid,4}\",\"Section1/ComagicCalls/Source.{ComagicCallsTag-Сервис,5}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "PlansFinal",
        "lineageTag": "20ff4378-81d5-4ef1-a3a6-e2fa9db83f85",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "0c44b00c-ce50-436f-aabe-ccc207f17310",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "977a042c-3928-4ec9-9700-ed136ea94c04",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Бюджет",
            "dataType": "double",
            "sourceColumn": "Бюджет",
            "lineageTag": "42336bd9-1e9d-4f0c-bd34-356a08f8af7d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "План показы",
            "dataType": "double",
            "sourceColumn": "План показы",
            "lineageTag": "6f6de666-b59a-498a-9f97-dea4aa635219",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "План клики",
            "dataType": "double",
            "sourceColumn": "План клики",
            "lineageTag": "00ac7797-b6a8-42f8-83bc-6229101a8cd2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "План звонки, тег продажа",
            "dataType": "double",
            "sourceColumn": "План звонки, тег продажа",
            "lineageTag": "dbad17c7-2455-4b0e-9661-904f158a5b73",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calls_Service",
            "dataType": "double",
            "sourceColumn": "Calls_Service",
            "formatString": "0",
            "lineageTag": "667c9277-d215-447d-87a3-534e5a012bf4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calls_TradeIn",
            "dataType": "double",
            "sourceColumn": "Calls_TradeIn",
            "formatString": "0",
            "lineageTag": "820bee7e-5d00-4e24-9c26-7493eecf8f1c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Traffic",
            "dataType": "double",
            "sourceColumn": "Traffic",
            "formatString": "0",
            "lineageTag": "c24cbaee-3bfd-4c4a-9fb9-60288d85d60a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "KartochkaProdavca",
            "dataType": "double",
            "sourceColumn": "KartochkaProdavca",
            "formatString": "0",
            "lineageTag": "219abfba-be9e-4ff4-8684-d9e5e58d4d3c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Meets",
            "dataType": "double",
            "sourceColumn": "Meets",
            "formatString": "0",
            "lineageTag": "13b73543-61cf-4d7a-9a40-385e70e58e56",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TestDrive",
            "dataType": "double",
            "sourceColumn": "TestDrive",
            "formatString": "0",
            "lineageTag": "3c1c1491-5433-49bf-850e-c9ae1ac96553",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Offers",
            "dataType": "double",
            "sourceColumn": "Offers",
            "formatString": "0",
            "lineageTag": "ea349982-a643-42ce-80b5-5d763e029e7b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Transactions",
            "dataType": "double",
            "sourceColumn": "Transactions",
            "formatString": "0",
            "lineageTag": "5246859f-bb88-4958-a74d-36842d9f90e3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Планы фильтр_",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "PlansFinal[Calls_Service] + PlansFinal[KartochkaProdavca]+PlansFinal[Meets]+PlansFinal[Offers]+PlansFinal[TestDrive]+PlansFinal[Traffic]+PlansFinal[Transactions]+PlansFinal[Бюджет]+PlansFinal[План звонки, тег продажа]+PlansFinal[План клики]+PlansFinal[План показы]",
            "lineageTag": "ce6461a1-772c-4dcb-8819-489ed26efeda",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "PlansFinal",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT   * FROM pivotparts.plans\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}, {\"План звонки, тег продажа\", type number}, {\"Calls_Service\", type number}, {\"Calls_TradeIn\", type number}, {\"Traffic\", type number}, {\"KartochkaProdavca\", type number}, {\"Meets\", type number}, {\"TestDrive\", type number}, {\"Offers\", type number}, {\"Transactions\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Бюджет план без НДС",
            "expression": "SUM([Бюджет])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "cb1b8af9-5bde-453c-bd94-a74619c1943f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Показы план",
            "expression": "SUM([План показы])",
            "formatString": "#,0",
            "lineageTag": "5388346b-d515-48de-a372-4f633a5737e1"
          },
          {
            "name": "Клики план",
            "expression": "SUM([План клики])",
            "formatString": "#,0",
            "lineageTag": "a006d58d-f0c1-4c18-9798-b16af1907114"
          },
          {
            "name": "План - тег продажа",
            "expression": "SUM([План звонки, тег продажа])",
            "formatString": "#,0",
            "lineageTag": "90cfeb44-819f-4396-afb2-0d4c22e276dc"
          },
          {
            "name": "% расхода бюджета",
            "expression": "DIVIDE([Расход без НДС],[Бюджет план без НДС])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e95acfb1-ea2d-45d5-9db7-023c49d14437"
          },
          {
            "name": "% показов от плана",
            "expression": "DIVIDE([Показы],[Показы план])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "71ff0d69-db7c-465b-a150-67b931670a26"
          },
          {
            "name": "% кликов от плана",
            "expression": "DIVIDE([Клики],[Клики план])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c9475ee9-6fae-4787-8c23-53f14a3449c8"
          },
          {
            "name": "% плана по Comagic звонки тег продажа (хотябы 1 из тегов)",
            "expression": "DIVIDE([Comagic есть Тэг про продажу],[План - тег продажа])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f3191dfa-9cd2-4b80-b123-c638d44650d0"
          },
          {
            "name": "% плана по Comagic звонки тег продажа",
            "expression": "DIVIDE([Comagic Тэг «Продажа»],[План - тег продажа])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "8f19d65c-e370-46d4-a0d7-147d930ec645"
          },
          {
            "name": "% плана в тег ОП",
            "expression": "DIVIDE([Comagic Тэг «ОП»],[План - тег продажа])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "8cfa9c5a-9c0f-453a-8147-ce0048844956"
          },
          {
            "name": "Sum of Бюджет",
            "expression": "SUM('PlansFinal'[Бюджет])",
            "lineageTag": "9164b4c3-ac0a-423b-a245-a2167943a04c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% плана ОП, цена",
            "expression": "DIVIDE([Тег ОП цена],[План Тег ОП цена])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ba72d196-bbab-4334-a624-5a31b9004acd"
          },
          {
            "name": "PlanCallsService",
            "expression": "sum(PlansFinal[Calls_Service])",
            "formatString": "#,0",
            "lineageTag": "c11e83fe-d9ab-4460-bc88-2bcbd45f0c60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "План звонки Сервис, цена",
            "expression": "DIVIDE([Бюджет план без НДС],[PlanCallsService])",
            "lineageTag": "a8f83e8b-ceac-4043-83a7-908740c258d5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0058d9a3-ce8e-40c7-97aa-25098d75d2ae"
          },
          {
            "name": "LinkedQueryName",
            "value": "PlansFinal"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":14,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/PlansFinal/Changed Type.{Date,0}\",\"Section1/PlansFinal/Source.{AtomId,1}\",\"Section1/PlansFinal/Source.{Бюджет,2}\",\"Section1/PlansFinal/Source.{План показы,3}\",\"Section1/PlansFinal/Source.{План клики,4}\",\"Section1/PlansFinal/Changed Type.{План звонки, тег продажа,5}\",\"Section1/PlansFinal/Changed Type.{Calls_Service,6}\",\"Section1/PlansFinal/Changed Type.{Calls_TradeIn,7}\",\"Section1/PlansFinal/Changed Type.{Traffic,8}\",\"Section1/PlansFinal/Changed Type.{KartochkaProdavca,9}\",\"Section1/PlansFinal/Changed Type.{Meets,10}\",\"Section1/PlansFinal/Changed Type.{TestDrive,11}\",\"Section1/PlansFinal/Changed Type.{Offers,12}\",\"Section1/PlansFinal/Changed Type.{Transactions,13}\"],\"ColumnCount\":14,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/PlansFinal/Changed Type.{Date,0}\",\"Section1/PlansFinal/Source.{AtomId,1}\",\"Section1/PlansFinal/Source.{Бюджет,2}\",\"Section1/PlansFinal/Source.{План показы,3}\",\"Section1/PlansFinal/Source.{План клики,4}\",\"Section1/PlansFinal/Changed Type.{План звонки, тег продажа,5}\",\"Section1/PlansFinal/Changed Type.{Calls_Service,6}\",\"Section1/PlansFinal/Changed Type.{Calls_TradeIn,7}\",\"Section1/PlansFinal/Changed Type.{Traffic,8}\",\"Section1/PlansFinal/Changed Type.{KartochkaProdavca,9}\",\"Section1/PlansFinal/Changed Type.{Meets,10}\",\"Section1/PlansFinal/Changed Type.{TestDrive,11}\",\"Section1/PlansFinal/Changed Type.{Offers,12}\",\"Section1/PlansFinal/Changed Type.{Transactions,13}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "crmTraffic",
        "lineageTag": "4347ca61-ff99-4673-877e-d46a1ec27897",
        "columns": [
          {
            "name": "AtomIdFinal",
            "dataType": "int64",
            "sourceColumn": "AtomIdFinal",
            "lineageTag": "3b7eb46c-afb0-4b7e-884d-0019a6bf70af",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DateTraffic",
            "dataType": "dateTime",
            "sourceColumn": "DateTraffic",
            "formatString": "General Date",
            "lineageTag": "3787e488-98ed-4dbf-a777-d3a695d112fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateComagic",
            "dataType": "dateTime",
            "sourceColumn": "DateComagic",
            "formatString": "General Date",
            "lineageTag": "d63ea4ad-33c1-427b-b025-e88bbfee6050",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "5a95afe5-c421-4d32-8dce-57227d942604",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "22518161-0af1-46f2-92d9-80ee4fe12c9a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClientTrafficType",
            "dataType": "string",
            "sourceColumn": "ClientTrafficType",
            "lineageTag": "da89fe0c-5075-4c4a-bd2b-6af00cf702ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliSource",
            "dataType": "string",
            "sourceColumn": "PotCliSource",
            "lineageTag": "cc2bcdb4-c0ff-4e16-9304-52fb1366cc50",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Трафик",
            "dataType": "int64",
            "sourceColumn": "Трафик",
            "lineageTag": "2f55144e-00a4-4503-9b5d-7ac4101a92bf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "final date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK(crmTraffic[DateComagic]),crmTraffic[DateTraffic],crmTraffic[DateComagic])",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "4ad5363b-6604-455b-9863-b3717940c56b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "HasComagicCall",
            "dataType": "string",
            "sourceColumn": "HasComagicCall",
            "lineageTag": "33e07290-8982-412b-bf32-110febb1ff94",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "WEEKDiff",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IFERROR(DATEDIFF([DateComagic],[DateTraffic],WEEK),-1)",
            "formatString": "0",
            "lineageTag": "a22584fe-188e-49d2-b483-1268ab548f36",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Недели_ Трафик когорты",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(FIRSTNONBLANK('Calendar'[Недели_колон],1),FILTER('Calendar','Calendar'[Date]=crmTraffic[DateTraffic]))",
            "sortByColumn": "week_traffic",
            "lineageTag": "18e08e3b-7ec5-418e-b56c-3281d8435881",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "week_traffic",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(FIRSTNONBLANK('Calendar'[Недели],1),FILTER('Calendar','Calendar'[Date]=crmTraffic[DateTraffic]))",
            "lineageTag": "152db6a7-d685-4bb3-8abb-1a698a5b3e03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "37b803a1-809b-4337-bf7d-85675fc13541",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wkDiff",
            "dataType": "int64",
            "sourceColumn": "wkDiff",
            "formatString": "0",
            "lineageTag": "ff57ed48-6963-43f4-b995-999cdc55db83",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "PhraseKey",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "blank() --crmTraffic[adCampaignId] & \"#\" & crmTraffic[PhraseId]",
            "formatString": "0",
            "lineageTag": "6b10614d-7784-4e56-bb5d-8049222db3c2",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmTraffic",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[crmClientTraffic_attNew]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"AtomIdFinal\", \"AtomIdFinal\"}, {\"DateTraffic\", \"DateTraffic\"}, {\"DateComagic\", \"DateComagic\"}, {\"Site\", \"Site\"}, {\"Make\", \"Make\"}, {\"ClientTrafficType\", \"ClientTrafficType\"}, {\"PotCliSource\", \"PotCliSource\"}, {\"Трафик\", \"Трафик\"}, {\"HasComagicCall\", \"HasComagicCall\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"AtomIdFinal\", Int64.Type}, {\"DateTraffic\", type datetime}, {\"DateComagic\", type datetime}, {\"Site\", type text}, {\"Make\", type text}, {\"ClientTrafficType\", type text}, {\"PotCliSource\", type text}, {\"Трафик\", Int64.Type}, {\"HasComagicCall\", type text}}),",
                "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Changed Type\", \"wkDiff\", each Duration.Days((Date.StartOfWeek([DateTraffic],Day.Monday) - Date.StartOfWeek([DateComagic],Day.Monday))) / 7, Int64.Type)",
                "in",
                "    #\"Добавлен пользовательский объект\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Трафик, шт",
            "expression": "SUM([Трафик])",
            "formatString": "#,0",
            "lineageTag": "2956052d-74ae-449b-aeb5-6d8bec8c79f5"
          },
          {
            "name": "Трафик, цена",
            "expression": "DIVIDE([Расход без НДС],[Трафик, шт])",
            "lineageTag": "b2d8fd1c-f2cb-4465-9c7a-997f3df72440",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Трафик новый авто",
            "expression": "CALCULATE([Трафик, шт],crmTraffic[ClientTrafficType]=\"Новый автомобиль\")",
            "formatString": "#,0",
            "lineageTag": "bc0ef46c-fdbc-4a73-be63-1ef4f96c6088"
          },
          {
            "name": "Трафик новый авто, цена",
            "expression": "DIVIDE([Расход без НДС],[Трафик новый авто])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "9fbe06c9-1c4b-4105-bbee-949a99f48038",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ОП → Трафик новый авто",
            "expression": "DIVIDE([Трафик новый авто],[Comagic Тэг «ОП»])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "9071f222-f265-4a4a-973f-51376ae054c6"
          },
          {
            "name": "Трафик новый авто по дате создания трафик",
            "expression": "CALCULATE([Трафик новый авто],USERELATIONSHIP(crmTraffic[DateTraffic],'Calendar'[Date]))",
            "formatString": "#,0",
            "lineageTag": "b6c5b743-2f22-47bc-be16-e7463ad63fc8"
          },
          {
            "name": "Трафик новый | первый",
            "expression": "CALCULATE([Трафик новый авто],crmTraffic[AttributionId]=2)",
            "formatString": "0",
            "lineageTag": "63322122-b88f-47a2-9a02-4485db71936c"
          },
          {
            "name": "Трафик новый | последний",
            "expression": "CALCULATE([Трафик новый авто],crmTraffic[AttributionId]=1)",
            "formatString": "0",
            "lineageTag": "5b8c7f38-d2af-44a1-aee5-f104d47aebb5"
          },
          {
            "name": "Трафик новый | участвует",
            "expression": "CALCULATE([Трафик новый авто],crmTraffic[AttributionId]=3)",
            "formatString": "0",
            "lineageTag": "2192cb22-80b3-46a8-a112-0458de2fbaa6"
          },
          {
            "name": "Трафик новый авто, без замены AtomId",
            "expression": [
              "",
              "CALCULATE(SUM(crmTrafficAtomIdBeforeReplace[Трафик]),crmTrafficAtomIdBeforeReplace[ClientTrafficType]=\"Новый автомобиль\")"
            ],
            "formatString": "#,0",
            "displayFolder": "Трафик без замены AtomId",
            "lineageTag": "5c56d3dd-db04-438c-90d9-e89a52240184"
          },
          {
            "name": "Изменение трафика (новый авто) с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Трафик новый авто, без замены AtomId | Прошедшая неделя] - [Трафик (новый авто) ПП],",
              "        [Трафик (новый авто) ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE (",
              "        [Трафик новый авто, без замены AtomId] - [Трафик (новый авто) ПП],",
              "        [Трафик (новый авто) ПП],",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "lineageTag": "1c565c22-392e-4def-9972-9e2da08729b4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение трафика (новый авто) с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение трафика (новый авто) с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение трафика (новый авто) с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение трафика (новый авто) с пп], \"#.##%\" )",
              ")"
            ],
            "lineageTag": "fe723a26-0ace-420b-8927-94fe9b1f99cb"
          },
          {
            "name": "Трафик (новый авто) ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7c2948af-d2b1-4477-aae5-15a70ee182a7"
          },
          {
            "name": "Трафик новый авто, без замены AtomId, цена",
            "expression": "DIVIDE([Расход без НДС],[Трафик новый авто, без замены AtomId])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "displayFolder": "Трафик без замены AtomId, цена",
            "lineageTag": "19d67e57-6bd3-4551-b7df-316011716559",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Трафик новый авто, без замены AtomId | Прошедшая неделя",
            "expression": [
              "CALCULATE (",
              "    [Трафик новый авто, без замены AtomId],",
              "    FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              ")"
            ],
            "displayFolder": "Трафик без замены AtomId",
            "lineageTag": "5b0f2bb8-2bdb-4038-9155-55a29b52f319"
          },
          {
            "name": "Клики → Трафик новый авто, без замены AtomId",
            "expression": "DIVIDE ( [Трафик новый авто, без замены AtomId], [Клики] )",
            "formatString": "0.0#%;-0.0#%;0.0#%",
            "displayFolder": "Клики → Трафик новый авто, без замены AtomId",
            "lineageTag": "febfaadf-4d15-44b4-948a-0d79a8d1a522"
          },
          {
            "name": "Клики → Трафик новый авто, без замены AtomId ПП",
            "expression": "DIVIDE ([Трафик (новый авто) ПП],[Клики ПП])",
            "formatString": "0.0#%;-0.0#%;0.0#%",
            "displayFolder": "Клики → Трафик новый авто, без замены AtomId",
            "lineageTag": "34d0b482-1acd-4738-9d5c-d0a5fefe5bab"
          },
          {
            "name": "Изменение клики → трафик на с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    [Клики → Трафик новый авто, без замены AtomId | Прошедшая неделя] - [Клики → Трафик новый авто, без замены AtomId ПП],",
              "    [Клики → Трафик новый авто, без замены AtomId] - [Клики → Трафик новый авто, без замены AtomId ПП]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Клики → Трафик новый авто, без замены AtomId",
            "lineageTag": "b0f79113-bfd8-4e1c-8a6a-1e1614126d8a"
          },
          {
            "name": "Изменение клики → трафик на с пп (текст)",
            "expression": [
              "IF (",
              "     [Изменение клики → трафик на с пп]> 0,",
              "    \"▲ \" & FORMAT ( [Изменение клики → трафик на с пп], \"0.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение клики → трафик на с пп], \"0.##%\" )",
              ")"
            ],
            "displayFolder": "Клики → Трафик новый авто, без замены AtomId",
            "lineageTag": "c5d728ac-52dc-4c1f-87c6-0a6ca6279426"
          },
          {
            "name": "Трафик новый авто, без замены AtomId, цена ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId, цена],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId, цена],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId, цена],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "displayFolder": "Трафик без замены AtomId, цена",
            "lineageTag": "5961ea96-d3ef-401b-a5bc-d0a84af713d1"
          },
          {
            "name": "Трафик новый авто, без замены AtomId, цена | Прошедшая неделя",
            "expression": "DIVIDE ([Расход без НДС | Прошедшая неделя],[Трафик новый авто, без замены AtomId | Прошедшая неделя])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "displayFolder": "Трафик без замены AtomId, цена",
            "lineageTag": "c5aa5988-f80f-4b28-b3cc-cab511fcb884"
          },
          {
            "name": "Клики → Трафик новый авто, без замены AtomId | Прошедшая неделя",
            "expression": "DIVIDE ([Трафик новый авто, без замены AtomId | Прошедшая неделя],[Клики | Прошедшая неделя])",
            "formatString": "0.0#%;-0.0#%;0.0#%",
            "displayFolder": "Клики → Трафик новый авто, без замены AtomId",
            "lineageTag": "bbdb6343-98aa-4b39-a570-132ad6ba9fb3"
          },
          {
            "name": "Изменение трафика (новый авто), цена с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Трафик новый авто, без замены AtomId, цена | Прошедшая неделя] - [Трафик новый авто, без замены AtomId, цена ПП],",
              "        [Трафик новый авто, без замены AtomId, цена ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE (",
              "        [Трафик новый авто, без замены AtomId, цена] - [Трафик новый авто, без замены AtomId, цена ПП],",
              "        [Трафик новый авто, без замены AtomId, цена ПП],",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "lineageTag": "4672d4cb-893d-4d53-8800-a9cd25acef87",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение трафика (новый авто), цена с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение трафика (новый авто), цена с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение трафика (новый авто), цена с пп], \"0.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение трафика (новый авто), цена с пп], \"0.##%\" )",
              ")"
            ],
            "lineageTag": "5d049d56-45df-43a9-8bf1-72eb1d7ae8a7"
          },
          {
            "name": "Трафик → РКП, без замены AtomId",
            "expression": "DIVIDE([РКП, без замены AtomId],[Трафик новый авто, без замены AtomId],BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "975be31b-3ee6-4fca-87ba-7546b7a48d03"
          },
          {
            "name": "Количество атомов",
            "expression": "COUNTX(FILTER(SUMMARIZE(AtomsWithExtensions,AtomsWithExtensions[AtomId],\"Трафик → РКП, без замены AtomId\",[Трафик → РКП, без замены AtomId]), [Трафик → РКП, без замены AtomId] > 1), [AtomId])",
            "formatString": "0",
            "lineageTag": "49e72694-dc1b-4a72-bb06-232f9a590906"
          },
          {
            "name": "Трафик (новый авто, с заменой AtomId) ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Трафик новый авто, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ee037e6c-9282-41ef-a61a-7079919d22af"
          },
          {
            "name": "Трафик новый авто, 1",
            "expression": "CALCULATE([Трафик новый авто],FILTER('Calendar', 'Calendar'[Week] = [W1] || 'Calendar'[Week] = [W2]))",
            "formatString": "0",
            "lineageTag": "44a19b9d-ab67-4dee-a5d2-97bc645cdda5"
          },
          {
            "name": "Трафик новый авто (calendar 3)",
            "expression": "CALCULATE([Трафик новый авто], TREATAS(values('Calendar (3)'[Date]),'Calendar'[Date]))",
            "formatString": "0",
            "lineageTag": "0ad398fe-6edd-424e-ad16-56e2faafacca"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9fdfb885-0182-46e4-a58f-60318aaa6992"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmTraffic"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":9,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmTraffic/Changed Type.{AtomIdFinal,0}\",\"Section1/crmTraffic/Changed Type.{DateTraffic,1}\",\"Section1/crmTraffic/Changed Type.{DateComagic,2}\",\"Section1/crmTraffic/Changed Type.{HasComagicCall,3}\",\"Section1/crmTraffic/Changed Type.{Site,4}\",\"Section1/crmTraffic/Changed Type.{Make,5}\",\"Section1/crmTraffic/Changed Type.{ClientTrafficType,6}\",\"Section1/crmTraffic/Changed Type.{PotCliSource,7}\",\"Section1/crmTraffic/Changed Type.{Трафик,8}\"],\"ColumnCount\":9,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmTraffic/Changed Type.{AtomIdFinal,0}\",\"Section1/crmTraffic/Changed Type.{DateTraffic,1}\",\"Section1/crmTraffic/Changed Type.{DateComagic,2}\",\"Section1/crmTraffic/Changed Type.{HasComagicCall,3}\",\"Section1/crmTraffic/Changed Type.{Site,4}\",\"Section1/crmTraffic/Changed Type.{Make,5}\",\"Section1/crmTraffic/Changed Type.{ClientTrafficType,6}\",\"Section1/crmTraffic/Changed Type.{PotCliSource,7}\",\"Section1/crmTraffic/Changed Type.{Трафик,8}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmClientPotCli",
        "lineageTag": "ad40dc77-abff-490f-935a-4f4675b2118b",
        "columns": [
          {
            "name": "WhenCreated",
            "dataType": "dateTime",
            "sourceColumn": "WhenCreated",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "227f0fe4-05ca-4860-b56b-181a70788874",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "PotCliDepth",
            "dataType": "string",
            "sourceColumn": "PotCliDepth",
            "lineageTag": "146213d7-f282-458b-8da1-f06236d431a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "ea11492b-8091-4616-9bc1-d0dc04724908",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Площадка МТ РКП",
            "dataType": "string",
            "sourceColumn": "Площадка МТ РКП",
            "lineageTag": "f6900032-3362-4302-b9fa-a966f3ce2697",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "lineageTag": "6d8862ec-58ed-4302-88a2-bc055282187c",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "2ce2dc25-bd46-4ffd-8c78-49f9e9db4d2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "PotCliCounts",
            "dataType": "int64",
            "sourceColumn": "PotCliCounts",
            "lineageTag": "3742dc68-ff22-46fa-8752-92f16135239b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "РКП статус",
            "dataType": "string",
            "sourceColumn": "РКП статус",
            "lineageTag": "da79abca-19cd-41fc-b130-ee6252b26369",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча назначена",
            "dataType": "int64",
            "sourceColumn": "3 Встреча назначена",
            "formatString": "0",
            "lineageTag": "cf4abd06-795b-47f1-9827-5dd6228f8386",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча",
            "dataType": "int64",
            "sourceColumn": "3 Встреча",
            "formatString": "0",
            "lineageTag": "455026c1-aae9-4f71-86ba-8ec796b86967",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв назначен",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв назначен",
            "formatString": "0",
            "lineageTag": "1516eaf6-7e89-4688-9c41-38610b700626",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв",
            "formatString": "0",
            "lineageTag": "e48ed21b-84af-4e54-82d5-22531c4b1f35",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "5 Предложение",
            "dataType": "int64",
            "sourceColumn": "5 Предложение",
            "formatString": "0",
            "lineageTag": "42d2afcd-b096-467d-915e-c7357ecbaeb2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "6 Сделка",
            "dataType": "int64",
            "sourceColumn": "6 Сделка",
            "formatString": "0",
            "lineageTag": "3f2fc039-89ac-480a-9edd-fc0e4e0b92a6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "7 Выдача",
            "dataType": "int64",
            "sourceColumn": "7 Выдача",
            "formatString": "0",
            "lineageTag": "6ba7263d-8e8d-4f46-af6d-a6777ebf55f3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Расторжение",
            "dataType": "int64",
            "sourceColumn": "Расторжение",
            "formatString": "0",
            "lineageTag": "1e28bcea-2197-4015-9197-efab8b9d4a29",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП — Есть хотя-бы одно из событий",
            "dataType": "int64",
            "sourceColumn": "РКП — Есть хотя-бы одно из событий",
            "formatString": "0",
            "lineageTag": "c38978b8-f2ca-43d1-bbe9-9b65dbae0eb5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "comagic_starttime",
            "dataType": "dateTime",
            "sourceColumn": "comagic_starttime",
            "formatString": "General Date",
            "lineageTag": "b3ca1a44-1388-47f1-8313-bdcd235a4214",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "traffic_created",
            "dataType": "dateTime",
            "sourceColumn": "traffic_created",
            "formatString": "General Date",
            "lineageTag": "4558dc41-9035-4e14-a0bd-cc05c732f43a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "trafic_finded",
            "dataType": "string",
            "sourceColumn": "trafic_finded",
            "lineageTag": "9651aa33-e4aa-4fbe-ad8c-b8184f221dab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "comagic_finded",
            "dataType": "string",
            "sourceColumn": "comagic_finded",
            "lineageTag": "888cde30-1356-4737-a2ac-b3f3edfd918e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "4691e9d0-9306-40a6-9a43-b8b14c698cc1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "PhraseKey",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "blank() --crmClientPotCli[AdCampaignId] & \"#\" & crmClientPotCli[PhraseId]",
            "formatString": "0",
            "lineageTag": "c4627803-4eb9-4a2f-bca2-f15ead685b8f",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmClientPotCli",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT    *   FROM [pivotparts].[crmClientPotCli]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"WhenCreated\", \"WhenCreated\"}, {\"PotCliDepth\", \"PotCliDepth\"}, {\"Make\", \"Make\"}, {\"Site\", \"Site\"}, {\"AtomId\", \"AtomId\"}, {\"date\", \"date\"}, {\"PotCliCounts\", \"PotCliCounts\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"WhenCreated\", type datetime}, {\"PotCliDepth\", type text}, {\"Make\", type text}, {\"Site\", type text}, {\"AtomId\", Int64.Type}, {\"date\", type datetime}, {\"PotCliCounts\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Site\", \"Площадка МТ РКП\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "РКП",
            "expression": "SUM([PotCliCounts])",
            "formatString": "#,0",
            "displayFolder": "Main Mesuares",
            "lineageTag": "f559faed-b127-4f88-bb25-95581409547d"
          },
          {
            "name": "Карточка продавца, Сделка",
            "expression": "CALCULATE([РКП],crmClientPotCli[PotCliDepth]=\"Сделка\")",
            "lineageTag": "d8584fff-391b-4a7d-b016-4cf0ea11357b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Карточка продавца, Выдача",
            "expression": "CALCULATE([РКП],crmClientPotCli[PotCliDepth]=\"Выдача\")",
            "lineageTag": "90be3ca1-62a0-4cbc-871e-bb25203561e8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Трафик → РКП",
            "expression": "DIVIDE([РКП],[Трафик новый авто])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2864e7a4-cc10-4a50-a6eb-1daa458bf704"
          },
          {
            "name": "РКП, цена",
            "expression": "DIVIDE([Расход без НДС],[РКП])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "a94bf8bc-3cf8-4006-a534-b37aa6dc4561",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "РКП, по дате создания",
            "expression": "CALCULATE([РКП],USERELATIONSHIP(crmClientPotCli[WhenCreated],'Calendar'[Date]))",
            "formatString": "#,0",
            "lineageTag": "dcdfd955-5063-40d2-ae87-4677a12f9e09"
          },
          {
            "name": "Клик → РКП, %",
            "expression": "DIVIDE([РКП],[Клики])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "41cffd70-573f-4952-a3ee-ce6924ba639a"
          },
          {
            "name": "РКП Эффективная",
            "description": "РКП, в рамках которых была назначена или совершена встреча или тест драйв, или предложение, или сделка, или расторжение",
            "expression": "sum([РКП — Есть хотя-бы одно из событий])",
            "formatString": "#,0",
            "displayFolder": "Main Mesuares",
            "lineageTag": "a0cae232-bc9d-474c-a634-5bed67b0441b"
          },
          {
            "name": "РКП → РКП эффективная, %",
            "expression": "DIVIDE([РКП Эффективная],[РКП])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d4439f5b-918e-44c0-a977-7280b8df490b"
          },
          {
            "name": "РКП Эффективная, цена",
            "expression": "DIVIDE([Расход без НДС],[РКП Эффективная])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7516bcf6-8cd5-42f2-9151-8ec58299994c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "РКП; со сравнением с предыдущим месяцем",
            "expression": [
              "",
              "FORMAT([РКП],\"#,##\") & \" | \" & FORMAT([РКП, предыдущий месяц],\"0.0%\")"
            ],
            "lineageTag": "088395a2-2d49-4a7e-99c2-588818fc19bd"
          },
          {
            "name": "РКП, предыдущий месяц",
            "expression": "DIVIDE([РКП] - CALCULATE([РКП],PREVIOUSMONTH('Calendar'[Date])),[РКП],BLANK()) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f5910e6-9cad-4c11-b5c9-5b21a94de8d4"
          },
          {
            "name": "РКП, без замены AtomId",
            "expression": "SUM(crmClientPotCliAtomIdBeforeReplace[PotCliCounts])",
            "formatString": "#,0",
            "displayFolder": "РКП, без замены AtomId",
            "lineageTag": "4d2e1b8a-055a-4ebd-9add-a1b807d325ff"
          },
          {
            "name": "РКП Эффективная, без замены AtomId",
            "expression": "sum(crmClientPotCliAtomIdBeforeReplace[РКП — Есть хотя-бы одно из событий])",
            "formatString": "#,0",
            "displayFolder": "РКП Эффективная, без замены Atomid",
            "lineageTag": "7c51189c-42fa-4bab-9ac7-e73e90ecd0ce"
          },
          {
            "name": "Изменение РКП с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [РКП, без замены AtomId | Прошедшая неделя] - [РКП ПП],",
              "        [РКП ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [РКП, без замены AtomId] - [РКП ПП], [РКП ПП], BLANK () )",
              ")"
            ],
            "displayFolder": "РКП, без замены AtomId",
            "lineageTag": "0e179dad-18d6-4556-9f36-dad41a88cf1a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение РКП с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение РКП с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение РКП с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение РКП с пп], \"#.##%\" )",
              ")"
            ],
            "displayFolder": "РКП, без замены AtomId",
            "lineageTag": "fde48930-bf5c-4027-b400-e3f76cf8c37d"
          },
          {
            "name": "Изменение РКП Эффективная с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [РКП Эффективная, без замены AtomId] - [РКП Эффективная ПП],",
              "        [РКП Эффективная ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE (",
              "        [РКП Эффективная, без замены AtomId] - [РКП Эффективная ПП],",
              "        [РКП Эффективная ПП],",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "displayFolder": "РКП Эффективная, без замены Atomid",
            "lineageTag": "954048f6-da15-4060-8d9b-e24736209bf9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение РКП Эффективная с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение РКП Эффективная с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение РКП Эффективная с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение РКП Эффективная с пп], \"#.##%\" )",
              ")"
            ],
            "displayFolder": "РКП Эффективная, без замены Atomid",
            "lineageTag": "3021307a-3b3c-4bc0-bdd3-9f13a861913b"
          },
          {
            "name": "РКП ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [РКП, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [РКП, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [РКП, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "РКП, без замены AtomId",
            "lineageTag": "774fe8f1-c8a6-4dc3-af6e-7f0ddcb7dbbf"
          },
          {
            "name": "РКП Эффективная ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [РКП Эффективная, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [РКП Эффективная, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [РКП Эффективная, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "РКП Эффективная, без замены Atomid",
            "lineageTag": "378855b8-ee05-4938-82a7-ff92dff7041b"
          },
          {
            "name": "РКП Эффективная, без замены AtomId | Прошедшая неделя",
            "expression": [
              "CALCULATE (",
              "    [РКП Эффективная, без замены AtomId],",
              "    FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              ")"
            ],
            "displayFolder": "РКП Эффективная, без замены Atomid",
            "lineageTag": "60e77ff6-f2ce-4bf0-90d5-4881869cc773"
          },
          {
            "name": "РКП, без замены AtomId | Прошедшая неделя",
            "expression": "CALCULATE([РКП, без замены AtomId], FILTER (ALL ('Calendar'), [weekdiff] = 1))",
            "displayFolder": "РКП, без замены AtomId",
            "lineageTag": "8dec407b-626d-478a-8766-ea08e2e7801a",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "РКП, без замены AtomId, цена",
            "expression": "DIVIDE([Расход без НДС],[РКП, без замены AtomId])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "e43a7dd2-f7c6-4290-8651-8dd99b36b325",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "РКП, без замены AtomId, цена ПП",
            "expression": [
              "DIVIDE([Расход ПП],[РКП ПП])",
              ""
            ],
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "6d52489b-e58e-4605-b8e6-5d8320bde90c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "РКП, без замены AtomId, цена | Прошедшая неделя",
            "expression": "DIVIDE([Расход без НДС | Прошедшая неделя],[РКП, без замены AtomId | Прошедшая неделя])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "a14816d6-e677-4bb1-a67b-b77983a5db95",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Изменение РКП, цена",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE([РКП, без замены AtomId, цена | Прошедшая неделя] - [РКП, без замены AtomId, цена ПП],[РКП, без замены AtomId, цена ПП],BLANK()),",
              "    DIVIDE([РКП, без замены AtomId, цена] - [РКП, без замены AtomId, цена ПП],[РКП, без замены AtomId, цена ПП],BLANK())",
              ")"
            ],
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "248ecf20-3f51-4da1-a33e-6facf0192bd7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение РКП, цена (текст)",
            "expression": [
              "IF (",
              "     [Изменение РКП, цена]> 0,",
              "    \"▲ \" & FORMAT ( [Изменение РКП, цена], \"0.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение РКП, цена], \"0.##%\" )",
              ")",
              ""
            ],
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "e216107a-c1d9-44eb-96d6-31d2f8a3342f"
          },
          {
            "name": "РКП, цена, по периодам",
            "expression": "DIVIDE([Расход, по периодам], [РКП, без замены AtomId, по периодам])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "displayFolder": "РКП, без замены AtomId, цена",
            "lineageTag": "fd2f24c8-a8d1-41c7-89af-b3644b050ea7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Клики → РКП, без замены AtomId",
            "expression": "DIVIDE([РКП, без замены AtomId],[Клики],BLANK())",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "eb30215e-10b8-49ab-b4fc-db18a0cb8910"
          },
          {
            "name": "Клики → РКП, без замены AtomId ПП",
            "expression": "DIVIDE([РКП, без замены AtomId],[Клики ПП],BLANK())",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "fda1391c-8c6d-4b7f-8e9c-9ca2400c77ab"
          },
          {
            "name": "Клики → РКП, без замены AtomId | Прошедшая неделя",
            "expression": "DIVIDE([РКП, без замены AtomId | Прошедшая неделя],[Клики | Прошедшая неделя], BLANK())",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "0ba85b5d-ff4b-4509-8557-8f74baacee23"
          },
          {
            "name": "Изменение Клики → РКП, без замены AtomId",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    [Клики → РКП, без замены AtomId | Прошедшая неделя]- [Клики → РКП, без замены AtomId ПП],",
              "    [Клики → РКП, без замены AtomId] - [Клики → РКП, без замены AtomId ПП]",
              ")"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "86e3c1f4-05ab-4fc9-b954-f383b7589ae1"
          },
          {
            "name": "Изменение Клики → РКП, без замены AtomId (текст)",
            "expression": [
              "IF (",
              "     [Изменение Клики → РКП, без замены AtomId]> 0,",
              "    \"▲ \" & FORMAT ( [Изменение Клики → РКП, без замены AtomId], \"0.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение Клики → РКП, без замены AtomId], \"0.##%\" )",
              ")"
            ],
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "9bf02594-2f92-42ca-aaa4-26cb74605dd2"
          },
          {
            "name": "Клики → РКП, без замены AtomId по периодам",
            "expression": "DIVIDE([РКП, без замены AtomId, по периодам],[Клики, по периодам], BLANK())",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Клики → РКП, без замены AtomId",
            "lineageTag": "3f3c4592-af71-4a8c-9b2b-fccbf5b51208"
          },
          {
            "name": "Количество атомов с неверной воронкой трафик → ркп",
            "expression": "SUMMARIZE(AtomsWithExtensions,AtomsWithExtensions[AtomId],\"Трафик → РКП, без замены AtomId\",[Трафик → РКП, без замены AtomId])",
            "lineageTag": "ac6fe77a-013d-4584-a820-9238adf43640"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c1d0d0e7-559e-4561-bfeb-51f53d5b0b45"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmClientPotCli"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":22,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmClientPotCli/Changed Type.{WhenCreated,0}\",\"Section1/crmClientPotCli/Changed Type.{PotCliDepth,1}\",\"Section1/crmClientPotCli/Changed Type.{Make,2}\",\"Section1/crmClientPotCli/Changed Type.{Site,3}\",\"Section1/crmClientPotCli/Changed Type.{AtomId,4}\",\"Section1/crmClientPotCli/Source.{AtomdIdBeforeReplace,5}\",\"Section1/crmClientPotCli/Changed Type.{date,6}\",\"Section1/crmClientPotCli/Changed Type.{PotCliCounts,7}\",\"Section1/crmClientPotCli/Source.{РКП статус,8}\",\"Section1/crmClientPotCli/Source.{3 Встреча назначена,9}\",\"Section1/crmClientPotCli/Source.{3 Встреча,10}\",\"Section1/crmClientPotCli/Source.{4 Тест-драйв назначен,11}\",\"Section1/crmClientPotCli/Source.{4 Тест-драйв,12}\",\"Section1/crmClientPotCli/Source.{5 Предложение,13}\",\"Section1/crmClientPotCli/Source.{6 Сделка,14}\",\"Section1/crmClientPotCli/Source.{7 Выдача,15}\",\"Section1/crmClientPotCli/Source.{Расторжение,16}\",\"Section1/crmClientPotCli/Source.{РКП — Есть хотя-бы одно из событий,17}\",\"Section1/crmClientPotCli/Source.{comagic_starttime,18}\",\"Section1/crmClientPotCli/Source.{traffic_created,19}\",\"Section1/crmClientPotCli/Source.{trafic_finded,20}\",\"Section1/crmClientPotCli/Source.{comagic_finded,21}\"],\"ColumnCount\":22,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmClientPotCli/Changed Type.{WhenCreated,0}\",\"Section1/crmClientPotCli/Changed Type.{PotCliDepth,1}\",\"Section1/crmClientPotCli/Changed Type.{Make,2}\",\"Section1/crmClientPotCli/Changed Type.{Site,3}\",\"Section1/crmClientPotCli/Changed Type.{AtomId,4}\",\"Section1/crmClientPotCli/Source.{AtomdIdBeforeReplace,5}\",\"Section1/crmClientPotCli/Changed Type.{date,6}\",\"Section1/crmClientPotCli/Changed Type.{PotCliCounts,7}\",\"Section1/crmClientPotCli/Source.{РКП статус,8}\",\"Section1/crmClientPotCli/Source.{3 Встреча назначена,9}\",\"Section1/crmClientPotCli/Source.{3 Встреча,10}\",\"Section1/crmClientPotCli/Source.{4 Тест-драйв назначен,11}\",\"Section1/crmClientPotCli/Source.{4 Тест-драйв,12}\",\"Section1/crmClientPotCli/Source.{5 Предложение,13}\",\"Section1/crmClientPotCli/Source.{6 Сделка,14}\",\"Section1/crmClientPotCli/Source.{7 Выдача,15}\",\"Section1/crmClientPotCli/Source.{Расторжение,16}\",\"Section1/crmClientPotCli/Source.{РКП — Есть хотя-бы одно из событий,17}\",\"Section1/crmClientPotCli/Source.{comagic_starttime,18}\",\"Section1/crmClientPotCli/Source.{traffic_created,19}\",\"Section1/crmClientPotCli/Source.{trafic_finded,20}\",\"Section1/crmClientPotCli/Source.{comagic_finded,21}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmCarSale",
        "lineageTag": "ae7522db-7957-4396-8b3d-0c50bd2b68d7",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "Long Date",
            "lineageTag": "6a01d2d6-a2a6-4aef-b54c-ec72ff4322f2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "lineageTag": "65059e32-7c87-4c2b-8820-fe151bbcd368",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "dateEvent",
            "dataType": "dateTime",
            "sourceColumn": "dateEvent",
            "formatString": "Long Date",
            "lineageTag": "c97ab09d-8bb0-4e0d-808a-763c54d546fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "5eccc0c5-9648-40c8-a2d8-9dd2bf369c10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "47193d24-2299-4a7c-9e32-1b9a701d4fa3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "штуки",
            "dataType": "int64",
            "sourceColumn": "штуки",
            "lineageTag": "42418916-a653-4c26-b2e3-331750870409",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DateCreated_CarSale",
            "dataType": "dateTime",
            "sourceColumn": "DateCreated_CarSale",
            "formatString": "Long Date",
            "lineageTag": "914fa6be-326d-49d4-a070-b893ca3ede57",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Контракты_шт",
            "dataType": "int64",
            "sourceColumn": "Контракты_шт",
            "formatString": "0",
            "lineageTag": "79252fa2-cd88-49e6-812f-65303fa5d576",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Контракты_сумма_₽",
            "formatString": "0",
            "lineageTag": "e29a5547-6078-40a8-ae52-70deeef80c91",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_шт",
            "dataType": "int64",
            "sourceColumn": "Сделки_шт",
            "formatString": "0",
            "lineageTag": "a6edab85-99c8-4e99-8740-6607eebdf15e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Сделки_сумма_₽",
            "formatString": "0",
            "lineageTag": "877a77ef-9d31-4700-b4a7-da1d0aeda42b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_шт",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_шт",
            "formatString": "0",
            "lineageTag": "e8e8cbb4-7088-4c76-b86c-e732d220e014",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_₽",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_₽",
            "formatString": "0",
            "lineageTag": "b322a827-ab43-4eaa-8da3-509bcddeacef",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_шт",
            "dataType": "int64",
            "sourceColumn": "Открытая_шт",
            "formatString": "0",
            "lineageTag": "bd9688b9-306c-4a9f-96d8-f63978e8a6a2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_₽",
            "dataType": "double",
            "sourceColumn": "Открытая_₽",
            "lineageTag": "054030e5-ba62-4954-8f38-dcfa1cab64b3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_шт",
            "dataType": "int64",
            "sourceColumn": "Несостоявшаяся_шт",
            "formatString": "0",
            "lineageTag": "1b50ed8b-c089-497a-989d-bd99213d4b6b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_₽",
            "dataType": "double",
            "sourceColumn": "Несостоявшаяся_₽",
            "lineageTag": "59baf2ab-80f8-4f30-9723-2f7648b72bb0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "479a1d85-5637-4701-b235-1c763509d177",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmCarSale",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[crmCarSale]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"date\", \"date\"}, {\"AtomId\", \"AtomId\"}, {\"DateCreated_CarSale\", \"DateCreated_CarSale\"}, {\"dateEvent\", \"dateEvent\"}, {\"Make\", \"Make\"},  {\"Site\", \"Site\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"date\", type date}, {\"AtomId\", Int64.Type}, {\"DateCreated_CarSale\", type date}, {\"dateEvent\", type date}, {\"Make\", type text}, {\"Site\", type text}, {\"штуки\", Int64.Type}, {\"Контракты_шт\", Int64.Type}, {\"Контракты_сумма_₽\", Int64.Type}, {\"Сделки_шт\", Int64.Type}, {\"Сделки_сумма_₽\", Int64.Type}, {\"Архив предложений_шт\", Int64.Type}, {\"Архив предложений_₽\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Контракты, шт",
            "expression": "sum([Контракты_шт])",
            "formatString": "#,0",
            "lineageTag": "94321c98-e5a0-4d29-a542-fa068e0d5021"
          },
          {
            "name": "РКП Эффективная → Контракты",
            "expression": "DIVIDE([Контракты, шт],[РКП Эффективная])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fec6c125-d7d3-42a8-892d-ab9f54dae84e"
          },
          {
            "name": "Контракты, цена",
            "expression": "DIVIDE([Расход без НДС],[Контракты, шт])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "0b7d21f9-1ad7-4173-a0d2-bccd24e5fd54",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Контракты сумма, ₽",
            "expression": "sum([Контракты_сумма_₽])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "844d9643-8407-43c9-8149-d41a3dfa79f7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Контракты, шт, по дате создания",
            "expression": "CALCULATE([Контракты, шт],USERELATIONSHIP('Calendar'[Date],crmCarSale[DateCreated_CarSale]))",
            "formatString": "#,0",
            "lineageTag": "8a113fed-b49e-4986-9f2f-fe9d5184471c"
          },
          {
            "name": "Несостоявшаяся, шт",
            "expression": "sum(crmCarSale[Несостоявшаяся_шт]) ",
            "formatString": "#,0",
            "lineageTag": "426eec22-46d1-4864-9d7d-75ec52680c28"
          },
          {
            "name": "Несостоявшаяся, ₽",
            "expression": "SUM('crmCarSale'[Несостоявшаяся_₽])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "9bf2b582-339a-4b56-8db9-01c062829847",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Открытая, шт",
            "expression": "SUM('crmCarSale'[Открытая_шт])",
            "formatString": "#,0",
            "lineageTag": "cdbed973-bd74-467b-8469-e1c34de991e1"
          },
          {
            "name": "Открытая, ₽",
            "expression": "sum('crmCarSale'[Открытая_₽])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "4ecc1516-dd7d-49f5-afe3-92f520207d34",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Архив предложений, шт",
            "expression": "SUM('crmCarSale'[Архив предложений_шт]) ",
            "formatString": "#,0",
            "lineageTag": "de3edf59-a63b-4fc1-82c8-fafeeb35fb26"
          },
          {
            "name": "Архив предложений, ₽",
            "expression": "SUM('crmCarSale'[Архив предложений_₽])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "2c73585a-39d7-41a9-8416-ee8712e07ef8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сделки, шт",
            "expression": "sum('crmCarSale'[Сделки_шт])",
            "formatString": "#,0",
            "lineageTag": "578cd07b-5653-409c-a53f-829e2b0c8797"
          },
          {
            "name": "Сделки сумма, ₽",
            "expression": "SUM('crmCarSale'[Сделки_сумма_₽])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7bf92a05-ad8c-4e12-94f8-38165e69d611",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Контракты → Несостоявшаяся",
            "expression": "DIVIDE([Несостоявшаяся, шт],[Контракты, шт],BLANK()) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5aee3292-870d-422c-8dba-867c8e9e96dd"
          },
          {
            "name": "Несостоявшаяся, шт, по дате создания",
            "expression": "CALCULATE([Несостоявшаяся, шт],USERELATIONSHIP('Calendar'[Date],crmCarSale[DateCreated_CarSale]))",
            "formatString": "#,0",
            "lineageTag": "044b0c12-5823-4634-bb93-e613510daa7f"
          },
          {
            "name": "Контракты → Открытая",
            "expression": "DIVIDE([Открытая, шт],[Контракты, шт],BLANK()) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f369a66e-3b59-452d-ae22-d17187d9b1dd"
          },
          {
            "name": "Открытая, шт, по дате создания",
            "expression": "CALCULATE([Открытая, шт],USERELATIONSHIP('Calendar'[Date],crmCarSale[DateCreated_CarSale]))",
            "formatString": "#,0",
            "lineageTag": "a5f91a67-1d43-44e7-9e6c-3f4c560a1b4c"
          },
          {
            "name": "Контракты → Сделки",
            "expression": "DIVIDE([Сделки, шт],[Контракты, шт],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "347e054a-39a8-43d7-beb0-3d53889e6828"
          },
          {
            "name": "Сделки, шт, по дате создания",
            "expression": "CALCULATE([Сделки, шт],USERELATIONSHIP('Calendar'[Date],crmCarSale[DateCreated_CarSale]))",
            "formatString": "#,0",
            "lineageTag": "d0fb3781-efe4-4327-824f-f5697720d262"
          },
          {
            "name": "РКП Эффективная → Сделки",
            "expression": "DIVIDE([Сделки, шт],[РКП Эффективная],BLANK()) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "23b70933-c2c2-44ab-9df1-6e05c020e9c2"
          },
          {
            "name": "Контракты, шт, без замены AtomId",
            "expression": "sum(crmCarSaleAtomIdBeforeReplace[Контракты_шт])",
            "formatString": "#,0",
            "lineageTag": "27abb751-6af0-415a-a637-ed45cfa87422"
          },
          {
            "name": "Сделки, шт, без замены AtomId",
            "expression": "SUM(crmCarSaleAtomIdBeforeReplace[Сделки_шт])",
            "formatString": "#,0",
            "lineageTag": "5917d50b-3587-44a8-8c9c-dd46f74e2add"
          },
          {
            "name": "Изменение контрактов с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Контракты, шт, без замены AtomId | Прошедшая неделя] - [Контракты ПП],",
              "        [Контракты ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE (",
              "        [Контракты, шт, без замены AtomId] - [Контракты ПП],",
              "        [Контракты ПП],",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "lineageTag": "96e6f9f8-83b8-4a1f-b1de-79f1d1941811",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение контрактов с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение контрактов с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение контрактов с пп], \"0.0#%\" ),",
              "    IF (",
              "        OR ( ISBLANK ( [Изменение контрактов с пп] ), [Изменение контрактов с пп] = 0 ),",
              "        \"-\",",
              "        \"▼ \" & FORMAT ( [Изменение контрактов с пп], \"0.0#%\" )",
              "    )",
              ")"
            ],
            "lineageTag": "601e3cb7-4ebf-4f23-8614-6836b8e8bae3"
          },
          {
            "name": "Изменение Сделок с пп",
            "expression": [
              "IF (",
              "    [SelectedCamparePeriodType] = 2,",
              "    DIVIDE (",
              "        [Сделки, шт, без замены AtomId | Прошедшая неделя] - [Сделки ПП],",
              "        [Сделки ПП],",
              "        BLANK ()",
              "    ),",
              "    DIVIDE ( [Сделки, шт, без замены AtomId] - [Сделки ПП], [Сделки ПП], BLANK () )",
              ")"
            ],
            "lineageTag": "4a4abd40-847f-4220-9038-0b0f4b0209ff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Изменение Сделок с пп (текст)",
            "expression": [
              "IF (",
              "    [Изменение Сделок с пп] > 0,",
              "    \"▲ \" & FORMAT ( [Изменение Сделок с пп], \"#.##%\" ),",
              "    \"▼ \" & FORMAT ( [Изменение Сделок с пп], \"#.##%\" )",
              ")"
            ],
            "lineageTag": "0a57a5cb-4b5c-4302-a7e2-4d16347ce8ee"
          },
          {
            "name": "Контракты ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Контракты, шт, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Контракты, шт, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Контракты, шт, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "641f165d-c42c-4e1e-91e0-cffe60dd1e85"
          },
          {
            "name": "Сделки ПП",
            "expression": [
              "SWITCH (",
              "    [SelectedCamparePeriodType],",
              "    1,",
              "        CALCULATE (",
              "            [Сделки, шт, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [Date] >= [MidDate] && [Date] <= [MaxDate] )",
              "        ),",
              "    3,",
              "        CALCULATE (",
              "            [Сделки, шт, без замены AtomId],",
              "            DATEADD ( 'Calendar'[Date], -1 * [Выбрано дней], DAY )",
              "        ),",
              "    2,",
              "        CALCULATE (",
              "            [Сделки, шт, без замены AtomId],",
              "            FILTER ( ALL ( 'Calendar' ), [weekdiff] = 2 )",
              "        ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "214f5705-563f-41d4-ac02-a0f663015613"
          },
          {
            "name": "Контракты, шт, без замены AtomId | Прошедшая неделя",
            "expression": [
              "CALCULATE (",
              "    [Контракты, шт, без замены AtomId],",
              "    FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              ")"
            ],
            "lineageTag": "1042da99-ca90-4b73-81e0-c13c645b7639"
          },
          {
            "name": "Сделки, шт, без замены AtomId | Прошедшая неделя",
            "expression": [
              "CALCULATE (",
              "    [Сделки, шт, без замены AtomId],",
              "    FILTER ( ALL ( 'Calendar' ), [weekdiff] = 1 )",
              ")"
            ],
            "lineageTag": "f7c4b990-b516-48ed-994a-e5dcefe8bdc8"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "610bc065-b84e-45d4-a604-303a354305ab"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmCarSale"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":18,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmCarSale/Changed Type.{date,0}\",\"Section1/crmCarSale/Changed Type.{AtomId,1}\",\"Section1/crmCarSale/Changed Type.{AtomdIdBeforeReplace,2}\",\"Section1/crmCarSale/Changed Type.{DateCreated_CarSale,3}\",\"Section1/crmCarSale/Changed Type.{dateEvent,4}\",\"Section1/crmCarSale/Changed Type.{Make,5}\",\"Section1/crmCarSale/Changed Type.{Site,6}\",\"Section1/crmCarSale/Changed Type.{штуки,7}\",\"Section1/crmCarSale/Changed Type.{Контракты_шт,8}\",\"Section1/crmCarSale/Changed Type.{Контракты_сумма_₽,9}\",\"Section1/crmCarSale/Changed Type.{Сделки_шт,10}\",\"Section1/crmCarSale/Changed Type.{Сделки_сумма_₽,11}\",\"Section1/crmCarSale/Changed Type.{Архив предложений_шт,12}\",\"Section1/crmCarSale/Changed Type.{Архив предложений_₽,13}\",\"Section1/crmCarSale/Source.{Открытая_шт,14}\",\"Section1/crmCarSale/Source.{Открытая_₽,15}\",\"Section1/crmCarSale/Source.{Несостоявшаяся_шт,16}\",\"Section1/crmCarSale/Source.{Несостоявшаяся_₽,17}\"],\"ColumnCount\":18,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmCarSale/Changed Type.{date,0}\",\"Section1/crmCarSale/Changed Type.{AtomId,1}\",\"Section1/crmCarSale/Changed Type.{AtomdIdBeforeReplace,2}\",\"Section1/crmCarSale/Changed Type.{DateCreated_CarSale,3}\",\"Section1/crmCarSale/Changed Type.{dateEvent,4}\",\"Section1/crmCarSale/Changed Type.{Make,5}\",\"Section1/crmCarSale/Changed Type.{Site,6}\",\"Section1/crmCarSale/Changed Type.{штуки,7}\",\"Section1/crmCarSale/Changed Type.{Контракты_шт,8}\",\"Section1/crmCarSale/Changed Type.{Контракты_сумма_₽,9}\",\"Section1/crmCarSale/Changed Type.{Сделки_шт,10}\",\"Section1/crmCarSale/Changed Type.{Сделки_сумма_₽,11}\",\"Section1/crmCarSale/Changed Type.{Архив предложений_шт,12}\",\"Section1/crmCarSale/Changed Type.{Архив предложений_₽,13}\",\"Section1/crmCarSale/Source.{Открытая_шт,14}\",\"Section1/crmCarSale/Source.{Открытая_₽,15}\",\"Section1/crmCarSale/Source.{Несостоявшаяся_шт,16}\",\"Section1/crmCarSale/Source.{Несостоявшаяся_₽,17}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmSitesList",
        "lineageTag": "63466899-bd0f-47d4-be51-17e88f7f2474",
        "columns": [
          {
            "name": "Площадка",
            "dataType": "string",
            "sourceColumn": "Площадка",
            "lineageTag": "9864c976-1de7-45eb-b032-697cb00b00a0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmSitesList",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[crmSitesList]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Site\", \"Site\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Site\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Site\", \"Площадка\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5516aa31-0a2f-451f-9217-cd3ea90090a1"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmSitesList"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmSitesList/Changed Type.{Site,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmSitesList/Changed Type.{Site,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "crmMakeList",
        "lineageTag": "7e471e88-3e5c-447a-b042-01b894f9893d",
        "columns": [
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "244ca1ec-0216-43e9-ad90-005174496a95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Бренд Авто MT",
            "dataType": "string",
            "sourceColumn": "Бренд Авто MT",
            "lineageTag": "ed9b9613-e169-4714-acee-403c80769a0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmMakeList",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[crmMakeList]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Make\", \"Make\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Make\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "26b74a09-9807-41c1-a971-b11500cf3647"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmMakeList"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmMakeList/Changed Type.{Make,0}\",\"Section1/crmMakeList/Source.{Бренд Авто MT,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmMakeList/Changed Type.{Make,0}\",\"Section1/crmMakeList/Source.{Бренд Авто MT,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "MainTableColumns",
        "lineageTag": "f0eed958-47eb-4ead-8a05-01a84d90a324",
        "columns": [
          {
            "name": "ColumsForReport",
            "dataType": "string",
            "sourceColumn": "ColumsForReport",
            "sortByColumn": "Index",
            "lineageTag": "59e11646-9bd5-4f56-bc17-088bd540fdaa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Index",
            "dataType": "double",
            "sourceColumn": "Index",
            "lineageTag": "06f3d7e1-2c48-4120-89ed-6a2fcd9eedea",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "MainTableColumns-715d9d0c-c48b-4452-ac9b-d04ac14029d2",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WurDgwoaLjRdbL+y7sEUpVgcosOjC1gubFS7MuzAfna+jcLENyNl7YQOKzMILWy82XNh0YcfFRlzi6DqBhik8apukcGERUMWGiy0XdlzYpaOgCtWOEMMQ0FG4sAzZoAUXZsHcCWYiWxQLAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"ColumsForReport\"}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Renamed Columns\", \"Index\", 0, 1)",
                "in",
                "    #\"Added Index\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Факт",
            "expression": [
              "",
              "    SWITCH(",
              "        SELECTEDVALUE(MainTableColumns[ColumsForReport]),",
              "        \"Расход\",[Расход без НДС],",
              "        \"Тег ОП\",[Comagic Тэг «ОП»],",
              "        \"Тег ОП, цена\",[Тег ОП цена],",
              "        \"Тег Сервис\",[Comagic Тэг «Сервис»],",
              "        \"Тег Сервис, цена\",[Comagic Тэг «Сервис», цена],",
              "        \"ОП → Трафик, %\",DIVIDE([Трафик новый авто по дате создания трафик],[Comagic Тэг «ОП»]),",
              "        \"Трафик\",[Трафик новый авто по дате создания трафик],",
              "        \"Трафик, цена\",DIVIDE([Расход без НДС],[Трафик новый авто по дате создания трафик]),",
              "        \"РКП\",[РКП],",
              "        \"РКП, цена\",[РКП, цена],",
              "        BLANK())"
            ],
            "formatString": "#,0",
            "lineageTag": "3d3040a2-79ac-446a-98a2-0b5fbc652a43",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "План",
            "expression": [
              "",
              "    SWITCH(",
              "        SELECTEDVALUE(MainTableColumns[ColumsForReport]),\"Расход\",[Бюджет план без НДС],",
              "        \"Тег ОП\",[План - тег продажа],",
              "        \"Тег ОП, цена\",DIVIDE([Бюджет план без НДС],[План - тег продажа]),",
              "        \"Тег Сервис\",sum(PlansFinal[Calls_Service]),",
              "        \"Тег Сервис, цена\",[План звонки Сервис, цена],",
              "        \"Трафик\",0,",
              "        \"РКП\",0",
              "        ,0)"
            ],
            "lineageTag": "9360c167-e51d-4119-82bd-199ecc7fce44",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% выполнения",
            "expression": "IFERROR(DIVIDE([Факт],[План],1),BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "fbe447ea-3862-41f6-bd1c-5a4af866798f"
          },
          {
            "name": "Затраты на единицу",
            "expression": "if(SELECTEDVALUE(MainTableColumns[ColumsForReport])<>\"Затраты на маркетинг\",DIVIDE([Расход без НДС],MainTableColumns[Факт]),[Расход без НДС])",
            "formatString": "#,0.0\\ \"₽\";-#,0.0\\ \"₽\";#,0.0\\ \"₽\"",
            "lineageTag": "cfe3f925-823d-4a22-b35c-44d340cea68c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "%вып -1",
            "expression": "if([% выполнения]<1,-1,1)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "e402fb41-95c4-4a9d-94d6-355042f0c34f"
          },
          {
            "name": "План + 20%",
            "expression": "if([План]>[Факт],[План]*1.1,[Факт]*1.1)",
            "lineageTag": "dc888eb8-a17d-4f68-9688-98a4f8091b3a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1d2bf810-6be0-4251-aa40-af543471a7c7"
          },
          {
            "name": "LinkedQueryName",
            "value": "MainTableColumns"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":2,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/MainTableColumns/Added Index.{ColumsForReport,0}\",\"Section1/MainTableColumns/Added Index.{Index,1}\"],\"ColumnCount\":2,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/MainTableColumns/Added Index.{ColumsForReport,0}\",\"Section1/MainTableColumns/Added Index.{Index,1}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ExtentionsForReports",
        "lineageTag": "757355f3-67e0-4413-926f-27b3d4794bca",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Type",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Type]",
            "lineageTag": "ac1ec89a-c679-49eb-b809-8c162765453e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Values",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "AtomsWithExtensions[Канал]",
            "lineageTag": "65929d4d-68eb-45d5-b77a-f7dc4dd4a1d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ExtentionsForReports-acd7b946-eada-4bba-94c7-5f2bccec7f2b",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "var GroupSources = CROSSJOIN(ROW(\"Type\",\"3 Группа источников\"), VALUES(AtomsWithExtensions[Группа источников]))",
                "var Sources = CROSSJOIN(ROW(\"Type\",\"4 Источник\"), VALUES(AtomsWithExtensions[Источник]))",
                "var GroupOfGroups = CROSSJOIN(ROW(\"Type\",\"2 Канал\"), VALUES(AtomsWithExtensions[Канал]))",
                "var Campaigns = CROSSJOIN(ROW(\"Type\",\"5 Кампания\"), VALUES(AtomsWithExtensions[Кампания]))",
                "var AutoBrand = CROSSJOIN(ROW(\"Type\",\"1 Бренд Авто\"), VALUES(AtomsWithExtensions[Бренд авто]))",
                "var Places = CROSSJOIN(ROW(\"Type\",\"6 Площадка рекламы\"), VALUES(AtomsWithExtensions[Площадка рекламы]))",
                "return UNION(UNION(UNION(UNION(UNION(GroupOfGroups,GroupSources),Sources),Campaigns),AutoBrand),Places)"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Факт динамический",
            "expression": [
              "",
              "if(HASONEVALUE('ExtentionsForReports'[Type]), ",
              "    SWITCH(VALUES('ExtentionsForReports'[Type])",
              "    ,\"3 Группа источников\",   CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Группа источников]))",
              "    ,\"4 Источник\",            CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Источник]))",
              "    ,\"5 Кампания\",            CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Кампания]))",
              "    ,\"1 Бренд Авто\",          CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Бренд авто]))",
              "    ,\"2 Канал\",               CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Канал]))",
              "    ,\"6 Площадка рекламы\",    CALCULATE([Факт],TREATAS(VALUES('ExtentionsForReports'[Values]),AtomsWithExtensions[Площадка рекламы]))",
              "    )",
              ")"
            ],
            "lineageTag": "ce701d69-ccbc-4250-b56a-3953f32323e8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b48bd7cc482140a0a5b0bdbf08a8dede"
          }
        ]
      },
      {
        "name": "Comagic Bez RK",
        "lineageTag": "246f09b8-7dac-486c-9769-860e60e43401",
        "columns": [
          {
            "name": "CampaignName",
            "dataType": "string",
            "sourceColumn": "CampaignName",
            "lineageTag": "0783a832-2a45-4743-b6cc-3339ba366486",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SiteDomainName",
            "dataType": "string",
            "sourceColumn": "SiteDomainName",
            "lineageTag": "7e023dfa-500a-4150-a905-dff24296c135",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UtmSource",
            "dataType": "string",
            "sourceColumn": "UtmSource",
            "lineageTag": "4c7d8788-6086-4f94-86b8-486a94be2e29",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UtmMedium",
            "dataType": "string",
            "sourceColumn": "UtmMedium",
            "lineageTag": "c0cdcba2-f56b-4c37-964f-5dfddb57f4e5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UtmCampaign",
            "dataType": "string",
            "sourceColumn": "UtmCampaign",
            "lineageTag": "a45b7142-c53c-4c9c-b90a-2a46f48c4f3c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "штуки",
            "dataType": "int64",
            "sourceColumn": "штуки",
            "formatString": "0",
            "lineageTag": "fddff244-606a-4078-b60d-09801392ad64",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "datemin",
            "dataType": "dateTime",
            "sourceColumn": "datemin",
            "formatString": "dd.mm.yy",
            "lineageTag": "0d2d25cc-92ea-456c-bbb2-d91a1402eb35",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "datemax",
            "dataType": "dateTime",
            "sourceColumn": "datemax",
            "formatString": "dd.mm.yy",
            "lineageTag": "f988fbe0-1891-46c4-b82a-444999fd8454",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Comagic Bez RK-f2ce565c-1ef5-4191-b54e-1c2c5ef5be05",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM pivotparts.ComagicBezRK\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"datemin\", type date}, {\"datemax\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f4472b00-3023-411f-bcae-d156eb587bd8"
          },
          {
            "name": "LinkedQueryName",
            "value": "Comagic Bez RK"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":8,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Comagic Bez RK/Source.{CampaignName,0}\",\"Section1/Comagic Bez RK/Source.{SiteDomainName,1}\",\"Section1/Comagic Bez RK/Source.{UtmSource,2}\",\"Section1/Comagic Bez RK/Source.{UtmMedium,3}\",\"Section1/Comagic Bez RK/Source.{UtmCampaign,4}\",\"Section1/Comagic Bez RK/Source.{штуки,5}\",\"Section1/Comagic Bez RK/Changed Type1.{datemin,6}\",\"Section1/Comagic Bez RK/Changed Type1.{datemax,7}\"],\"ColumnCount\":8,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Comagic Bez RK/Source.{CampaignName,0}\",\"Section1/Comagic Bez RK/Source.{SiteDomainName,1}\",\"Section1/Comagic Bez RK/Source.{UtmSource,2}\",\"Section1/Comagic Bez RK/Source.{UtmMedium,3}\",\"Section1/Comagic Bez RK/Source.{UtmCampaign,4}\",\"Section1/Comagic Bez RK/Source.{штуки,5}\",\"Section1/Comagic Bez RK/Changed Type1.{datemin,6}\",\"Section1/Comagic Bez RK/Changed Type1.{datemax,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "Used_crmClientPotCli",
        "lineageTag": "04e9d9fe-a7ff-44d4-a4df-5540e8e0980e",
        "columns": [
          {
            "name": "WhenCreated",
            "dataType": "dateTime",
            "sourceColumn": "WhenCreated",
            "formatString": "General Date",
            "lineageTag": "15d1a968-2fd9-4c0f-b528-6a4fd5123cc6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliDepth",
            "dataType": "string",
            "sourceColumn": "PotCliDepth",
            "lineageTag": "83b0440d-3764-4e0f-bc46-e40e8812cb15",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "6d2c12bb-6136-4d18-8b83-dc121dc4fb7a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Площадка МТ РКП",
            "dataType": "string",
            "sourceColumn": "Площадка МТ РКП",
            "lineageTag": "43e1f661-0593-49c7-bd1e-ffb0d4aafb2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "1998680b-1898-4e09-971f-773cecfd39b6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomdIdBeforeReplace",
            "dataType": "int64",
            "sourceColumn": "AtomdIdBeforeReplace",
            "formatString": "0",
            "lineageTag": "15af7b2b-cdd2-4a58-9aed-cb5d4eaa9858",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "General Date",
            "lineageTag": "d2882525-8df9-45d9-ac6c-6608d63c031e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliCounts",
            "dataType": "int64",
            "sourceColumn": "PotCliCounts",
            "formatString": "0",
            "lineageTag": "feb9e8b3-561b-4aae-b3f7-b3a4c090dfdb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП статус",
            "dataType": "string",
            "sourceColumn": "РКП статус",
            "lineageTag": "2720e227-a337-421a-828e-1e8bba9f1c03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча назначена",
            "dataType": "int64",
            "sourceColumn": "3 Встреча назначена",
            "formatString": "0",
            "lineageTag": "56486a32-3cec-4498-baa7-0bc5a2a7e260",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча",
            "dataType": "int64",
            "sourceColumn": "3 Встреча",
            "formatString": "0",
            "lineageTag": "60479855-86d6-487a-a07f-18d5375ff5da",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв назначен",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв назначен",
            "formatString": "0",
            "lineageTag": "b9dc6aee-1545-41ab-8535-c9cdc07ef7cd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв",
            "formatString": "0",
            "lineageTag": "6f242fa4-f777-4cbc-be39-3dcf495ab386",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "5 Предложение",
            "dataType": "int64",
            "sourceColumn": "5 Предложение",
            "formatString": "0",
            "lineageTag": "34c8cba2-3c73-4268-aeac-e02eefa6ca1a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "6 Сделка",
            "dataType": "int64",
            "sourceColumn": "6 Сделка",
            "formatString": "0",
            "lineageTag": "ecf88674-5799-4ad8-b4b1-a0f3b22615ea",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "7 Выдача",
            "dataType": "int64",
            "sourceColumn": "7 Выдача",
            "formatString": "0",
            "lineageTag": "d641e82a-e5b1-4c5c-b18e-d0518db1d77c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Расторжение",
            "dataType": "int64",
            "sourceColumn": "Расторжение",
            "formatString": "0",
            "lineageTag": "21b1ff5d-b71d-4158-8185-ffe94d0d4ca6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП — Есть хотя-бы одно из событий",
            "dataType": "int64",
            "sourceColumn": "РКП — Есть хотя-бы одно из событий",
            "formatString": "0",
            "lineageTag": "4d1dc823-d220-4100-82bb-72f19abcf31c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "3de20c74-ca48-40a4-8e8b-ee8cfb824b41",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Used_crmClientPotCli-301ae7c6-2ffe-45ed-b7e9-ddecb674749f",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT    *   FROM [pivotparts].[crmClientPotCliUsedCars]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"WhenCreated\", \"WhenCreated\"}, {\"PotCliDepth\", \"PotCliDepth\"}, {\"Make\", \"Make\"}, {\"Site\", \"Site\"}, {\"AtomId\", \"AtomId\"}, {\"date\", \"date\"}, {\"PotCliCounts\", \"PotCliCounts\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"WhenCreated\", type datetime}, {\"PotCliDepth\", type text}, {\"Make\", type text}, {\"Site\", type text}, {\"AtomId\", Int64.Type}, {\"date\", type datetime}, {\"PotCliCounts\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Site\", \"Площадка МТ РКП\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "РКП пробеги, по дате создания",
            "expression": "CALCULATE([РКП],USERELATIONSHIP(Used_crmClientPotCli[WhenCreated],'Calendar'[Date]))",
            "formatString": "0",
            "lineageTag": "977bfe6f-ff83-4440-b314-6265e96fb5b6"
          },
          {
            "name": "РКП пробеги",
            "expression": "SUM(Used_crmClientPotCli[PotCliCounts])",
            "formatString": "0",
            "lineageTag": "fbdcd564-5e19-4870-bbcf-65a82dbc4321"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fff3015d-8fc9-40be-a359-78f0c334e5ba"
          },
          {
            "name": "LinkedQueryName",
            "value": "Used_crmClientPotCli"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":18,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Used_crmClientPotCli/Changed Type.{WhenCreated,0}\",\"Section1/Used_crmClientPotCli/Changed Type.{PotCliDepth,1}\",\"Section1/Used_crmClientPotCli/Changed Type.{Make,2}\",\"Section1/Used_crmClientPotCli/Changed Type.{Site,3}\",\"Section1/Used_crmClientPotCli/Changed Type.{AtomId,4}\",\"Section1/Used_crmClientPotCli/Source.{AtomdIdBeforeReplace,5}\",\"Section1/Used_crmClientPotCli/Changed Type.{date,6}\",\"Section1/Used_crmClientPotCli/Changed Type.{PotCliCounts,7}\",\"Section1/Used_crmClientPotCli/Source.{РКП статус,8}\",\"Section1/Used_crmClientPotCli/Source.{3 Встреча назначена,9}\",\"Section1/Used_crmClientPotCli/Source.{3 Встреча,10}\",\"Section1/Used_crmClientPotCli/Source.{4 Тест-драйв назначен,11}\",\"Section1/Used_crmClientPotCli/Source.{4 Тест-драйв,12}\",\"Section1/Used_crmClientPotCli/Source.{5 Предложение,13}\",\"Section1/Used_crmClientPotCli/Source.{6 Сделка,14}\",\"Section1/Used_crmClientPotCli/Source.{7 Выдача,15}\",\"Section1/Used_crmClientPotCli/Source.{Расторжение,16}\",\"Section1/Used_crmClientPotCli/Source.{РКП — Есть хотя-бы одно из событий,17}\"],\"ColumnCount\":18,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Used_crmClientPotCli/Changed Type.{WhenCreated,0}\",\"Section1/Used_crmClientPotCli/Changed Type.{PotCliDepth,1}\",\"Section1/Used_crmClientPotCli/Changed Type.{Make,2}\",\"Section1/Used_crmClientPotCli/Changed Type.{Site,3}\",\"Section1/Used_crmClientPotCli/Changed Type.{AtomId,4}\",\"Section1/Used_crmClientPotCli/Source.{AtomdIdBeforeReplace,5}\",\"Section1/Used_crmClientPotCli/Changed Type.{date,6}\",\"Section1/Used_crmClientPotCli/Changed Type.{PotCliCounts,7}\",\"Section1/Used_crmClientPotCli/Source.{РКП статус,8}\",\"Section1/Used_crmClientPotCli/Source.{3 Встреча назначена,9}\",\"Section1/Used_crmClientPotCli/Source.{3 Встреча,10}\",\"Section1/Used_crmClientPotCli/Source.{4 Тест-драйв назначен,11}\",\"Section1/Used_crmClientPotCli/Source.{4 Тест-драйв,12}\",\"Section1/Used_crmClientPotCli/Source.{5 Предложение,13}\",\"Section1/Used_crmClientPotCli/Source.{6 Сделка,14}\",\"Section1/Used_crmClientPotCli/Source.{7 Выдача,15}\",\"Section1/Used_crmClientPotCli/Source.{Расторжение,16}\",\"Section1/Used_crmClientPotCli/Source.{РКП — Есть хотя-бы одно из событий,17}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Used_crmCarSale",
        "lineageTag": "949b6b2f-b8fb-48aa-aab7-c12e70c1d709",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "Long Date",
            "lineageTag": "dd9d5de0-7562-46fa-bfd6-31b05b77721f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "a322b35d-b4ab-4c0f-a42b-98001232852e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomdIdBeforeReplace",
            "dataType": "int64",
            "sourceColumn": "AtomdIdBeforeReplace",
            "formatString": "0",
            "lineageTag": "2b1d4174-ea59-4d44-8a94-a492bd9e01e9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCreated_CarSale",
            "dataType": "dateTime",
            "sourceColumn": "DateCreated_CarSale",
            "formatString": "Long Date",
            "lineageTag": "0652b055-4743-413e-80a7-afa7a10b48b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "dateEvent",
            "dataType": "dateTime",
            "sourceColumn": "dateEvent",
            "formatString": "Long Date",
            "lineageTag": "aed69a80-0f44-413e-baf5-96811b817f9d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "04f009b7-3313-4e17-ae05-08900298d9a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "426f30ef-a94a-43ec-b94e-a93eea6695cc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "штуки",
            "dataType": "int64",
            "sourceColumn": "штуки",
            "formatString": "0",
            "lineageTag": "62c672b5-053d-47b5-98fd-377ea9321cb4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты_шт",
            "dataType": "int64",
            "sourceColumn": "Контракты_шт",
            "formatString": "0",
            "lineageTag": "d28d851c-eac4-4d2b-bed1-37ba60f1d0c3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Контракты_сумма_₽",
            "formatString": "0",
            "lineageTag": "0110aaa9-8714-4223-9540-e6e54f0f26e3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_шт",
            "dataType": "int64",
            "sourceColumn": "Сделки_шт",
            "formatString": "0",
            "lineageTag": "567481ae-20b9-43bb-b03b-f5198d7f21cc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Сделки_сумма_₽",
            "formatString": "0",
            "lineageTag": "4d0e63f9-79ba-4e80-b4cd-e1448332ecfd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_шт",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_шт",
            "formatString": "0",
            "lineageTag": "054fdb69-5fb3-4fe6-9436-eeb8b49b19cb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_₽",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_₽",
            "formatString": "0",
            "lineageTag": "1fa072c1-c48c-4d00-921a-05a5f05c06b5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_шт",
            "dataType": "int64",
            "sourceColumn": "Открытая_шт",
            "formatString": "0",
            "lineageTag": "cd336a46-76e1-4b02-89cd-62345c7ca1bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_₽",
            "dataType": "double",
            "sourceColumn": "Открытая_₽",
            "lineageTag": "142ff905-f4f1-4337-abbb-3222cff6938f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_шт",
            "dataType": "int64",
            "sourceColumn": "Несостоявшаяся_шт",
            "formatString": "0",
            "lineageTag": "25dcc20e-f003-45c4-9ecf-447508c36d9f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_₽",
            "dataType": "double",
            "sourceColumn": "Несостоявшаяся_₽",
            "lineageTag": "4e0dcab2-de7a-40a4-90f2-1d8a2bc1e855",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "0a99766c-57f8-45f4-9cdf-267a7de7275e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Used_crmCarSale-5787e2ab-6e59-41ed-8638-8973ad2a1208",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[crmCarSaleUsedCars]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"date\", \"date\"}, {\"AtomId\", \"AtomId\"}, {\"DateCreated_CarSale\", \"DateCreated_CarSale\"}, {\"dateEvent\", \"dateEvent\"}, {\"Make\", \"Make\"},  {\"Site\", \"Site\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"date\", type date}, {\"AtomId\", Int64.Type}, {\"AtomdIdBeforeReplace\", Int64.Type}, {\"DateCreated_CarSale\", type date}, {\"dateEvent\", type date}, {\"Make\", type text}, {\"Site\", type text}, {\"штуки\", Int64.Type}, {\"Контракты_шт\", Int64.Type}, {\"Контракты_сумма_₽\", Int64.Type}, {\"Сделки_шт\", Int64.Type}, {\"Сделки_сумма_₽\", Int64.Type}, {\"Архив предложений_шт\", Int64.Type}, {\"Архив предложений_₽\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Контракты пробеги, шт",
            "expression": "sum(Used_crmCarSale[Контракты_шт])",
            "formatString": "#,0",
            "lineageTag": "a3169163-11c8-4254-b37d-fa9e3aca2df3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Сделки пробеги, шт",
            "expression": "sum('Used_crmCarSale'[Сделки_шт])",
            "formatString": "#,0",
            "lineageTag": "0fab8d1f-6753-4fe4-94d8-211ad362c4da",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Сделки пробеги, шт, по дате создания",
            "expression": "CALCULATE([Сделки пробеги, шт],USERELATIONSHIP('Calendar'[Date],Used_crmCarSale[DateCreated_CarSale]))",
            "formatString": "0",
            "lineageTag": "596964ec-f096-4114-bd8c-46132067ce3c"
          },
          {
            "name": "Контракты пробеги, шт, по дате создания",
            "expression": "CALCULATE([Контракты пробеги, шт],USERELATIONSHIP('Calendar'[Date],Used_crmCarSale[DateCreated_CarSale]))",
            "formatString": "0",
            "lineageTag": "1ce7c0bc-61ae-4017-9d2c-cdcb05700d6c"
          },
          {
            "name": "Контракты → Сделки (пробеги)",
            "expression": "DIVIDE([Сделки пробеги, шт],[Контракты пробеги, шт],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c622d343-d302-4eb8-9123-6ad4f90dd3a3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4b026df5-1e08-4f0e-b2cd-438237f1143c"
          },
          {
            "name": "LinkedQueryName",
            "value": "Used_crmCarSale"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":18,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Used_crmCarSale/Changed Type.{date,0}\",\"Section1/Used_crmCarSale/Changed Type.{AtomId,1}\",\"Section1/Used_crmCarSale/Changed Type.{AtomdIdBeforeReplace,2}\",\"Section1/Used_crmCarSale/Changed Type.{DateCreated_CarSale,3}\",\"Section1/Used_crmCarSale/Changed Type.{dateEvent,4}\",\"Section1/Used_crmCarSale/Changed Type.{Make,5}\",\"Section1/Used_crmCarSale/Changed Type.{Site,6}\",\"Section1/Used_crmCarSale/Changed Type.{штуки,7}\",\"Section1/Used_crmCarSale/Changed Type.{Контракты_шт,8}\",\"Section1/Used_crmCarSale/Changed Type.{Контракты_сумма_₽,9}\",\"Section1/Used_crmCarSale/Changed Type.{Сделки_шт,10}\",\"Section1/Used_crmCarSale/Changed Type.{Сделки_сумма_₽,11}\",\"Section1/Used_crmCarSale/Changed Type.{Архив предложений_шт,12}\",\"Section1/Used_crmCarSale/Changed Type.{Архив предложений_₽,13}\",\"Section1/Used_crmCarSale/Source.{Открытая_шт,14}\",\"Section1/Used_crmCarSale/Source.{Открытая_₽,15}\",\"Section1/Used_crmCarSale/Source.{Несостоявшаяся_шт,16}\",\"Section1/Used_crmCarSale/Source.{Несостоявшаяся_₽,17}\"],\"ColumnCount\":18,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Used_crmCarSale/Changed Type.{date,0}\",\"Section1/Used_crmCarSale/Changed Type.{AtomId,1}\",\"Section1/Used_crmCarSale/Changed Type.{AtomdIdBeforeReplace,2}\",\"Section1/Used_crmCarSale/Changed Type.{DateCreated_CarSale,3}\",\"Section1/Used_crmCarSale/Changed Type.{dateEvent,4}\",\"Section1/Used_crmCarSale/Changed Type.{Make,5}\",\"Section1/Used_crmCarSale/Changed Type.{Site,6}\",\"Section1/Used_crmCarSale/Changed Type.{штуки,7}\",\"Section1/Used_crmCarSale/Changed Type.{Контракты_шт,8}\",\"Section1/Used_crmCarSale/Changed Type.{Контракты_сумма_₽,9}\",\"Section1/Used_crmCarSale/Changed Type.{Сделки_шт,10}\",\"Section1/Used_crmCarSale/Changed Type.{Сделки_сумма_₽,11}\",\"Section1/Used_crmCarSale/Changed Type.{Архив предложений_шт,12}\",\"Section1/Used_crmCarSale/Changed Type.{Архив предложений_₽,13}\",\"Section1/Used_crmCarSale/Source.{Открытая_шт,14}\",\"Section1/Used_crmCarSale/Source.{Открытая_₽,15}\",\"Section1/Used_crmCarSale/Source.{Несостоявшаяся_шт,16}\",\"Section1/Used_crmCarSale/Source.{Несостоявшаяся_₽,17}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Used_crmTraffic",
        "lineageTag": "419e0c00-9a3e-45c7-8b53-a81843788d0c",
        "columns": [
          {
            "name": "AtomIdFinal",
            "dataType": "int64",
            "sourceColumn": "AtomIdFinal",
            "formatString": "0",
            "lineageTag": "46e9bb6a-9e4e-461e-accf-25233a6bb799",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateTraffic",
            "dataType": "dateTime",
            "sourceColumn": "DateTraffic",
            "formatString": "General Date",
            "lineageTag": "d6bc9c36-27b3-4191-8d9b-c7a39b573038",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateComagic",
            "dataType": "dateTime",
            "sourceColumn": "DateComagic",
            "formatString": "General Date",
            "lineageTag": "4b37e395-1f1c-453b-9f0d-02a215ff51d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HasComagicCall",
            "dataType": "string",
            "sourceColumn": "HasComagicCall",
            "lineageTag": "7c21c1ec-8ead-4836-b8c4-f2a8844ef4cc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "d5e87f22-ee53-41e1-afc9-66f9789e9f7b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "e076d6e4-6ca5-4976-bbc9-e6fc8e190d53",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClientTrafficType",
            "dataType": "string",
            "sourceColumn": "ClientTrafficType",
            "lineageTag": "4c323728-fd30-404a-8adf-03022c35ae38",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliSource",
            "dataType": "string",
            "sourceColumn": "PotCliSource",
            "lineageTag": "ae060ffe-34a8-41a0-bf3c-9a8f89532a2f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Трафик",
            "dataType": "int64",
            "sourceColumn": "Трафик",
            "formatString": "0",
            "lineageTag": "117ecc3f-719f-477e-ae9c-e2edbbef74ce",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "final date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK(Used_crmTraffic[DateComagic]),Used_crmTraffic[DateTraffic],Used_crmTraffic[DateComagic])",
            "formatString": "General Date",
            "lineageTag": "a1806d7f-6252-49ab-92d2-9e6af4940678",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "abcbf54a-1a0c-40e3-a8d4-0bbd0bec8dc0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Used_crmTraffic-d3f87e75-c691-482e-97ec-10ea233413b3",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[crmClientTrafficUsedCars]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"AtomIdFinal\", \"AtomIdFinal\"}, {\"DateTraffic\", \"DateTraffic\"}, {\"DateComagic\", \"DateComagic\"}, {\"Site\", \"Site\"}, {\"Make\", \"Make\"}, {\"ClientTrafficType\", \"ClientTrafficType\"}, {\"PotCliSource\", \"PotCliSource\"}, {\"Трафик\", \"Трафик\"}, {\"HasComagicCall\", \"HasComagicCall\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"AtomIdFinal\", Int64.Type}, {\"DateTraffic\", type datetime}, {\"DateComagic\", type datetime}, {\"Site\", type text}, {\"Make\", type text}, {\"ClientTrafficType\", type text}, {\"PotCliSource\", type text}, {\"Трафик\", Int64.Type}, {\"HasComagicCall\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "abe40c3d-aa8f-4d8a-b2e9-bf4cac282807"
          },
          {
            "name": "LinkedQueryName",
            "value": "Used_crmTraffic"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":9,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Used_crmTraffic/Changed Type.{AtomIdFinal,0}\",\"Section1/Used_crmTraffic/Changed Type.{DateTraffic,1}\",\"Section1/Used_crmTraffic/Changed Type.{DateComagic,2}\",\"Section1/Used_crmTraffic/Changed Type.{HasComagicCall,3}\",\"Section1/Used_crmTraffic/Changed Type.{Site,4}\",\"Section1/Used_crmTraffic/Changed Type.{Make,5}\",\"Section1/Used_crmTraffic/Changed Type.{ClientTrafficType,6}\",\"Section1/Used_crmTraffic/Changed Type.{PotCliSource,7}\",\"Section1/Used_crmTraffic/Changed Type.{Трафик,8}\"],\"ColumnCount\":9,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Used_crmTraffic/Changed Type.{AtomIdFinal,0}\",\"Section1/Used_crmTraffic/Changed Type.{DateTraffic,1}\",\"Section1/Used_crmTraffic/Changed Type.{DateComagic,2}\",\"Section1/Used_crmTraffic/Changed Type.{HasComagicCall,3}\",\"Section1/Used_crmTraffic/Changed Type.{Site,4}\",\"Section1/Used_crmTraffic/Changed Type.{Make,5}\",\"Section1/Used_crmTraffic/Changed Type.{ClientTrafficType,6}\",\"Section1/Used_crmTraffic/Changed Type.{PotCliSource,7}\",\"Section1/Used_crmTraffic/Changed Type.{Трафик,8}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "crmService",
        "lineageTag": "798a9f99-f7ae-421c-b125-d8602a40b1d2",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "e0e6f277-8dd8-415c-b221-e20c7d68108b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "2a7cae68-664b-4f4a-863e-498e0894aac8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Бренд МТ",
            "dataType": "string",
            "sourceColumn": "Бренд МТ",
            "lineageTag": "26b9a2d0-8eff-4f88-9747-65e8468e7921",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "667cf59c-c587-4d6e-89f1-23de02b48e58",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Цех",
            "dataType": "string",
            "sourceColumn": "Цех",
            "lineageTag": "39dce9ee-3799-4d28-9116-fe52f2dd71ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "72cc3925-e083-4999-99b1-56966a8253b6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Заказ наряды",
            "dataType": "int64",
            "sourceColumn": "Заказ наряды",
            "formatString": "0",
            "lineageTag": "8d930609-fd3f-43d6-9982-e3b65c616681",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Запчасти_шт",
            "dataType": "double",
            "sourceColumn": "Запчасти_шт",
            "lineageTag": "67f3c033-dda8-4e27-a8c3-771ce5cd768b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Запчасти_сумма",
            "dataType": "double",
            "sourceColumn": "Запчасти_сумма",
            "lineageTag": "82b0b7e0-d046-45e4-81da-367e25584bfe",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Работы_сумма",
            "dataType": "double",
            "sourceColumn": "Работы_сумма",
            "lineageTag": "64c1b03a-26d4-4d23-8ec0-63d075d76c1b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Прочее_сумма",
            "dataType": "double",
            "sourceColumn": "Прочее_сумма",
            "lineageTag": "cec20f66-fd23-4e53-b41c-77e72eefa6cd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Скидка_сумма",
            "dataType": "double",
            "sourceColumn": "Скидка_сумма",
            "lineageTag": "290b009d-bb50-4efb-aa1d-0c64ddf33f37",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Выручка_сумма",
            "dataType": "double",
            "sourceColumn": "Выручка_сумма",
            "lineageTag": "4dc93350-5b6b-484e-99a3-996243d8645c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Были Открыты",
            "dataType": "int64",
            "sourceColumn": "Были Открыты",
            "formatString": "0",
            "lineageTag": "32c3e030-5594-4ede-ba4f-2d79945c28a5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были закрыты",
            "dataType": "int64",
            "sourceColumn": "Были закрыты",
            "formatString": "0",
            "lineageTag": "a134f8d4-6104-4b71-915e-246e8c14bad4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были полностью оплачены",
            "dataType": "int64",
            "sourceColumn": "Были полностью оплачены",
            "formatString": "0",
            "lineageTag": "41c97187-224f-4f17-b945-3ac92f96f525",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были переведены в гарантийную проформу",
            "dataType": "int64",
            "sourceColumn": "Были переведены в гарантийную проформу",
            "formatString": "0",
            "lineageTag": "fddd79e3-4691-45a9-97e6-664cff923548",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Выручка ЗН, которые были полностью оплачены",
            "dataType": "double",
            "sourceColumn": "Выручка ЗН, которые были полностью оплачены",
            "lineageTag": "0fcda121-7c15-46ed-8018-6a0aad8a04f8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ЗН_с_назначенной_встречей",
            "dataType": "int64",
            "sourceColumn": "ЗН_с_назначенной_встречей",
            "formatString": "0",
            "lineageTag": "842335cd-74e9-4551-8f4f-28236587fa50",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сервисный_проход_с_назначенной_встречей",
            "dataType": "int64",
            "sourceColumn": "Сервисный_проход_с_назначенной_встречей",
            "formatString": "0",
            "lineageTag": "8aa51fe2-d7b9-445a-873d-655e77fe0569",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сервисный_проход",
            "dataType": "int64",
            "sourceColumn": "Сервисный_проход",
            "formatString": "0",
            "lineageTag": "ca5ecd98-f2b8-499b-b372-1ac5dac2930e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "8d52e965-1033-4c49-a0aa-82dfdbb7d47a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были полностью оплачены и закрыты",
            "dataType": "int64",
            "sourceColumn": "Были полностью оплачены и закрыты",
            "formatString": "0",
            "lineageTag": "48add0da-6a28-4c87-94f4-f1edd492d704",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были полностью оплачены и закрыты, выручка",
            "dataType": "double",
            "sourceColumn": "Были полностью оплачены и закрыты, выручка",
            "lineageTag": "101d654d-5ded-46d1-984c-8cca6b0d81ab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "WhenCreated",
            "dataType": "dateTime",
            "sourceColumn": "WhenCreated",
            "formatString": "General Date",
            "lineageTag": "95c2f9d5-e1d6-4efb-bb31-7797083a4f73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Были полностью оплачены и закрыты, с назначенной встречей",
            "dataType": "int64",
            "sourceColumn": "Были полностью оплачены и закрыты, с назначенной встречей",
            "formatString": "0",
            "lineageTag": "e9c14ff4-dbe3-47b6-8eb6-bf2a770aeb93",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Стоимость др.услуга",
            "dataType": "double",
            "sourceColumn": "Стоимость др.услуга",
            "lineageTag": "f8a335a3-1997-4dfc-ba1e-7a855994ec67",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Стоимость запчастей",
            "dataType": "double",
            "sourceColumn": "Стоимость запчастей",
            "lineageTag": "abd13420-5402-4d29-86af-51e423121afa",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Сумма в счёте",
            "dataType": "double",
            "sourceColumn": "Сумма в счёте",
            "lineageTag": "9ce8bfc7-7504-4036-a2e8-a803f5c678fb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmService-eae74f2d-9faf-4a1c-86d3-42af24f0a937",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[crmService]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Make\", \"Бренд МТ\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "ЗН",
            "expression": "sum(crmService[Заказ наряды])",
            "formatString": "#,0",
            "lineageTag": "d48a22fb-650e-42eb-a2a7-aa89d1487581"
          },
          {
            "name": "Тег «Сервис» → ЗН",
            "expression": "DIVIDE([ЗН],[Comagic Тэг «Сервис»])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "a1cf5de7-e920-4e8c-b88a-43bf3993c20a"
          },
          {
            "name": "Сервисный проход",
            "expression": "sum(crmService[Сервисный_проход])",
            "formatString": "#,0",
            "lineageTag": "5602a59e-e5be-4475-99e2-4d69545644af"
          },
          {
            "name": "Тег «Сервис» → сервисный проход",
            "expression": "DIVIDE([Сервисный проход],[Comagic Тэг «Сервис»])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "de232855-7803-48c6-af40-e49408b90f66"
          },
          {
            "name": "Сервисный проход с назначенной встречей",
            "expression": "sum(crmService[Сервисный_проход_с_назначенной_встречей])",
            "formatString": "#,0",
            "lineageTag": "5b1ccff6-2a48-42fa-8380-7ba997bd6f3c"
          },
          {
            "name": "ЗН, цена",
            "expression": "DIVIDE([Расход без НДС],[ЗН])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "1cfd0fd8-3ed2-45c0-ad16-8b24369c3b95",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН Были полностью оплачены",
            "expression": "sum(crmService[Были полностью оплачены])",
            "formatString": "#,0",
            "lineageTag": "485648aa-0833-40f8-94a2-b09401901a15"
          },
          {
            "name": "ЗН → Полностью оплачены",
            "expression": "DIVIDE([ЗН Были полностью оплачены],[ЗН])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "608fbf31-d071-4b07-a17a-4c6218ec4cd8"
          },
          {
            "name": "ЗН, выручка, полностью оплаченных",
            "expression": "SUM(crmService[Выручка ЗН, которые были полностью оплачены])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "7ca88420-f9ae-4b8e-a24b-7be7ab87504e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, полностью оплачены, цена",
            "expression": "DIVIDE([Расход без НДС],[ЗН Были полностью оплачены])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "b9f06385-7c81-4778-ab6f-1f7311d75c68",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, предложение, сумма",
            "expression": "sum(crmService[Выручка_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "8a251ca4-1837-43b3-b45d-df81114af4a7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сервисный проход → Сервисный проход с назначенной встречей",
            "expression": "DIVIDE([Сервисный проход с назначенной встречей],[Сервисный проход],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "210b8584-783b-4528-a9ce-c5f978350e32"
          },
          {
            "name": "Выручка, сумма",
            "expression": "SUM(crmService[Выручка_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "e8c63cfa-b607-4e60-9a76-6a71768f059e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Запчасти, сумма",
            "expression": "sum(crmService[Запчасти_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "8e2f8426-288e-48f2-9485-cab2fef01825",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Запчасти, шт",
            "expression": "SUM(crmService[Запчасти_шт])",
            "formatString": "#,0",
            "lineageTag": "038bfa66-cfa9-4148-b63f-2e9083bb2299"
          },
          {
            "name": "Прочее, сумма",
            "expression": "SUM(crmService[Прочее_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "8ec4a2d4-ebd2-48d0-bc6c-6eba7abc6aec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Работы, сумма",
            "expression": "SUM(crmService[Работы_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "dff2692e-384d-4c19-956b-ed98885cd2db",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Скидка, сумма",
            "expression": "SUM(crmService[Скидка_сумма])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "acdfd11a-c842-407d-90d5-02c5366e305d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, были полностью оплачены и закрыты",
            "expression": "SUM(crmService[Были полностью оплачены и закрыты])",
            "formatString": "#,0",
            "lineageTag": "3aa1705f-78c9-4708-8da8-aa1b5e54ef89"
          },
          {
            "name": "ЗН, с назначенной встречей",
            "expression": "sum(crmService[ЗН_с_назначенной_встречей])",
            "formatString": "#,0",
            "lineageTag": "c42a1ccc-c1bb-44b9-8ed2-cc9235e0977b"
          },
          {
            "name": "Тег «Сервис» → ЗН, с назначенной встречей",
            "expression": "DIVIDE([ЗН, с назначенной встречей],[Comagic Тэг «Сервис»],BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "76e503af-8c16-45fc-a2cf-c2a0d0b72dba"
          },
          {
            "name": "ЗН, с назначенной встречей, цена",
            "expression": "DIVIDE([Расход без НДС],[ЗН, с назначенной встречей],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "bec1e861-3c5f-4849-94d1-003680876a66",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, с назначенной встречей → ЗН, были полностью оплачены и закрыты",
            "expression": "DIVIDE([ЗН, были полностью оплачены и закрыты, с назначенной встречей],[ЗН, с назначенной встречей],BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "a5796293-74ff-43ae-a4a0-e37085af10be"
          },
          {
            "name": "ЗН, по дате создания",
            "expression": "CALCULATE(SUM(crmService[Заказ наряды]),USERELATIONSHIP(crmService[WhenCreated],'Calendar'[Date]))",
            "formatString": "#,0",
            "lineageTag": "89684b64-7b8f-4e11-9ff7-fd08a5e672cb"
          },
          {
            "name": "ЗН, были полностью оплачены и закрыты, цена",
            "expression": "DIVIDE([Расход без НДС],[ЗН, были полностью оплачены и закрыты],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "fe73ce08-923c-4163-bd52-18384a873290",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, были полностью оплачены и закрыты, выручка",
            "expression": "SUM(crmService[Были полностью оплачены и закрыты, выручка])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "559ff66e-2415-4221-b4d2-55a5634a26c4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН, были полностью оплачены и закрыты, с назначенной встречей",
            "expression": "SUM(crmService[Были полностью оплачены и закрыты, с назначенной встречей])",
            "formatString": "#,0",
            "lineageTag": "df2c2574-0625-4cd5-b586-612bf870b1da"
          },
          {
            "name": "ЗН, были полностью оплачены и закрыты, с назначенной встречей, цена",
            "expression": "DIVIDE([Расход без НДС],[ЗН, были полностью оплачены и закрыты, с назначенной встречей], BLANK()) ",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "10b028a5-8843-4259-81ce-5d62ff463d01",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ЗН → ЗН, были полностью оплачены и закрыты",
            "expression": "DIVIDE([ЗН, были полностью оплачены и закрыты],[ЗН],BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "24ce2b84-13bb-49d1-a514-54a1883e1909"
          },
          {
            "name": "Доход сервиса без НДС",
            "expression": "SUM(crmService[Сумма в счёте]) - SUM(crmService[Стоимость др.услуга]) - SUM(crmService[Стоимость запчастей])  ",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "80496ee2-20ad-46fa-8d9d-d32809beb5f7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Выручка сервиса, без НДС",
            "expression": "SUM(crmService[Сумма в счёте])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "91aec735-4b6d-4772-8013-7d3c80ab9638",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Себестоимость сервиса, без НДС",
            "expression": "SUM(crmService[Стоимость др.услуга]) + SUM(crmService[Стоимость запчастей])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "4fbeb81a-700b-49bd-af13-b606415ebb75",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Мера",
            "lineageTag": "83b890a9-f974-44bf-8336-6ee553c94c72",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "Маржа сервиса, %",
            "expression": "DIVIDE([Выручка сервиса, без НДС] - [Себестоимость сервиса, без НДС],[Выручка сервиса, без НДС])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e123a54e-e9f5-493f-87b5-3a4055067360"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ac04e2c7-31a3-489a-ba29-140a3663b697"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmService"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":21,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmService/Changed Type.{Date,0}\",\"Section1/crmService/Source.{AtomId,1}\",\"Section1/crmService/Source.{Make,2}\",\"Section1/crmService/Source.{Site,3}\",\"Section1/crmService/Source.{Цех,4}\",\"Section1/crmService/Source.{Status,5}\",\"Section1/crmService/Source.{Заказ наряды,6}\",\"Section1/crmService/Source.{Запчасти_шт,7}\",\"Section1/crmService/Source.{Запчасти_сумма,8}\",\"Section1/crmService/Source.{Работы_сумма,9}\",\"Section1/crmService/Source.{Прочее_сумма,10}\",\"Section1/crmService/Source.{Скидка_сумма,11}\",\"Section1/crmService/Source.{Выручка_сумма,12}\",\"Section1/crmService/Source.{Были Открыты,13}\",\"Section1/crmService/Source.{Были закрыты,14}\",\"Section1/crmService/Source.{Были полностью оплачены,15}\",\"Section1/crmService/Source.{Были переведены в гарантийную проформу,16}\",\"Section1/crmService/Source.{Выручка ЗН, которые были полностью оплачены,17}\",\"Section1/crmService/Source.{ЗН_с_назначенной_встречей,18}\",\"Section1/crmService/Source.{Сервисный_проход_с_назначенной_встречей,19}\",\"Section1/crmService/Source.{Сервисный_проход,20}\"],\"ColumnCount\":21,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmService/Changed Type.{Date,0}\",\"Section1/crmService/Source.{AtomId,1}\",\"Section1/crmService/Source.{Make,2}\",\"Section1/crmService/Source.{Site,3}\",\"Section1/crmService/Source.{Цех,4}\",\"Section1/crmService/Source.{Status,5}\",\"Section1/crmService/Source.{Заказ наряды,6}\",\"Section1/crmService/Source.{Запчасти_шт,7}\",\"Section1/crmService/Source.{Запчасти_сумма,8}\",\"Section1/crmService/Source.{Работы_сумма,9}\",\"Section1/crmService/Source.{Прочее_сумма,10}\",\"Section1/crmService/Source.{Скидка_сумма,11}\",\"Section1/crmService/Source.{Выручка_сумма,12}\",\"Section1/crmService/Source.{Были Открыты,13}\",\"Section1/crmService/Source.{Были закрыты,14}\",\"Section1/crmService/Source.{Были полностью оплачены,15}\",\"Section1/crmService/Source.{Были переведены в гарантийную проформу,16}\",\"Section1/crmService/Source.{Выручка ЗН, которые были полностью оплачены,17}\",\"Section1/crmService/Source.{ЗН_с_назначенной_встречей,18}\",\"Section1/crmService/Source.{Сервисный_проход_с_назначенной_встречей,19}\",\"Section1/crmService/Source.{Сервисный_проход,20}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmServiceProhody",
        "lineageTag": "a261d3f5-a744-48a3-9b22-90926513f5aa",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "24241d1c-20da-4031-b2a6-8ccfa691e854",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "e1a10490-ae54-49de-8093-666859b04dfd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "eefa15e4-c25a-4b23-98ba-e9147e6e9094",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "a45a52fa-426b-4381-814d-edda5791e583",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Цех",
            "dataType": "string",
            "sourceColumn": "Цех",
            "lineageTag": "6c4d039f-96ef-46e5-ac55-16f19dfb6e51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "СП_с_ЗН_Были_Открыты",
            "dataType": "int64",
            "sourceColumn": "СП_с_ЗН_Были_Открыты",
            "formatString": "0",
            "lineageTag": "c27a8e78-d075-4634-908c-9e831aa411b5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "СП_с_ЗН_Были_Закрыты",
            "dataType": "int64",
            "sourceColumn": "СП_с_ЗН_Были_Закрыты",
            "formatString": "0",
            "lineageTag": "36ffdca6-9748-41df-8c93-d9e057906134",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "СП_с_ЗН_Были_Полностью_опл",
            "dataType": "int64",
            "sourceColumn": "СП_с_ЗН_Были_Полностью_опл",
            "formatString": "0",
            "lineageTag": "b3825958-ef6f-4309-b591-eef1c41c7747",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "СП_с_ЗН_Закрыты_и_ПолнОпл",
            "dataType": "int64",
            "sourceColumn": "СП_с_ЗН_Закрыты_и_ПолнОпл",
            "formatString": "0",
            "lineageTag": "bc1d2f4f-cf2c-4096-854a-7d4e5ac048e0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Выручка полностью оплаченных ЗН",
            "dataType": "double",
            "sourceColumn": "Выручка полностью оплаченных ЗН",
            "lineageTag": "80e1a1a9-492d-4b96-b1ef-4b1f93ff4e78",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Сервисный_проход_с_назначенной_встречей",
            "dataType": "int64",
            "sourceColumn": "Сервисный_проход_с_назначенной_встречей",
            "formatString": "0",
            "lineageTag": "3b6d44b1-f796-4897-98f6-6c1b2b803800",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Заказ_наряды",
            "dataType": "int64",
            "sourceColumn": "Заказ_наряды",
            "formatString": "0",
            "lineageTag": "2c3164f2-c3e9-4cc1-84b4-3d03dadffbed",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Запчасти_шт",
            "dataType": "double",
            "sourceColumn": "Запчасти_шт",
            "lineageTag": "52f60390-6554-4144-a281-fa078dd405d7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Запчасти_сумма",
            "dataType": "double",
            "sourceColumn": "Запчасти_сумма",
            "lineageTag": "195c21c9-ab3e-4c62-9ea2-3b2156109ac4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Работы_сумма",
            "dataType": "double",
            "sourceColumn": "Работы_сумма",
            "lineageTag": "007d0654-da7d-468c-8eb5-1261be585888",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Прочее_сумма",
            "dataType": "double",
            "sourceColumn": "Прочее_сумма",
            "lineageTag": "b833c836-55b6-4c5d-8b82-0b66e000c67f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Скидка_сумма",
            "dataType": "double",
            "sourceColumn": "Скидка_сумма",
            "lineageTag": "5763c1b5-cd09-4d3c-a974-bb0e1d5c1d5c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Cумма_предложение",
            "dataType": "double",
            "sourceColumn": "Cумма_предложение",
            "lineageTag": "bdb4416c-e51b-4e60-9588-5078024e179b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Сервисные_проходы",
            "dataType": "int64",
            "sourceColumn": "Сервисные_проходы",
            "formatString": "0",
            "lineageTag": "27658573-abb3-4958-ac4c-336a55105bd2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "35eed7b9-131f-4264-a36c-a5877e1fbb00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WhenCreated",
            "dataType": "dateTime",
            "sourceColumn": "WhenCreated",
            "formatString": "General Date",
            "lineageTag": "0921c6af-116f-4338-afd5-fc10dc7aabfa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Выручка полностью оплаченных и закрытых ЗН",
            "dataType": "double",
            "sourceColumn": "Выручка полностью оплаченных и закрытых ЗН",
            "lineageTag": "ade7b6b9-afc2-4a2d-933d-bd57e10dbc8f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmServiceProhody-a552ddfd-c38c-4ab5-8ebb-84d8f6f7a4ce",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[crmServiceProhody]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_Сервисный проход с назначенной встречей",
            "expression": "sum(crmServiceProhody[Сервисный_проход_с_назначенной_встречей])",
            "formatString": "#,0",
            "lineageTag": "bcf3173c-533f-481f-a523-5206716b6461"
          },
          {
            "name": "_Сервисный проход",
            "expression": "SUM(crmServiceProhody[Сервисные_проходы])",
            "formatString": "#,0",
            "lineageTag": "53bdc61f-6023-45af-a612-eb370565c5d9"
          },
          {
            "name": "Сервисный проход, был закрыт",
            "expression": "SUM(crmServiceProhody[СП_с_ЗН_Были_Закрыты])",
            "formatString": "#,0",
            "lineageTag": "1d6467d9-c5c8-423e-92c5-0d82393f0790"
          },
          {
            "name": "Сервисный проход, с назначенной встречей → Сервисный проход, был закрыт",
            "expression": "DIVIDE([Сервисный проход, был закрыт],[Сервисный проход с назначенной встречей],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0e70df99-11f1-4ec1-8c55-b985d3d831bb"
          },
          {
            "name": "Сервисный проход, полностью оплачен",
            "expression": "SUM(crmServiceProhody[СП_с_ЗН_Были_Полностью_опл])",
            "formatString": "#,0",
            "lineageTag": "f27acb42-afa9-43e6-8349-0484c818d179"
          },
          {
            "name": "Сервисный проход → Сервисный проход, полностью оплачен",
            "expression": "DIVIDE([Сервисный проход, полностью оплачен],[Сервисный проход],BLANK())",
            "lineageTag": "34eba503-525e-4260-9a76-f06f468f9f60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Сервисный проход →  Сервисный проход, был закрыт",
            "expression": "DIVIDE([Сервисный проход, был закрыт],[_Сервисный проход],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "39df30b2-4fa7-4d8d-80ff-1c018ad3cbfa"
          },
          {
            "name": "Сервисный проход, закрыт и полностью оплачен",
            "expression": "SUM(crmServiceProhody[СП_с_ЗН_Закрыты_и_ПолнОпл])",
            "formatString": "#,0",
            "lineageTag": "1e34d75c-5e77-4130-8ca0-e005aaa7f994"
          },
          {
            "name": "Сервисный проход, закрыт и полностью оплачен, цена",
            "expression": "DIVIDE([Расход без НДС],[Сервисный проход, закрыт и полностью оплачен],BLANK())",
            "formatString": "#,0.0\\ \"₽\";-#,0.0\\ \"₽\";#,0.0\\ \"₽\"",
            "lineageTag": "3b67fb1b-13be-4d0d-b758-06e30c7efc02",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сервисный проход → Сервисный проход, закрыт и полностью оплачен",
            "expression": "DIVIDE([Сервисный проход, закрыт и полностью оплачен],[_Сервисный проход],BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1a2e06c0-4f3f-4d0a-a77c-63ba3c735531"
          },
          {
            "name": "_Сервисный проход → Сервисный проход, с назначенной встречей",
            "expression": "DIVIDE([_Сервисный проход с назначенной встречей],[_Сервисный проход],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3f425fb6-d4c3-4b86-9e81-f143f3dcfbed"
          },
          {
            "name": "Тег «Сервис» → СП, с назначенной встречей",
            "expression": "DIVIDE([Сервисный проход с назначенной встречей],[Comagic Тэг «Сервис»],BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "7bd16a3e-ce48-45f4-89e9-8aa57984e622"
          },
          {
            "name": "Сервисный проход с назначенной встречей, цена",
            "expression": "DIVIDE([Расход без НДС],[Сервисный проход с назначенной встречей],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "6cfb026d-2feb-4007-8e4d-5c48a4e28b2d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сервисный проход с назначенной встречей → Сервисный проход закрыт и полностью оплачен",
            "expression": "DIVIDE([Сервисный проход, закрыт и полностью оплачен],[Сервисный проход с назначенной встречей], BLANK())",
            "formatString": "0%;-0%;0%",
            "lineageTag": "328b223d-6d0c-4b17-9d05-477555dbc09d"
          },
          {
            "name": "Сервисные проходы, по дате создания",
            "expression": "CALCULATE(SUM(crmServiceProhody[Сервисные_проходы]),USERELATIONSHIP('Calendar'[Date],crmServiceProhody[WhenCreated]))",
            "formatString": "#,0",
            "lineageTag": "c5601994-1930-494e-b0df-383f7fbd6209"
          },
          {
            "name": "Сервисный проход, цена",
            "expression": "DIVIDE([Расход без НДС],[_Сервисный проход],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "30bce62b-1dc6-4242-a827-0a7f0d00b58a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Сервисный проход закрыт и полностью оплачен, выручка",
            "expression": "sum(crmServiceProhody[Выручка полностью оплаченных и закрытых ЗН])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "0ea99fe7-97d5-4302-a1c9-862400aeee91",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8331666f-3730-43ab-874c-3aee4325cfea"
          },
          {
            "name": "LinkedQueryName",
            "value": "crmServiceProhody"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":19,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/crmServiceProhody/Source.{AtomId,0}\",\"Section1/crmServiceProhody/Changed Type.{Date,1}\",\"Section1/crmServiceProhody/Source.{Make,2}\",\"Section1/crmServiceProhody/Source.{Site,3}\",\"Section1/crmServiceProhody/Source.{Цех,4}\",\"Section1/crmServiceProhody/Source.{Сервисные_проходы,5}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Открыты,6}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Закрыты,7}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Полностью_опл,8}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Закрыты_и_ПолнОпл,9}\",\"Section1/crmServiceProhody/Source.{Выручка полностью оплаченных ЗН,10}\",\"Section1/crmServiceProhody/Source.{Сервисный_проход_с_назначенной_встречей,11}\",\"Section1/crmServiceProhody/Source.{Заказ_наряды,12}\",\"Section1/crmServiceProhody/Source.{Запчасти_шт,13}\",\"Section1/crmServiceProhody/Source.{Запчасти_сумма,14}\",\"Section1/crmServiceProhody/Source.{Работы_сумма,15}\",\"Section1/crmServiceProhody/Source.{Прочее_сумма,16}\",\"Section1/crmServiceProhody/Source.{Скидка_сумма,17}\",\"Section1/crmServiceProhody/Source.{Cумма_предложение,18}\"],\"ColumnCount\":19,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/crmServiceProhody/Source.{AtomId,0}\",\"Section1/crmServiceProhody/Changed Type.{Date,1}\",\"Section1/crmServiceProhody/Source.{Make,2}\",\"Section1/crmServiceProhody/Source.{Site,3}\",\"Section1/crmServiceProhody/Source.{Цех,4}\",\"Section1/crmServiceProhody/Source.{Сервисные_проходы,5}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Открыты,6}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Закрыты,7}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Были_Полностью_опл,8}\",\"Section1/crmServiceProhody/Source.{СП_с_ЗН_Закрыты_и_ПолнОпл,9}\",\"Section1/crmServiceProhody/Source.{Выручка полностью оплаченных ЗН,10}\",\"Section1/crmServiceProhody/Source.{Сервисный_проход_с_назначенной_встречей,11}\",\"Section1/crmServiceProhody/Source.{Заказ_наряды,12}\",\"Section1/crmServiceProhody/Source.{Запчасти_шт,13}\",\"Section1/crmServiceProhody/Source.{Запчасти_сумма,14}\",\"Section1/crmServiceProhody/Source.{Работы_сумма,15}\",\"Section1/crmServiceProhody/Source.{Прочее_сумма,16}\",\"Section1/crmServiceProhody/Source.{Скидка_сумма,17}\",\"Section1/crmServiceProhody/Source.{Cумма_предложение,18}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "Shop",
        "lineageTag": "6080c969-c23a-4ec7-9f5a-6b220c4fa527",
        "columns": [
          {
            "name": "Цех",
            "dataType": "string",
            "sourceColumn": "Цех",
            "lineageTag": "8255755c-f100-4e1c-a841-be823fa01f8b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shop-d7c2bfe4-e433-43d7-b71a-c966be1b5d3e",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = List.Distinct(crmService[Цех]),",
                "    #\"Преобразовано в таблицу\" = Table.FromList(Источник, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Преобразовано в таблицу\",{{\"Column1\", \"Цех\"}}),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Переименованные столбцы\",{{\"Цех\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8cb7987a-b605-410e-9f2e-9e71bac83ae4"
          },
          {
            "name": "LinkedQueryName",
            "value": "Shop"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Shop/Измененный тип.{Цех,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Shop/Измененный тип.{Цех,0}\"],\"RelationshipInfo\":[]}"
          }
        ]
      },
      {
        "name": "Cohotrs",
        "lineageTag": "30640e96-119d-4ba0-b326-f890ab85a25d",
        "columns": [
          {
            "name": "date_event",
            "dataType": "dateTime",
            "sourceColumn": "date_event",
            "formatString": "Long Date",
            "lineageTag": "41144b69-f544-4adf-84c5-8fa0113cd8be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "date_start",
            "dataType": "dateTime",
            "sourceColumn": "date_start",
            "formatString": "Long Date",
            "lineageTag": "bd94a15e-12d6-476a-82c5-19ad309bbebb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "штуки",
            "dataType": "int64",
            "sourceColumn": "штуки",
            "formatString": "0",
            "lineageTag": "f298b350-3152-4c52-8f56-f876417bb695",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "когорта",
            "dataType": "string",
            "sourceColumn": "когорта",
            "lineageTag": "27601d22-258d-4959-b581-1557a440109a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Comagic нашелся",
            "dataType": "string",
            "sourceColumn": "Comagic нашелся",
            "lineageTag": "549d354a-ae75-4ba8-b1cc-2043abe9d173",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "08c8785c-6412-4acb-819c-a832187b4e7a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "WEEKDiff",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IFERROR(DATEDIFF([date_start],[date_event],WEEK),-1)",
            "formatString": "0",
            "lineageTag": "a8aa5dc6-84aa-440b-850a-2020a8017b05",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Недели_ когорты",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(FIRSTNONBLANK('Calendar'[Недели_колон],1),FILTER('Calendar','Calendar'[Date]=Cohotrs[date_event]))",
            "sortByColumn": "week_cohorts",
            "lineageTag": "059a971c-699a-4e82-a121-9454b222ac95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "week_cohorts",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "CALCULATE(FIRSTNONBLANK('Calendar'[Недели],1),FILTER('Calendar','Calendar'[Date]=Cohotrs[date_event]))",
            "lineageTag": "3feb3d97-c45c-40b1-af20-17495cbc54a8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wkDiff",
            "dataType": "int64",
            "sourceColumn": "wkDiff",
            "formatString": "0",
            "lineageTag": "3077a713-fe33-4e73-8ebc-98edf02da291",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Cohotrs-a3b217ac-3ab1-4fed-8389-c83a4e179d7b",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT    *   FROM pivotparts.[Cohotrs]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"date_event\", type date}, {\"date_start\", type date}}),",
                "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Changed Type\", \"wkDiff\", each let ",
                "wkdiff = (Duration.Days(",
                "Date.StartOfWeek([date_event], Day.Monday) -",
                "Date.StartOfWeek([date_start], Day.Monday)",
                "))/7",
                "in if wkdiff = null then -1 else wkdiff, Int64.Type)",
                "in",
                "    #\"Добавлен пользовательский объект\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ef206c9f-1416-4045-bb18-b81567ebe67f"
          },
          {
            "name": "LinkedQueryName",
            "value": "Cohotrs"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":6,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Cohotrs/Changed Type.{date_event,0}\",\"Section1/Cohotrs/Changed Type.{date_start,1}\",\"Section1/Cohotrs/Source.{штуки,2}\",\"Section1/Cohotrs/Source.{когорта,3}\",\"Section1/Cohotrs/Source.{Comagic нашелся,4}\",\"Section1/Cohotrs/Source.{AtomId,5}\"],\"ColumnCount\":6,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Cohotrs/Changed Type.{date_event,0}\",\"Section1/Cohotrs/Changed Type.{date_start,1}\",\"Section1/Cohotrs/Source.{штуки,2}\",\"Section1/Cohotrs/Source.{когорта,3}\",\"Section1/Cohotrs/Source.{Comagic нашелся,4}\",\"Section1/Cohotrs/Source.{AtomId,5}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "TagOpTypes",
        "lineageTag": "474f8738-6cd2-4f5d-856c-275a14f768e3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Name]",
            "lineageTag": "a6745e06-5f08-4036-b6c1-4265a699487b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TagOpTypes-1407245b-2875-415e-a48e-b6e81c0a3d4a",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"Name\",STRING,{{\"ОП\"},{\"ОП Только автоматические\"}})"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8f465a0357fa40daa7c64ac744e72580"
          }
        ]
      },
      {
        "name": "Measure List 1",
        "lineageTag": "6b4d91a9-dd34-4cf1-981e-740df458e5de",
        "columns": [
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Id",
            "lineageTag": "e4e35ed1-acdb-465a-a65d-0633e7b7c339",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "0deaf7f8-3ebb-4f3b-bf0f-47118f609ba9",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measure List 1-e8bc078b-9932-4b47-9283-96b48275bf87",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #table(",
                "        {\"Name\",\"Id\"},",
                "        {",
                "            {\"Расход\",1},",
                "            {\"Клики\",2},",
                "            {\"Звонки\",3},",
                "            {\"Тэг «ОП»\",4},",
                "            {\"Стоимость тэга «ОП»\",5},            ",
                "            {\"Трафик\",6},",
                "            {\"Стоимость трафика\",7},            ",
                "            {\"РКП\",8},",
                "            {\"Стоиомость РКП\",9},            ",
                "            {\"РКП Эффективная\",10},",
                "            {\"Стоимость РКП Эффективная\",11},",
                "            {\"Контракты\",12},                        ",
                "            {\"Стоиомсть контракта\",13},",
                "            {\"Сделки\",14},            ",
                "            {\"Стоимость сделки\",15}",
                "",
                "        }",
                "",
                "    ),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Name\", type text}, {\"Id\", Int64.Type}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Выбранная мера 1",
            "expression": [
              "SWITCH(",
              "SELECTEDVALUE('Measure List 1'[Id],BLANK()),",
              "1,          [Расход без НДС],",
              "2,          [Клики],",
              "3,          [Comagic звонки все],",
              "4,          [Comagic Тэг «ОП»],",
              "5,          [Тег ОП цена],",
              "6,          [Трафик новый авто, без замены AtomId],",
              "7,          DIVIDE([Расход без НДС],[Трафик новый авто, без замены AtomId]),",
              "8,          [РКП, без замены AtomId],",
              "9,          DIVIDE([Расход без НДС],[РКП, без замены AtomId]),",
              "10,         [РКП Эффективная, без замены AtomId],",
              "11,         DIVIDE([Расход без НДС],[РКП Эффективная, без замены AtomId]),         ",
              "12,         [Контракты, шт, без замены AtomId],",
              "13,         DIVIDE([Расход без НДС],[Контракты, шт, без замены AtomId]),",
              "14,         [Сделки, шт, без замены AtomId],",
              "15,         DIVIDE([Расход без НДС],[Сделки, шт, без замены AtomId])",
              ")"
            ],
            "lineageTag": "3f00ef4a-23ef-41eb-b25c-7d46bf2feba4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "Measure List 2",
        "lineageTag": "6c750ee1-b7b9-4e18-a422-e554cd10d962",
        "columns": [
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Id",
            "lineageTag": "a8fcba39-10e4-4f55-b364-8489031f41d4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "4b0843bc-d71c-4923-9745-ecd3f263e4b5",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measure List 2-92d6cac7-6554-4528-bb81-e296d3061828",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #\"Measure List 1\"",
                "in",
                "    Источник"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Выбранная мера 2",
            "expression": [
              "SWITCH(",
              "SELECTEDVALUE('Measure List 2'[Id],BLANK()),",
              "1,          [Расход без НДС],",
              "2,          [Клики],",
              "3,          [Comagic звонки все],",
              "4,          [Comagic Тэг «ОП»],",
              "5,          [Тег ОП цена],",
              "6,          [Трафик новый авто, без замены AtomId],",
              "7,          DIVIDE([Расход без НДС],[Трафик новый авто, без замены AtomId]),",
              "8,          [РКП, без замены AtomId],",
              "9,          DIVIDE([Расход без НДС],[РКП, без замены AtomId]),",
              "10,         [РКП Эффективная, без замены AtomId],",
              "11,         DIVIDE([Расход без НДС],[РКП Эффективная, без замены AtomId]),         ",
              "12,         [Контракты, шт, без замены AtomId],",
              "13,         DIVIDE([Расход без НДС],[Контракты, шт, без замены AtomId]),",
              "14,         [Сделки, шт, без замены AtomId],",
              "15,         DIVIDE([Расход без НДС],[Сделки, шт, без замены AtomId])",
              ")"
            ],
            "lineageTag": "7ab46e9a-e37c-4ca4-b9e3-fcd7bec92c4c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dimensions",
        "lineageTag": "bacd56ac-9650-4761-9e67-570e47ed949f",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "c6b6bbc4-9ed3-492f-9d73-726677c22f9f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "55472283-3d8b-4f1d-96d0-6d614818b24e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dimensions-e17f8141-1187-4c7f-b115-5d197201a47d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #table (",
                "        {\"Id\",\"Name\"},",
                "        {",
                "            {1,\"Канал\"},",
                "            {2,\"Группа источников\"},",
                "            {3,\"Источник\"},",
                "            {4,\"Кампания\"},",
                "            {5,\"Бренд авто\"}",
                "",
                "        }",
                "    ),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Id\", Int64.Type}, {\"Name\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AtomWithExtensionsDim",
        "lineageTag": "91c89cbf-637f-46dd-9e8c-345a12b48ff7",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "d9445b45-2d83-48de-beeb-a4b0544a12e9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Dimension",
            "dataType": "string",
            "sourceColumn": "Dimension",
            "lineageTag": "5b33fed5-a4f1-43bc-984a-276998209cff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DimensionColumn",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(FIRSTNONBLANK('Dimensions'[Name],1),\"Группа источников\",RELATED(AtomsWithExtensions[Группа источников]),",
              "                                                             \"Канал\",RELATED(AtomsWithExtensions[Канал]),",
              "                                                             \"Бренд Авто\", RELATED(AtomsWithExtensions[Бренд авто]),",
              "                                                             \"Источник\", RELATED(AtomsWithExtensions[Источник]),",
              "                                                             \"Кампания\", RELATED(AtomsWithExtensions[Кампания])",
              ")"
            ],
            "lineageTag": "ecd85a66-77c1-47f6-8a3c-494b69ae421b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AtomWithExtensionsDim-6e7ad9dd-07a3-4a87-b72a-66a4971a7019",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.SelectColumns(AtomsWithExtensions,{\"AtomId\"}),",
                "    AtomsWithExtensionsSG = Table.AddColumn(Source, \"Dimension\", each \"Группа источников\"),",
                "    AtomsWithExtensionsGSG = Table.AddColumn(Source, \"Dimension\", each \"Канал\"),",
                "    AtomsWithExtensionsBrand = Table.AddColumn(Source, \"Dimension\", each \"Бренд авто\"),",
                "    AtomsWithExtensionsCampaign = Table.AddColumn(Source, \"Dimension\", each \"Кампания\"), ",
                "    AtomsWithExtensionsSource = Table.AddColumn(Source, \"Dimension\", each \"Источник\"), ",
                "    AtomWithExtensionsDim = Table.Combine({AtomsWithExtensionsSG, AtomsWithExtensionsGSG,AtomsWithExtensionsBrand,AtomsWithExtensionsCampaign,AtomsWithExtensionsSource}),",
                "     #\"Измененный тип\" = Table.TransformColumnTypes(AtomWithExtensionsDim,{{\"Dimension\", type text}})  ",
                "in",
                "   #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "CamparePeriodType",
        "lineageTag": "53c48cb2-1c91-4677-b16a-cf0652ca7d11",
        "columns": [
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "b184b247-fd19-40d9-b1b8-acceebcbeda8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "cf3b27b9-5e31-455e-af0d-896f13bb518f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name2",
            "dataType": "string",
            "sourceColumn": "Name2",
            "lineageTag": "6d9d585b-fdb9-4ecb-ad78-ad53e4173a89",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CamparePeriodType-c5f1eb81-d7d8-4d9d-849a-2da6052ce376",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #table ({\"Name\",\"Id\",\"Name2\"},",
                "    {",
                "        {\"Собственный\",1,\" \"},",
                "        {\"Предыдущий\",3,\"Предыдущий\"},",
                "        {\"Неделя\",2,\"Неделя\"}        ",
                "    }),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Name\", type text}, {\"Name2\", type text}, {\"Id\", Int64.Type}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "SelectedCamparePeriodType",
            "expression": "MAX(CamparePeriodType[Id])",
            "formatString": "0",
            "lineageTag": "ce42cc19-c85f-46d1-abc0-29a8bd7eca7a"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Calendar (3)",
        "lineageTag": "3dad0460-647c-4e88-8651-1a2a6f525cec",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "f5210a5d-811b-4308-bd3d-8fd8d7be76a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Week",
            "dataType": "string",
            "sourceColumn": "Week",
            "lineageTag": "6f4f3ea0-2f0b-408e-90a0-9a5df564dd5f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calendar (3)-abc231b9-0d6e-41c8-b1b1-6fc88fb40951",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Calendar,",
                "    #\"Строки с примененным фильтром\" = Table.SelectRows(Источник, each [Date] < Date.From(DateTime.LocalNow()))",
                "in",
                "    #\"Строки с примененным фильтром\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "MidDate",
            "expression": "MIn('Calendar (3)'[Date])",
            "formatString": "General Date",
            "lineageTag": "a0cfc15a-2e61-43e6-800b-e0792ba8aa61"
          },
          {
            "name": "MaxDate",
            "expression": "Max('Calendar (3)'[Date])",
            "formatString": "General Date",
            "lineageTag": "7e569e09-5a88-4bb9-9793-6e2dc7efee57"
          },
          {
            "name": "W1",
            "expression": "FIRSTNONBLANK('Calendar (3)'[Week],'Calendar (3)'[Week])",
            "lineageTag": "21cbf425-40ea-473f-abfc-47fff1e35b73"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "CalendarDim",
        "lineageTag": "bb9f0981-4e35-48be-803c-fde66b8fc5bf",
        "columns": [
          {
            "name": "Dimension",
            "dataType": "string",
            "sourceColumn": "Dimension",
            "lineageTag": "e0f06ba0-2404-461c-ab73-1fc3865f74bc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "5b2168bb-ee2e-4c5c-8887-1d7e882e7ed3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DimensionColumn",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(FIRSTNONBLANK('CalendarDimensions'[Name],1),\"Год\",FORMAT(RELATED('Calendar'[Year]),\"####\"),",
              "                                                             \"Месяц\",RELATED('Calendar'[YYYY-MM]),",
              "                                                             \"Неделя\", RELATED('Calendar'[Недели]),",
              "                                                             \"День\", FORMAT( RELATED('Calendar'[Date]),\"YYYY-MM-DD\"))"
            ],
            "lineageTag": "efeb31a4-dc3e-4e53-b124-174116b99093",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalendarDim-63bb2ce7-bc02-4337-ac72-3129fa1a52ad",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.SelectColumns(Calendar,{\"Date\"}),",
                "    CalendarExtensionYear = Table.AddColumn(Source, \"Dimension\", each \"Год\"),",
                "    CalendarExtensionMonth = Table.AddColumn(Source, \"Dimension\", each \"Месяц\"),",
                "    CalendarExtensionWeek = Table.AddColumn(Source, \"Dimension\", each \"Неделя\"),",
                "    CalendarExtensionDay = Table.AddColumn(Source, \"Dimension\", each \"День\"),    ",
                "    CalendarExtensionDim = Table.Combine({CalendarExtensionYear, CalendarExtensionMonth,CalendarExtensionWeek,CalendarExtensionDay}),",
                "     #\"Измененный тип\" = Table.TransformColumnTypes(CalendarExtensionDim,{{\"Dimension\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "CalendarDimensions",
        "lineageTag": "9488530b-d6f9-4a61-8b0e-aab8dcceaf86",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "fd9a1ecf-0d61-409c-82a9-a00b7e7b7aba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "fc6e7b5c-6f20-4329-a897-9724975bddb8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalendarDimensions-ea0cff23-c960-40fb-a9d7-e874f081bf9b",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #table (",
                "        {\"Id\",\"Name\"},",
                "        {",
                "            {1,\"Год\"},",
                "            {2,\"Месяц\"},",
                "            {3,\"Неделя\"},",
                "            {4,\"День\"}",
                "",
                "        }",
                "    ),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Id\", Int64.Type}, {\"Name\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "AttributionsNew",
        "lineageTag": "4ac94c4e-86bf-4fc8-a2ad-c8521b4fff8d",
        "columns": [
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "f81df150-fa5f-4be8-b633-8a75bb6a1b6a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Атрибуция",
            "dataType": "string",
            "sourceColumn": "Атрибуция",
            "lineageTag": "fa1da423-d07a-4b05-85ee-1dd383b6c7cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "AttributionsNew-fc518d22-0f51-47a2-a398-1e14bf66b71f",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Sql.Database(server, database, [Query=\"select * from [pivotparts].[Attributionsnew]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)])",
                "in",
                "    Источник"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "crmTrafficAtomIdBeforeReplace",
        "lineageTag": "3c87dd57-3519-4885-a43f-81c5ad80dda3",
        "columns": [
          {
            "name": "AtomIdFinal",
            "dataType": "int64",
            "sourceColumn": "AtomIdFinal",
            "formatString": "0",
            "lineageTag": "10a7b995-ee59-47eb-bc04-3a2aacf1b45a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateTraffic",
            "dataType": "dateTime",
            "sourceColumn": "DateTraffic",
            "formatString": "General Date",
            "lineageTag": "0bb3dae8-84b1-497c-8d41-e5d606f54356",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateComagic",
            "dataType": "dateTime",
            "sourceColumn": "DateComagic",
            "formatString": "General Date",
            "lineageTag": "1fddef1b-b1a4-43fb-9ca3-7ca594eb12c7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HasComagicCall",
            "dataType": "string",
            "sourceColumn": "HasComagicCall",
            "lineageTag": "14f9a23a-4b73-472e-8958-7c4177839e9b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "05f977e1-6c43-4759-8875-cf77bc0d3099",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "e3a6d83b-c6b6-47e7-9816-eae32cbca0a4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ClientTrafficType",
            "dataType": "string",
            "sourceColumn": "ClientTrafficType",
            "lineageTag": "80d5d986-e8e8-4592-83fd-fa35cc18c828",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliSource",
            "dataType": "string",
            "sourceColumn": "PotCliSource",
            "lineageTag": "9ce91cd4-6b2b-459d-97f2-82c505929afd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Трафик",
            "dataType": "int64",
            "sourceColumn": "Трафик",
            "formatString": "0",
            "lineageTag": "9d143890-1bed-477e-9dc5-a832020e8abf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "21cedfb2-c17e-496e-9413-1b5a18285002",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "wkDiff",
            "dataType": "int64",
            "sourceColumn": "wkDiff",
            "formatString": "0",
            "lineageTag": "e1b1d1c6-b76b-43f4-a4bc-f2da7afb8d69",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "final date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK(crmTrafficAtomIdBeforeReplace[DateComagic]),crmTrafficAtomIdBeforeReplace[DateTraffic],crmTrafficAtomIdBeforeReplace[DateComagic])",
            "formatString": "General Date",
            "lineageTag": "7c9e1f37-90f3-4ace-967d-080ebefd3944",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmTrafficAtomIdBeforeReplace-dc8fc0b7-faaf-4e93-81a9-7adc3b040370",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[crmClientTraffic_attNew_AtomIdBeforeReplace]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"AtomIdFinal\", \"AtomIdFinal\"}, {\"DateTraffic\", \"DateTraffic\"}, {\"DateComagic\", \"DateComagic\"}, {\"Site\", \"Site\"}, {\"Make\", \"Make\"}, {\"ClientTrafficType\", \"ClientTrafficType\"}, {\"PotCliSource\", \"PotCliSource\"}, {\"Трафик\", \"Трафик\"}, {\"HasComagicCall\", \"HasComagicCall\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"AtomIdFinal\", Int64.Type}, {\"DateTraffic\", type datetime}, {\"DateComagic\", type datetime}, {\"Site\", type text}, {\"Make\", type text}, {\"ClientTrafficType\", type text}, {\"PotCliSource\", type text}, {\"Трафик\", Int64.Type}, {\"HasComagicCall\", type text}}),",
                "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Changed Type\", \"wkDiff\", each Duration.Days((Date.StartOfWeek([DateTraffic],Day.Monday) - Date.StartOfWeek([DateComagic],Day.Monday))) / 7, Int64.Type)",
                "in",
                "    #\"Добавлен пользовательский объект\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmClientPotCliAtomIdBeforeReplace",
        "lineageTag": "5c4ec867-bbcc-468d-8fea-f6cd0ee73426",
        "columns": [
          {
            "name": "WhenCreated",
            "dataType": "dateTime",
            "sourceColumn": "WhenCreated",
            "formatString": "General Date",
            "lineageTag": "f9b7b79c-eb83-4c61-93cb-ebb70e6f551a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliDepth",
            "dataType": "string",
            "sourceColumn": "PotCliDepth",
            "lineageTag": "e2e6de66-8dbe-4702-9ccd-97c153f7e467",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "39db9128-1319-418e-b427-efa1e712affc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Площадка МТ РКП",
            "dataType": "string",
            "sourceColumn": "Площадка МТ РКП",
            "lineageTag": "51111f48-abf2-4fd9-919b-4ea4d6a4f554",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "aa27a4d0-93e8-4fa7-8f6f-6185297978f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "General Date",
            "lineageTag": "577928b6-f74f-407d-a93c-6975a1d4b6ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliCounts",
            "dataType": "int64",
            "sourceColumn": "PotCliCounts",
            "formatString": "0",
            "lineageTag": "4515a0cd-bc7d-4308-a972-28858dee02ab",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП статус",
            "dataType": "string",
            "sourceColumn": "РКП статус",
            "lineageTag": "3216f5be-0721-4852-af0f-712f11a8acf4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча назначена",
            "dataType": "int64",
            "sourceColumn": "3 Встреча назначена",
            "formatString": "0",
            "lineageTag": "b8933833-9b4d-451a-8d0a-939c039d0566",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "3 Встреча",
            "dataType": "int64",
            "sourceColumn": "3 Встреча",
            "formatString": "0",
            "lineageTag": "79ea8259-cfc8-462b-a020-d297dbe8ed38",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв назначен",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв назначен",
            "formatString": "0",
            "lineageTag": "7edfb981-ac62-49e1-8ed4-99d88ff02d36",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "4 Тест-драйв",
            "dataType": "int64",
            "sourceColumn": "4 Тест-драйв",
            "formatString": "0",
            "lineageTag": "3bca9719-6c37-46b3-a6da-2c32a3c0630c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "5 Предложение",
            "dataType": "int64",
            "sourceColumn": "5 Предложение",
            "formatString": "0",
            "lineageTag": "825884d8-f6ae-4435-af4b-426573c30e8b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "6 Сделка",
            "dataType": "int64",
            "sourceColumn": "6 Сделка",
            "formatString": "0",
            "lineageTag": "191f9929-072e-4ba4-9037-7b0c301c1433",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "7 Выдача",
            "dataType": "int64",
            "sourceColumn": "7 Выдача",
            "formatString": "0",
            "lineageTag": "dd3c6f38-616c-462f-bbee-894908db354c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Расторжение",
            "dataType": "int64",
            "sourceColumn": "Расторжение",
            "formatString": "0",
            "lineageTag": "29709639-6b3d-4d38-a11a-d942aa979b0a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП — Есть хотя-бы одно из событий",
            "dataType": "int64",
            "sourceColumn": "РКП — Есть хотя-бы одно из событий",
            "formatString": "0",
            "lineageTag": "8f15689e-0803-423d-ae1b-c060eaa89e79",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "comagic_starttime",
            "dataType": "dateTime",
            "sourceColumn": "comagic_starttime",
            "formatString": "General Date",
            "lineageTag": "f5b02740-c7e1-49f5-8b46-e2d915841f7f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "traffic_created",
            "dataType": "dateTime",
            "sourceColumn": "traffic_created",
            "formatString": "General Date",
            "lineageTag": "bad05ee5-6029-481f-aef5-900f77582a56",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "trafic_finded",
            "dataType": "string",
            "sourceColumn": "trafic_finded",
            "lineageTag": "7b32bd62-8dfc-40e3-8e78-6d7ea1c262fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "comagic_finded",
            "dataType": "string",
            "sourceColumn": "comagic_finded",
            "lineageTag": "1eb35c58-a122-47dd-9c7a-127ef843090d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "f9431fc8-c751-416f-8ceb-fadd9524570e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmClientPotCliAtomIdBeforeReplace-85998a51-a4f4-45d3-9543-4a6a1ac23cd4",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT    *   FROM [pivotparts].[crmClientPotCli_AtomIdBeforeReplace]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"WhenCreated\", \"WhenCreated\"}, {\"PotCliDepth\", \"PotCliDepth\"}, {\"Make\", \"Make\"}, {\"Site\", \"Site\"}, {\"AtomId\", \"AtomId\"}, {\"date\", \"date\"}, {\"PotCliCounts\", \"PotCliCounts\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"WhenCreated\", type datetime}, {\"PotCliDepth\", type text}, {\"Make\", type text}, {\"Site\", type text}, {\"AtomId\", Int64.Type}, {\"date\", type datetime}, {\"PotCliCounts\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Site\", \"Площадка МТ РКП\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "crmCarSaleAtomIdBeforeReplace",
        "lineageTag": "aec18f2f-b454-4839-86d0-325923404465",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "Long Date",
            "lineageTag": "456fdb9e-427a-41a3-9f95-0eebf45f28b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "dea64ad0-2054-4ec1-a210-18913d66b112",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCreated_CarSale",
            "dataType": "dateTime",
            "sourceColumn": "DateCreated_CarSale",
            "formatString": "Long Date",
            "lineageTag": "9c258733-bd16-4fb9-bfda-246b2b6b0e71",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "dateEvent",
            "dataType": "dateTime",
            "sourceColumn": "dateEvent",
            "formatString": "Long Date",
            "lineageTag": "7569152e-9238-4009-9651-1a67f3bbb417",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "lineageTag": "5ff632da-1c10-4121-a428-c4e750c8442b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "e2d8f318-a2ac-4e7b-acd7-7c63a5f9300d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "штуки",
            "dataType": "int64",
            "sourceColumn": "штуки",
            "formatString": "0",
            "lineageTag": "1719b4b2-3076-4bd9-9ca2-d70d4cda20ad",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты_шт",
            "dataType": "int64",
            "sourceColumn": "Контракты_шт",
            "formatString": "0",
            "lineageTag": "95c4a4c2-f2c7-4534-8532-0a9b9e853fd9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Контракты_сумма_₽",
            "formatString": "0",
            "lineageTag": "c2b4fb4f-991a-4e7c-be60-ee279316bb00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_шт",
            "dataType": "int64",
            "sourceColumn": "Сделки_шт",
            "formatString": "0",
            "lineageTag": "fbe10735-4e86-45a0-aa75-6086460f9ec1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки_сумма_₽",
            "dataType": "int64",
            "sourceColumn": "Сделки_сумма_₽",
            "formatString": "0",
            "lineageTag": "e21f9816-f10f-4b5d-a07f-0444ded9ef30",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_шт",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_шт",
            "formatString": "0",
            "lineageTag": "1cc24b93-325e-492e-9bb5-8a0d6edc3a41",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Архив предложений_₽",
            "dataType": "int64",
            "sourceColumn": "Архив предложений_₽",
            "formatString": "0",
            "lineageTag": "9ab2e1b1-f870-4fa1-9ead-3cd7e65c40bb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_шт",
            "dataType": "int64",
            "sourceColumn": "Открытая_шт",
            "formatString": "0",
            "lineageTag": "10101b73-f733-45d5-adae-cbd9d0a495cc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Открытая_₽",
            "dataType": "double",
            "sourceColumn": "Открытая_₽",
            "lineageTag": "4fa12d07-7472-426a-bd7c-13f908bf445f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_шт",
            "dataType": "int64",
            "sourceColumn": "Несостоявшаяся_шт",
            "formatString": "0",
            "lineageTag": "05210399-0a4d-42cd-b8e8-4cc7c17d925a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Несостоявшаяся_₽",
            "dataType": "double",
            "sourceColumn": "Несостоявшаяся_₽",
            "lineageTag": "f1af71de-5ec8-44a0-be55-0e059671749e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "AttributionId",
            "dataType": "int64",
            "sourceColumn": "AttributionId",
            "formatString": "0",
            "lineageTag": "063065bd-a05e-4777-9ad9-143729c59cb6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmCarSaleAtomIdBeforeReplace-641b7505-2b7a-4d12-baa8-75be24ff7365",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"SELECT * FROM [pivotparts].[crmCarSale_AtomIdBeforeReplace]\", CommandTimeout=#duration(0, 2, 0, 0)]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"date\", \"date\"}, {\"AtomId\", \"AtomId\"}, {\"DateCreated_CarSale\", \"DateCreated_CarSale\"}, {\"dateEvent\", \"dateEvent\"}, {\"Make\", \"Make\"},  {\"Site\", \"Site\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"date\", type date}, {\"AtomId\", Int64.Type},  {\"DateCreated_CarSale\", type date}, {\"dateEvent\", type date}, {\"Make\", type text}, {\"Site\", type text}, {\"штуки\", Int64.Type}, {\"Контракты_шт\", Int64.Type}, {\"Контракты_сумма_₽\", Int64.Type}, {\"Сделки_шт\", Int64.Type}, {\"Сделки_сумма_₽\", Int64.Type}, {\"Архив предложений_шт\", Int64.Type}, {\"Архив предложений_₽\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "PeriodType",
        "lineageTag": "6828aa44-0d82-4434-af8c-04d6c4b309e4",
        "columns": [
          {
            "name": "Период",
            "dataType": "string",
            "sourceColumn": "Период",
            "sortByColumn": "Id",
            "lineageTag": "7da72ca0-a2c7-42f4-90da-5bd28df35ead",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "string",
            "sourceColumn": "Id",
            "lineageTag": "044f12d8-0def-4d4c-9af8-3868609f5ccf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "PeriodType-fdbefb2e-2306-4706-9f00-4fef84967f38",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #table({\"Id\",\"Период\"},{{1,\"Текущий\"},{2,\"Предыдущий\"},{3,\"Среднее за последние 24 недели\"}})",
                "in",
                "    Источник"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Звонки, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Comagic звонки все | Прошедшая неделя],",
              "            [Comagic звонки все]",
              "        ),",
              "    \"Предыдущий\", [Звонки ПП],",
              "    \"Среднее за последние 24 недели\", [Среднее количество звонков, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "adccf917-ee21-424e-aa92-5ebdf2b264b8"
          },
          {
            "name": "Расход, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Расход без НДС | Прошедшая неделя],",
              "            [Расход без НДС]",
              "        ),",
              "    \"Предыдущий\", [Расход ПП],",
              "    \"Среднее за последние 24 недели\", [Средний расход, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "4597eda3-2bab-49ac-9504-3ec36a9ddc93",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "ОП, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Comagic Тэг «ОП» | Прошедшая неделя],",
              "            [Comagic Тэг «ОП»]",
              "        ),",
              "    \"Предыдущий\", [Звонки С ОП ПП],",
              "    \"Среднее за последние 24 недели\", [Средние количество тегов ОП, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6f172cc7-e15e-4d74-949d-b214a6ec1d97"
          },
          {
            "name": "Трафик новый авто, без замены AtomId, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Трафик новый авто, без замены AtomId | Прошедшая неделя],",
              "            [Трафик новый авто, без замены AtomId]",
              "        ),",
              "    \"Предыдущий\", [Трафик (новый авто) ПП],",
              "    \"Среднее за последние 24 недели\",[Средний трафик, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3c0cadfd-6f20-4146-98bc-8f0a982c95d4"
          },
          {
            "name": "РКП, без замены AtomId, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [РКП, без замены AtomId | Прошедшая неделя],",
              "            [РКП, без замены AtomId]",
              "        ),",
              "    \"Предыдущий\", [РКП ПП],",
              "    \"Среднее за последние 24 недели\", [Среднее количество РКП, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "РКП",
            "lineageTag": "dcb74f35-1239-4e10-8a8d-7caa2a0bc1fb"
          },
          {
            "name": "CPC, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\", IF ( [SelectedCamparePeriodType] = 2, [CPC | Прошедшая неделя], [CPC] ),",
              "    \"Предыдущий\", [CPC ПП],",
              "    \"Среднее за последние 24 недели\", [Среднее CPC за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "0983a29c-22c7-473b-9dec-198b52d0634b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Клики → трафик, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Клики → Трафик новый авто, без замены AtomId | Прошедшая неделя],",
              "            [Клики → Трафик новый авто, без замены AtomId]",
              "        ),",
              "    \"Предыдущий\", [Клики → Трафик новый авто, без замены AtomId ПП],",
              "    \"Среднее за последние 24 недели\", [Средняя конверсия из кликов в трафик, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29a591d0-2bb0-4b48-8d57-415e1317e828"
          },
          {
            "name": "Стоимость трафика, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Трафик новый авто, без замены AtomId, цена | Прошедшая неделя],",
              "            [Трафик новый авто, без замены AtomId, цена]",
              "        ),",
              "    \"Предыдущий\", [Трафик новый авто, без замены AtomId, цена ПП],",
              "    \"Среднее за последние 24 недели\", [Средняя стоимость трафика, за последние 6 месяцев],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "64b938c5-c99d-45c1-b9ff-24c7ef095f5f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Средний расход, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( Pivot, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"Spent\", SUM ( Pivot[Spent] )",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [Spent]",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "c5012a47-b659-4b11-8f08-20a293df4dde"
          },
          {
            "name": "MinDate 6 month",
            "expression": [
              "",
              "[MinDate] - 161"
            ],
            "formatString": "General Date",
            "lineageTag": "155a3c76-d57f-47ca-8631-1f10704a940b"
          },
          {
            "name": "Средний трафик, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( crmTrafficAtomIdBeforeReplace, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"Traffic\", SUM ( crmTrafficAtomIdBeforeReplace[Трафик] )",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            ),",
              "            crmTrafficAtomIdBeforeReplace[ClientTrafficType]=\"Новый автомобиль\"",
              "        ),",
              "        [Traffic]",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "9dc30753-d0bb-45d7-8ceb-a56113c77f97"
          },
          {
            "name": "Средний ОП ручной, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( ComagicCalls, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"TagOP\", SUM(ComagicCalls[ComagicCallsTag-ОП]) ",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [TagOP]                ",
              "    )"
            ],
            "lineageTag": "bb065b8d-4a15-404a-89d3-ff7fd654851a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Средний ОП автоматический, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( ComagicCalls, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"TagOP\", SUM(ComagicCalls[ComagicCallsTag-ОП-Только автоматический, без ручного]) ",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [TagOP]                ",
              "    )"
            ],
            "lineageTag": "e29af6a8-3132-462d-a060-8eda18a94acf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Средний ОП ручной и автоматический, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( ComagicCalls, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"TagOP\", SUM(ComagicCalls[ComagicCallsTag-ОП-Только автоматический, без ручного]) + SUM(ComagicCalls[ComagicCallsTag-ОП])",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [TagOP]                ",
              "    ) "
            ],
            "lineageTag": "32c74af3-1f66-4fb0-a7e3-863f38df2176",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Средние количество тегов ОП, за последние 6 месяцев",
            "expression": [
              "",
              " IF(",
              "HASONEVALUE(TagOpTypes[Name]),",
              "    SWITCH(VALUES(TagOpTypes[Name]),",
              "        \"ОП\",[Средний ОП ручной, за последние 6 месяцев],",
              "        \"ОП Только автоматические\",[Средний ОП автоматический, за последние 6 месяцев]",
              "    ),",
              "    [Средний ОП ручной и автоматический, за последние 6 месяцев] ",
              ")"
            ],
            "lineageTag": "528e8589-dc49-4fb1-b7e0-3788375904df",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Среднее количество звонков, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( ComagicCalls, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"Calls\", SUM(ComagicCalls[ComagicCalls])",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [Calls]                ",
              "    )"
            ],
            "lineageTag": "6d70570a-9443-4cb9-8ffd-261a71e62755",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Среднее количество РКП, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( crmClientPotCli, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"RKP\", SUM(crmClientPotCli[PotCliCounts])",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [RKP]                ",
              "    )"
            ],
            "lineageTag": "bfdd63a7-bf65-489a-8287-e02e9daa0981",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Среднее количество кликов, за последние 6 месяцев",
            "expression": [
              "",
              "VAR mDate = [MinDate 6 month]",
              "VAR maxDate = [_MaxDate]",
              "RETURN",
              "    AVERAGEX (",
              "        CALCULATETABLE (",
              "            SUMMARIZE (",
              "                ADDCOLUMNS ( Pivot, \"Week\", RELATED ( 'Calendar'[Недели] ) ),",
              "                [Week],",
              "                \"Clicks\", SUMX(Pivot,if([Клики или сессии]=\"Clicks\",Pivot[Clicks],Pivot[Sessions]))",
              "            ),",
              "            FILTER (",
              "                ALL ( 'Calendar' ),",
              "                'Calendar'[Date] >= mDate",
              "                    && 'Calendar'[Date] <= maxDate",
              "            )",
              "        ),",
              "        [Clicks]                ",
              "    )",
              ""
            ],
            "lineageTag": "645c3303-6b20-42e6-a4b7-0f1ce0a58f27",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Среднее CPC за последние 6 месяцев",
            "expression": "DIVIDE([Средний расход, за последние 6 месяцев], [Среднее количество кликов, за последние 6 месяцев],BLANK()) ",
            "lineageTag": "87bd6459-6c78-4904-9bc8-0f66cefadca0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Средняя конверсия из кликов в трафик, за последние 6 месяцев",
            "expression": "DIVIDE([Средний трафик, за последние 6 месяцев],[Среднее количество кликов, за последние 6 месяцев],BLANK())",
            "lineageTag": "625e2200-d928-43c5-bf9d-19a1e247f9fe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Средняя стоимость трафика, за последние 6 месяцев",
            "expression": "DIVIDE([Средний расход, за последние 6 месяцев],[Средний трафик, за последние 6 месяцев],BLANK()) ",
            "lineageTag": "2d0e257f-d280-4e90-bfce-d332ab79f360",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Клики, по периодам",
            "expression": [
              "SWITCH (",
              "    FIRSTNONBLANK ( PeriodType[Период], PeriodType[Период] ),",
              "    \"Текущий\",",
              "        IF (",
              "            [SelectedCamparePeriodType] = 2,",
              "            [Клики | Прошедшая неделя],",
              "            [Клики]",
              "        ),",
              "    \"Предыдущий\", [Клики ПП],",
              "    \"Среднее за последние 24 недели\", [Среднее количество кликов, за последние 6 месяцев],",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "f31f1143-c78d-4313-9dc5-8ae679ac067d"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "PeriodType (2)",
        "lineageTag": "76618576-c19b-409e-becc-5a7356c52199",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "b67958c0-2ee8-4921-bbeb-eb2a7e773bc5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "84759750-2f7f-4901-a145-e7436e07e787",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "PeriodType (2)-a41fc799-5c8d-4447-a348-1ed9817345ba",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUbqw6MLWC7suNl/svLDhYr/Chb1A7hYg3n2xXylWJ1rJCKRmLkJQAcgAURcbLzZc2HBhE1jD3gs7QMpjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Id = _t, Name = _t]),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Id\", Int64.Type}, {\"Name\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Calendar4",
        "lineageTag": "2b0b5963-4063-49f2-a6ad-f13f8e11a842",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Calendar (4)[Date]",
            "formatString": "General Date",
            "lineageTag": "f18c990d-057c-47fe-a8c4-40677ac21583",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Week",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Calendar (4)[Week]",
            "lineageTag": "e121c60f-e390-45d3-941d-32932452c08c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calendar4-1713f920-981f-4723-a981-709411ee0f93",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "UNION('Calendar (4)','Calendar (3)')"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "17001ed5b6774101a54dc02b89130503"
          }
        ]
      },
      {
        "name": "Calendar (4)",
        "lineageTag": "60b4ad15-c018-4586-bf09-1ad5906634d3",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "091f3fb4-568f-485c-835e-298e4ec9e506",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Week",
            "dataType": "string",
            "sourceColumn": "Week",
            "lineageTag": "0f43eba5-ff48-4f31-8314-4dde770a45f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calendar (4)-8738ab34-13f9-4ae4-beb7-8ec95c610f65",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = #\"Calendar (3)\"",
                "in",
                "    Источник"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "W2",
            "expression": "FIRSTNONBLANK('Calendar (4)'[Week],'Calendar (4)'[Week])",
            "lineageTag": "d44e32d1-abca-4842-b931-f81a62c0e7b7"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "GA",
        "lineageTag": "2ed4a14d-cf09-4546-90fb-63b25516fe13",
        "columns": [
          {
            "name": "DateTime",
            "dataType": "dateTime",
            "sourceColumn": "DateTime",
            "formatString": "General Date",
            "lineageTag": "1b3d64c6-5569-480e-8197-1743b7f47021",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "e5adc37c-db3c-4946-9aaf-81a407d71fda",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "ClientId",
            "dataType": "string",
            "sourceColumn": "ClientId",
            "lineageTag": "2e32275d-d9b1-4eeb-9872-b90487302750",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "HostName",
            "dataType": "string",
            "sourceColumn": "HostName",
            "lineageTag": "099af88b-3355-4556-850a-12050ce3a2eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LandingPage",
            "dataType": "string",
            "sourceColumn": "LandingPage",
            "lineageTag": "54c06359-e3e0-47a2-8081-c4fda7049995",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "0f26ae9f-4418-4133-964e-4874f419a9f6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "0bb20083-aa32-4e89-b910-e2206fd9763e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "dc821585-ca49-4fb0-b83e-ef6768195ae4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DeviceTypeId",
            "dataType": "int64",
            "sourceColumn": "DeviceTypeId",
            "formatString": "0",
            "lineageTag": "bfcfc4c7-7ba7-484a-aaa8-ed499c0e6ecb",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sessions",
            "dataType": "int64",
            "sourceColumn": "Sessions",
            "formatString": "0",
            "lineageTag": "34d4b66f-fe3d-4ac5-b509-cf1ea0f1eed1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "GA-ad857d0c-be15-41df-a4b9-e49bd7b8044b",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database),",
                "    pivotparts_GA = Source{[Schema=\"pivotparts\",Item=\"GA\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(pivotparts_GA, each [Date] >= #date(2020, 1, 1))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "сессии",
            "expression": "SUM(GA[Sessions])",
            "formatString": "#,0",
            "lineageTag": "d03b45f7-9d0f-4120-8bea-5a9e23f1ecaa",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "уник посетителей",
            "expression": "countrows(values(GA[ClientId]))",
            "formatString": "#,0",
            "lineageTag": "ca7806a2-d9e7-417c-a687-510080ac5983",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "Dynamic1",
        "lineageTag": "4d1db965-2971-4af9-a711-7139dd4bf0de",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "008331bb-8063-4851-b3dc-1ca86bc1cfce",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Measure",
            "dataType": "string",
            "sourceColumn": "Measure",
            "lineageTag": "e9a972a9-54bc-4deb-94c5-f97579130a10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dynamic1-9d63f609-58b0-41d0-9ab0-1f15c25dee8d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUbrYeGHrxUYguePCDqVYnWglI5Bg84W9QIFdegoX9l/YB1bSdGEHEG+9sBukLBYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Id = _t, Measure = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Dynamic1",
            "expression": [
              "switch(SELECTEDVALUE(Dynamic1[Id]),",
              "1, [сессии],",
              "2,[уник посетителей],",
              "[сессии]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "77ae6604-2ac7-4694-9394-b0e3db47a2c4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "title_table_Dinamic1",
            "expression": [
              "",
              "var m = ",
              "switch(SELECTEDVALUE(Dynamic1[Id]),",
              "1, \"Количество сессий\",",
              "2,\"Количество посетителей\",",
              "\"Количество сессий\"",
              ")",
              "",
              "var p = SELECTEDVALUE(CalendarPeriodChoice[Period])",
              "return ",
              "m &\", период: \"& p&\" (дата в таблице - начало периода)\""
            ],
            "lineageTag": "eaaa0aab-7ead-4398-8574-b25860a47ff2"
          },
          {
            "name": "Dynamic2less3brand",
            "expression": [
              "",
              "if([isShowBrandCompare], [Dynamic1])"
            ],
            "formatString": "0",
            "lineageTag": "6f896c4d-2b16-4606-8695-a6ef958c7524"
          },
          {
            "name": "Dynamic2less3host",
            "expression": [
              "",
              "if( Dynamic1[isShowHostCompare], [Dynamic1])"
            ],
            "formatString": "0",
            "lineageTag": "ee8ee6c5-49dc-4c53-843a-cb82b6b8f422"
          },
          {
            "name": "isShowBrandCompare",
            "expression": "COUNTROWS(ALLSELECTED(HostNames[carBrand])) <=3",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e534dc25-2efe-4f4f-b040-117016fd7163"
          },
          {
            "name": "isShowHostCompare",
            "expression": "COUNTROWS(ALLSELECTED(HostNames)) <= 3",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "31ee2b3c-0207-436a-af17-9ba69d14789e"
          },
          {
            "name": "title_CompareBrand",
            "expression": [
              "",
              "if(not([isShowBrandCompare]),",
              "\"Выберите для сравнения не более трех брендов\"",
              ")"
            ],
            "lineageTag": "e95c439b-a707-49e9-8064-75cd7ed225e7"
          },
          {
            "name": "title_CompareHost",
            "expression": [
              "",
              "if(not([isShowHostCompare]),",
              "\"Выберите для сравнения не более трех сайтов\"",
              ")"
            ],
            "lineageTag": "431fce98-a793-4095-9521-fac0a23c48f5"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "CalendarPeriodChoice",
        "lineageTag": "bae2f0c7-b871-4185-8a10-a60c3b1d7c2c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date1",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date1]",
            "formatString": "Short Date",
            "lineageTag": "a88db124-35cb-4084-98aa-d6f8b2e3bec5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Date2",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date2]",
            "formatString": "Short Date",
            "lineageTag": "060bdc57-c063-4338-923f-e1167b18e7a2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Period",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Period]",
            "lineageTag": "b2de7fbb-f7a4-4de0-89cd-bb2b21a3c9c3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalendarPeriodChoice-12c9ffaa-8d14-41d0-9391-a3614b427791",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "var m = SELECTCOLUMNS('Calendar', \"Date1\", 'Calendar'[Date], \"Date2\", date(year('Calendar'[Date]), MONTH('Calendar'[Date]),1), \"Period\", \"Месяц\")",
                "var w = SELECTCOLUMNS('Calendar', \"Date1\", 'Calendar'[Date], \"Date2\", 'Calendar'[Неделя начинается с], \"Period\", \"Неделя\")",
                "return union(m,w)"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c8e7497de0814e71ac4558df0ecfdd7d"
          }
        ]
      },
      {
        "name": "CrmUsed",
        "lineageTag": "809b70ef-da16-44f9-8451-5e106b62b672",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "4a8e3806-259a-4ea3-b6d6-31e6d188cfba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "ba3d448c-3284-4f07-b6df-db1fdf296155",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Leads",
            "dataType": "int64",
            "sourceColumn": "Leads",
            "formatString": "0",
            "lineageTag": "5fdcf677-9760-4600-a620-ad42720951f6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП",
            "dataType": "int64",
            "sourceColumn": "РКП",
            "formatString": "0",
            "lineageTag": "e220a591-cf88-449b-8268-d3db3bec96c0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "РКП эфф",
            "dataType": "int64",
            "sourceColumn": "РКП эфф",
            "formatString": "0",
            "lineageTag": "ec8c8cc7-b683-40b5-b2b7-010fa5fcf735",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateEvent",
            "dataType": "dateTime",
            "sourceColumn": "DateEvent",
            "formatString": "General Date",
            "lineageTag": "31396be3-3cca-4710-bcc8-c3127ba5fee4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Трафик",
            "dataType": "int64",
            "sourceColumn": "Трафик",
            "formatString": "0",
            "lineageTag": "82130f3f-aba0-4209-8c86-c684c4afa84e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Контракты",
            "dataType": "int64",
            "sourceColumn": "Контракты",
            "formatString": "0",
            "lineageTag": "64eca609-b4f3-40b7-8a9a-696a67be56c5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Сделки",
            "dataType": "int64",
            "sourceColumn": "Сделки",
            "formatString": "0",
            "lineageTag": "8942162b-0b83-4298-be76-1cde0a345d24",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CrmUsed-408cf6af-4927-4ec9-9b22-084f45d92dbb",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from [pivotparts].[CrmUserCars]\", CreateNavigationProperties=false, CommandTimeout=#duration(0, 2, 0, 0)])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Leads_UsedCar",
            "expression": "CALCULATE(SUm(CrmUsed[Leads]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "#,0",
            "lineageTag": "a5e93e03-67a6-464a-913b-cadb41c0f144",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Clicks → Leads_UsedCars",
            "expression": "DIVIDE([Leads_UsedCar], [Клики])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "60295f18-d2e0-4288-9815-2f23b5a9a551",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Leads_UsedCar_cost",
            "expression": "DIVIDE([Расход без НДС], [Leads_UsedCar])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "00f5b164-3aa2-4af5-adde-49be31be29ce",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "RKP_eff_UsedCar",
            "expression": "CALCULATE(SUM(CrmUsed[РКП эфф]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "#,0",
            "lineageTag": "16860ced-b0c5-476b-a88b-1b62dd96a99e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Leads_UsedCars → RKP_eff_UserCars",
            "expression": "DIVIDE(CrmUsed[RKP_eff_UsedCar],[Leads_UsedCar])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "76bd9b31-e3d9-488f-9516-871dbcc782e4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RKP_eff_UserCars_cost",
            "expression": "DIVIDE([Расход без НДС],CrmUsed[RKP_eff_UsedCar])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "28c7c95a-59d5-42bf-9409-66abf64dbccf",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Leads_UsedCar_DateEvent",
            "expression": "CALCULATE(SUm(CrmUsed[Leads]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "0",
            "lineageTag": "2c3024ff-762e-4bca-b2ae-8123e06023a0"
          },
          {
            "name": "RKP_eff_UsedCar_DateEvent",
            "expression": "CALCULATE(SUM(CrmUsed[РКП эфф]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "#,0",
            "lineageTag": "aa2b373b-7576-4f3e-8d40-81b780e0a530",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RKP_UsedCar_DateEvent",
            "expression": "CALCULATE(SUM(CrmUsed[РКП]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "#,0",
            "lineageTag": "590b25ad-4bca-462f-9127-e0b4048b04ef",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RKP_UsedCar",
            "expression": "CALCULATE(SUM(CrmUsed[РКП]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "0",
            "lineageTag": "0210d181-982b-46a8-a829-786d20f747d5"
          },
          {
            "name": "Traffic_UsedCar",
            "expression": "CALCULATE(SUM(CrmUsed[Трафик]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "#,0",
            "lineageTag": "592cd567-ccfd-4756-b290-f8e1960c54f6",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Traffic_UsedCar_DateEvent",
            "expression": "CALCULATE(SUM(CrmUsed[Трафик]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "#,0",
            "lineageTag": "5131cc2b-4e12-4d0a-a776-ba3a9b53d95c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Contract_UsedCar",
            "expression": "CALCULATE(SUM('CrmUsed'[Контракты]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "#,0",
            "lineageTag": "767c25ec-49f3-498b-9668-1cd46a17425f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Contract_UsedCar_EventDate",
            "expression": "CALCULATE(SUM('CrmUsed'[Контракты]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "#,0",
            "lineageTag": "350f94e0-315a-49cf-b282-a18ab8ef9391",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Sale_UsedCar",
            "expression": "CALCULATE(SUM('CrmUsed'[Сделки]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[Date]))",
            "formatString": "#,0",
            "lineageTag": "174a2ecc-0c0c-45c1-a034-035afcb6d496",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Sale_UsedCar_DateEvent",
            "expression": "CALCULATE(SUM('CrmUsed'[Сделки]), USERELATIONSHIP('Calendar'[Date], 'CrmUsed'[DateEvent]))",
            "formatString": "#,0",
            "lineageTag": "f49164b3-94d3-4ea2-90c6-58337e9a3dec",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Contract_UsedCar → Sale_UsedCar",
            "expression": "DIVIDE([Sale_UsedCar],[Contract_UsedCar])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c6014be4-8e8c-4be9-9d09-05a36df866b8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Traffic_UsedCar_cost",
            "expression": "DIVIDE([Расход без НДС],[Traffic_UsedCar])",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "1df842b6-9e9c-4b80-a33e-de0ad568f1a7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Traffic_UsedCar → RKP_UsedCar",
            "expression": "DIVIDE([RKP_UsedCar],[Traffic_UsedCar],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f76342fc-1793-4bdd-a336-5896c870477b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RKP_UsedCar_cost",
            "expression": "DIVIDE([Расход без НДС],[RKP_UsedCar],BLANk())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "d63d4136-7b46-47ab-8605-b819a9dcd850",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Sale_UsedCar_cost",
            "expression": "DIVIDE([Расход без НДС],[Sale_UsedCar],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "c732c564-d115-4981-a0e5-4e47b3b655b2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Contract_UsedCar_cost",
            "expression": "DIVIDE([Расход без НДС],[Contract_UsedCar],BLANK())",
            "formatString": "#,0\\ \"₽\";-#,0\\ \"₽\";#,0\\ \"₽\"",
            "lineageTag": "32d1af5d-9174-4ded-8992-c4c7c5aaf943",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "crmTraffic_MTBrand",
        "lineageTag": "04900067-ae89-486d-9f13-f10af05974a5",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "f0fc443f-475a-4a77-b36c-35fec8865a54",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "cd0ea6c4-14d9-45b6-b5a2-bafeece364e5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TrafficType",
            "dataType": "string",
            "sourceColumn": "TrafficType",
            "lineageTag": "19fa8bb2-e0cd-4fce-a750-d582722f1560",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "25b98c19-28e3-4a2d-9d9d-3d748724683b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Traffic",
            "dataType": "int64",
            "sourceColumn": "Traffic",
            "formatString": "#,0",
            "lineageTag": "4cd75271-4e21-4966-bed3-871d0dba3178",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PotCliSource",
            "dataType": "string",
            "sourceColumn": "PotCliSource",
            "lineageTag": "94bf8eac-07f6-4b24-9c91-5c3c5970df3e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "crmTraffic_MTBrand-237dc5a4-dca4-4860-ab29-30999afa6392",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from pivotparts.ClientTraffic_MTBrands\", CommandTimeout=#duration(0, 2, 0, 0)])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ClassifieldCalls_v2",
        "lineageTag": "c3983ebe-ceda-4126-b100-7a1f72eb2859",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "0485757e-abf5-4502-9507-60c7f8a367ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calls",
            "dataType": "int64",
            "sourceColumn": "Calls",
            "formatString": "0",
            "lineageTag": "a81821f0-ea2a-414d-9a24-834b64ea5242",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "General Date",
            "lineageTag": "dceb225d-d851-4547-a9fa-86a4bfb5a547",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ClassifieldCalls_v2",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from pivotparts.ClassifiedsCalls\", CommandTimeout=#duration(0, 2, 0, 0)])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "ClassifieldCalls",
            "expression": "SUm(ClassifieldCalls_v2[Calls]) ",
            "formatString": "0",
            "lineageTag": "737f124d-6f67-43ad-b253-3acb0112b57c"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ClientTraffic_v2",
        "lineageTag": "a916ad77-a2cb-4916-be92-8f5fd59acaef",
        "columns": [
          {
            "name": "AtomId",
            "dataType": "int64",
            "sourceColumn": "AtomId",
            "formatString": "0",
            "lineageTag": "505b32f2-d60d-4537-91b7-d5f856709168",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateCohort",
            "dataType": "dateTime",
            "sourceColumn": "DateCohort",
            "formatString": "General Date",
            "lineageTag": "0488c3c1-f1a5-46d1-ab55-904ef22b2487",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CarBrand",
            "dataType": "string",
            "sourceColumn": "CarBrand",
            "lineageTag": "7073edd4-fd1f-4a20-b5af-a09b7aae8bea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TrafficType",
            "dataType": "string",
            "sourceColumn": "TrafficType",
            "lineageTag": "0838425e-04be-4d47-b81b-49af674ed604",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Traffic",
            "dataType": "int64",
            "sourceColumn": "Traffic",
            "formatString": "0",
            "lineageTag": "0deb637b-bcab-4b66-9141-2bdfde133d7f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ClientTraffic_v2",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(server, database, [Query=\"select * from pivotparts.crmClientTraffic_v2\", CommandTimeout=#duration(0, 2, 0, 0)])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "CRMTraffic",
            "expression": "SUM(ClientTraffic_v2[Traffic])",
            "formatString": "0",
            "lineageTag": "830aee89-94d2-4f75-8f5f-0f2811c4e33f"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a56f595a-d98b-48b8-ad75-5676fe4d9c64",
        "fromTable": "Pivot",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fec6d18a-f8f2-4a8a-b46b-470fe35e0346",
        "fromTable": "Pivot",
        "fromColumn": "DeviceTypeId",
        "toTable": "DeviceTypes",
        "toColumn": "Id"
      },
      {
        "name": "9572fad0-7713-4535-b74f-25ff06ba2747",
        "fromTable": "Pivot",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "f12e5b3c-2fed-4422-bb22-7c8f0a41e860",
        "fromTable": "ComagicCalls",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "b0defa03-242c-40ae-9a1c-79bd66482690",
        "fromTable": "ComagicCalls",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "c37c855c-6b45-42cc-8702-4b21f5507c74",
        "fromTable": "PlansFinal",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fbf02363-39ac-4b8d-8920-d1fecde29a71",
        "fromTable": "PlansFinal",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "15393884-e26e-4a24-ae1f-059cc49cab3e",
        "fromTable": "crmTraffic",
        "fromColumn": "AtomIdFinal",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "99645bda-dbdc-43a5-80a5-6bf51ba67cfa",
        "fromTable": "crmTraffic",
        "fromColumn": "final date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "5f450902-8a9a-4aea-9193-0a36af61bc6f",
        "fromTable": "crmTraffic",
        "fromColumn": "Site",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "0cf3f250-416b-4f47-8fa2-704de3935cd8",
        "fromTable": "crmTraffic",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "a2719a5a-6967-4a73-9a2d-991c60304622",
        "fromTable": "crmClientPotCli",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "e9b2176f-5e3d-45de-8e85-864a4993ba19",
        "fromTable": "crmClientPotCli",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "7f53b4ca-af5b-455b-84bf-e88d3175475b",
        "fromTable": "crmClientPotCli",
        "fromColumn": "WhenCreated",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "f29d819d-9e58-4453-8e2a-3679910163d9",
        "fromTable": "crmClientPotCli",
        "fromColumn": "Площадка МТ РКП",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "8b16c940-fc48-4cb0-9fad-6f6456e9117d",
        "fromTable": "crmClientPotCli",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "5d162807-ca69-48b0-a602-f128f1b0e345",
        "fromTable": "crmCarSale",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "c7ce7e2d-c0f1-4206-904e-2c1904fcb876",
        "fromTable": "crmCarSale",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "b8678862-d51a-4281-9825-b9e4ff8dbe20",
        "fromTable": "crmCarSale",
        "fromColumn": "dateEvent",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "346d21d5-9ebf-4092-a300-f537a20afcda",
        "fromTable": "crmCarSale",
        "fromColumn": "Site",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "6525ea03-a2dc-469f-b425-bc565bf0e60d",
        "fromTable": "crmCarSale",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "9c3e0b9a-d69b-4183-9281-9465f9c2bae2",
        "fromTable": "crmTraffic",
        "fromColumn": "DateTraffic",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "4bd34228-4fac-4e22-80d2-b97d6500346a",
        "fromTable": "AtomsWithExtensions",
        "fromColumn": "Бренд авто",
        "toTable": "crmMakeList",
        "toColumn": "Make",
        "isActive": false
      },
      {
        "name": "6eee17b0-0ac9-4b7b-8911-5caaed07fb24",
        "fromTable": "crmCarSale",
        "fromColumn": "DateCreated_CarSale",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "2587a343-0685-4d57-b5c5-d3c233372d3b",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "4b8235f2-016f-4794-a8c3-943a58a2e99f",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "c80cf9a6-cdc5-49cf-9e4e-73f5125c6341",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "a18615a3-f870-46d3-bdd6-d5114e48219d",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "be928a94-2105-4d51-bce9-749839710016",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "6caaefea-2236-427d-871a-28bc9d48de33",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "Site",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "6e9127c5-59c6-4e2f-bfda-512bf2e822d6",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "AtomIdFinal",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "94f9e98a-62e1-4981-8a27-f3ce4a286759",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "final date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "112a2a82-7568-461a-8ad7-0d4fc30477c0",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "DateTraffic",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "8be98bec-7552-4188-9a6b-90d1d4fcd574",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "Площадка МТ РКП",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "e5c4d1a6-a28f-49a9-86fd-daf2e0ad8c88",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6cccc1e1-273c-45d5-9748-ddcc9d80d375",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "WhenCreated",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "1c8b6f27-1ec5-4f8f-919c-37061ecd289c",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "Site",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "28db7ea7-fc1f-4c87-8492-2defcc9c9bea",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "569a6b74-e32a-45d8-9d1f-1fe2e1207655",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "DateCreated_CarSale",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "91844edf-a583-443b-a848-608269b960d4",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "dateEvent",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "61b49db4-0f66-42b5-ab97-f47ffd999fdc",
        "fromTable": "crmService",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "40e4ada1-5bbc-4058-996e-11961fae6888",
        "fromTable": "crmService",
        "fromColumn": "Бренд МТ",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "4b606e7e-6f46-47d9-8144-6ca6a6fa1256",
        "fromTable": "crmService",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6d880022-2dc0-4811-acdf-68f87a066cbc",
        "fromTable": "crmService",
        "fromColumn": "Site",
        "toTable": "crmSitesList",
        "toColumn": "Площадка"
      },
      {
        "name": "061e410a-3880-4fe0-906a-187d86aa457e",
        "fromTable": "crmServiceProhody",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "0e1afa04-6cf4-4895-b266-aa827d6f5fd2",
        "fromTable": "crmServiceProhody",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "c9ba4b21-046f-46d3-9434-17e8bc475661",
        "fromTable": "crmServiceProhody",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "51ad6116-82c9-4698-b88f-b2c152b0c34a",
        "fromTable": "crmService",
        "fromColumn": "Цех",
        "toTable": "Shop",
        "toColumn": "Цех"
      },
      {
        "name": "04e07aae-6012-4f5c-b310-1ddf78d35626",
        "fromTable": "crmServiceProhody",
        "fromColumn": "Цех",
        "toTable": "Shop",
        "toColumn": "Цех"
      },
      {
        "name": "9d70504e-cd86-49e7-aba6-e2f2305aa626",
        "fromTable": "Cohotrs",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "3936aea2-c068-4405-9bc8-8c366d312f4e",
        "fromTable": "Cohotrs",
        "fromColumn": "date_start",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "0cc9408d-3ba1-4fa1-a1d4-cd934e07b99e",
        "fromTable": "crmService",
        "fromColumn": "WhenCreated",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "31a9cc45-9d8e-4c24-bb85-ed4cb9f7d0d9",
        "fromTable": "crmServiceProhody",
        "fromColumn": "WhenCreated",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "3e45fcbb-f1e4-4ab5-a6e1-ecd5c4bcce0c",
        "fromTable": "AtomWithExtensionsDim",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "1656e9ae-711d-491d-bb10-e71cde4f0c80",
        "fromTable": "AtomWithExtensionsDim",
        "fromColumn": "Dimension",
        "toTable": "Dimensions",
        "toColumn": "Name",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d3b90b4c-5e44-4901-861b-92e3a573d84e",
        "fromTable": "CalendarDim",
        "fromColumn": "Dimension",
        "toTable": "CalendarDimensions",
        "toColumn": "Name"
      },
      {
        "name": "b25cd1c2-1a81-4fb0-aed9-8248d854fc98",
        "fromTable": "CalendarDim",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "83b36d51-5e4e-4953-86fd-2002c123a053",
        "fromTable": "crmTraffic",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "c3c81029-a677-4fae-8650-4f043beada11",
        "fromTable": "ComagicCalls",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "51491dd9-f375-405c-a4ca-90c7d30c2974",
        "fromTable": "Used_crmTraffic",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "59310f18-b05f-474b-96d8-fdb3620f4153",
        "fromTable": "crmClientPotCli",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "8d8a2ffc-82aa-47bd-8040-d75e6070cb00",
        "fromTable": "Used_crmClientPotCli",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "3b069266-5b5d-49f8-a0cf-1990d97bc98b",
        "fromTable": "crmCarSale",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "72aedc1b-0e1d-4538-9ffc-0dc782e62471",
        "fromTable": "Used_crmCarSale",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "3f7a6b3d-347a-44a5-a9f6-dbbcdb2df901",
        "fromTable": "crmService",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "61adafe9-3e46-4db6-a41c-e5a0eff8e47f",
        "fromTable": "crmServiceProhody",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "ea86bf80-8f71-43ea-93b5-d4495a835b03",
        "fromTable": "crmClientPotCliAtomIdBeforeReplace",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "e199cefc-63f4-4126-b5d7-3c82173754ee",
        "fromTable": "crmCarSaleAtomIdBeforeReplace",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "713513c0-1cfb-4b10-bc00-804b5880279d",
        "fromTable": "crmTrafficAtomIdBeforeReplace",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "a3662702-32cb-4b81-b85b-e15f6c98ea1c",
        "fromTable": "crmClientPotCliAtomIdBeforeReplace",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "0f013a2a-0eb3-48f3-92a0-34bcc4480bc3",
        "fromTable": "crmCarSaleAtomIdBeforeReplace",
        "fromColumn": "AttributionId",
        "toTable": "AttributionsNew",
        "toColumn": "AttributionId"
      },
      {
        "name": "b4b4fc27-a4b5-43e7-bbd2-72cdfbf53ebb",
        "fromTable": "crmTrafficAtomIdBeforeReplace",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "5cfa6489-84ce-4128-952d-ea0c3382cefa",
        "fromTable": "crmClientPotCliAtomIdBeforeReplace",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "e6e289de-583f-48f8-aa17-093c4e08415f",
        "fromTable": "crmCarSaleAtomIdBeforeReplace",
        "fromColumn": "Make",
        "toTable": "crmMakeList",
        "toColumn": "Make"
      },
      {
        "name": "b2c9a71b-f4c0-45a0-b37f-4e18afcf3c3f",
        "fromTable": "crmTrafficAtomIdBeforeReplace",
        "fromColumn": "final date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "85f09f03-b710-4bdb-a00a-1e40b1e72b36",
        "fromTable": "crmTrafficAtomIdBeforeReplace",
        "fromColumn": "AtomIdFinal",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "ade61bef-1457-4db7-96e8-1b4e158f6742",
        "fromTable": "crmCarSaleAtomIdBeforeReplace",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "521f693f-71d5-45df-bc7e-a7f2fa5951f1",
        "fromTable": "crmClientPotCliAtomIdBeforeReplace",
        "fromColumn": "date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "cab2456c-b6e9-493a-ad11-f158905d4de8",
        "fromCardinality": "one",
        "fromTable": "PeriodType (2)",
        "fromColumn": "Id",
        "toTable": "CamparePeriodType",
        "toColumn": "Id",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "59a9a026-3613-4829-b1ac-26c14ca706da",
        "fromTable": "GA",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "956a2bd0-b4b6-49f7-83fa-957479d50411",
        "fromTable": "CalendarPeriodChoice",
        "fromColumn": "Date1",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "8b6054de-bac9-4241-9890-07531b9ec1b3",
        "fromTable": "CrmUsed",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "d79a1908-edbc-4cc2-8efd-ea0d8ce25c98",
        "fromTable": "CrmUsed",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "1f893dfc-ed55-4869-ab63-baba5e5be7a1",
        "fromTable": "CrmUsed",
        "fromColumn": "DateEvent",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6f9e5dfc-15c2-4642-9877-55e5a35298b9",
        "fromTable": "crmTraffic_MTBrand",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "2ff031f0-17ee-4c48-9ffc-651065d9d8a9",
        "fromTable": "crmTraffic_MTBrand",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "f7511ca3-3cac-414c-abc1-3f6d601f029b",
        "fromTable": "ClassifieldCalls_v2",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "d7fd351c-6acf-41db-9aa1-04ee28b4d497",
        "fromTable": "ClassifieldCalls_v2",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "2aa77139-2d66-4709-b09a-854720c8fd57",
        "fromTable": "ClientTraffic_v2",
        "fromColumn": "AtomId",
        "toTable": "AtomsWithExtensions",
        "toColumn": "AtomId"
      },
      {
        "name": "1c3ed7ca-594b-43c7-8633-ece23123c537",
        "fromTable": "ClientTraffic_v2",
        "fromColumn": "DateCohort",
        "toTable": "Calendar",
        "toColumn": "Date"
      }
    ],
    "cultures": [
      {
        "name": "ru-RU",
        "linguisticMetadata": {}
      }
    ],
    "roles": [
      {
        "name": "Audi",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "AtomsWithExtensions",
            "filterExpression": "[Бренд авто] = \"Audi\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ba3b2317317f4d5496fb5f99ef795d32"
          }
        ]
      },
      {
        "name": "Main",
        "modelPermission": "read",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1bfd9f1f551b45c799f8bad58db4b1f7"
          }
        ]
      },
      {
        "name": "Artics",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "AtomsWithExtensions",
            "filterExpression": "([Бренд авто] = \"VW\" || [Бренд авто] = \"NFZ_VW\" || [Бренд авто] = \"Mercedes-Benz\")  && ([Канал] = \"Контекстная реклама\" || [Канал]  = \"Organic\")"
          },
          {
            "name": "Cohotrs",
            "filterExpression": "[date_start] >= DATE(2020,9,1)"
          },
          {
            "name": "ComagicCalls",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmCarSale",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmClientPotCli",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmService",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmServiceProhody",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmTraffic",
            "filterExpression": "[final date] >= DATE(2020,9,1)"
          },
          {
            "name": "Pivot",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "PlansFinal",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmCarSale",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmClientPotCli",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmTraffic",
            "filterExpression": "[final date] >= DATE(2020,9,1)"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1e533f0d850c4cef99597cb33d88a9d2"
          }
        ]
      },
      {
        "name": "Tandem",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "AtomsWithExtensions",
            "filterExpression": "([Бренд авто] = \"Skoda\" || [Бренд авто] = \"Citroen\")  && ([Канал] = \"Контекстная реклама\" || [Группа источников] = \"Vkontakte\")"
          },
          {
            "name": "Cohotrs",
            "filterExpression": "[date_start] >= DATE(2020,9,1)"
          },
          {
            "name": "ComagicCalls",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmCarSale",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmClientPotCli",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmService",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmServiceProhody",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "crmTraffic",
            "filterExpression": "[final date] >= DATE(2020,9,1)"
          },
          {
            "name": "Pivot",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "PlansFinal",
            "filterExpression": "[Date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmCarSale",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmClientPotCli",
            "filterExpression": "[date] >= DATE(2020,9,1)"
          },
          {
            "name": "Used_crmTraffic",
            "filterExpression": "[final date] >= DATE(2020,9,1)"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2fb9b4e018f84414ab1b35b3738474b5"
          }
        ]
      },
      {
        "name": "orwo",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "AtomsWithExtensions",
            "filterExpression": "AtomsWithExtensions[GA профиль] = \"sales.mercedes-wagner.ru\" || AtomsWithExtensions[GA профиль] = \"audi-vyborgsky.ru\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e9fcbdab6bd548ee9d91ed11f15eeff9"
          }
        ]
      },
      {
        "name": "Changan Contex and ya Maps",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "AtomsWithExtensions",
            "filterExpression": "[Бренд авто] = \"Changan\" && ( [Источник] = \"Карты + Навигатор Yandex\" ||  [Канал] = \"Контекстная реклама\")"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0dce7ebc1c6d42c1b5de44c185590a3c"
          }
        ]
      }
    ],
    "extendedProperties": [
      {
        "type": "json",
        "name": "TabularEditor_DeploymentMetadata",
        "value": {
          "User": "FETISHMATE\\pimpm",
          "Time": "2023-10-10T15:13:23.8394817+03:00",
          "ClientMachine": "FETISHMATE",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "2.18.8529.27318"
        }
      }
    ],
    "expressions": [
      {
        "name": "server",
        "kind": "m",
        "expression": "\"77.223.102.193,13786\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "76a74428-bb5a-4b1b-beb1-7bc44842c2e5",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "database",
        "kind": "m",
        "expression": "\"wagner-auto.ru\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "ea9ebef1-a4f7-4da3-bfbe-bcd3e258e14a",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.942.0 (23.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PlansFinal\",\"AtomsWithExtensions\",\"DeviceTypes\",\"Pivot\",\"Calendar\",\"ComagicCalls\",\"crmTraffic\",\"crmTrafficAtomIdBeforeReplace\",\"crmClientPotCli\",\"crmCarSale\",\"crmSitesList\",\"crmMakeList\",\"MainTableColumns\",\"Comagic Bez RK\",\"Used_crmClientPotCli\",\"Used_crmCarSale\",\"Used_crmTraffic\",\"crmService\",\"crmServiceProhody\",\"Shop\",\"Cohotrs\",\"Measure List 1\",\"Measure List 2\",\"Dimensions\",\"AtomWithExtensionsDim\",\"CamparePeriodType\",\"Calendar (3)\",\"Calendar (4)\",\"CalendarDim\",\"CalendarDimensions\",\"AttributionsNew\",\"crmClientPotCliAtomIdBeforeReplace\",\"crmCarSaleAtomIdBeforeReplace\",\"PeriodType\",\"PeriodType (2)\",\"GA\",\"Dynamic1\",\"server\",\"database\",\"CrmUsed\",\"crmTraffic_MTBrand\",\"ClassifieldCalls_v2\",\"ClientTraffic_v2\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}